/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { Editor } from "brace";
import { YduqsAudioPlayerModel } from "./components/atoms/yduqs-audio-player/yduqs-audio-player.model";
import { YduqsMenuModel } from "./components/atoms/yduqs-menu/yduqs-menu.model";
import { YduqsModulePlaylists } from "./components/patterns/yduqs-module-video/yduqs-module-video.model";
import { YduqsModulesPlaylists } from "./components/patterns/yduqs-playlist-video/yduqs-playlist-video.model";
import { YduqsQuestionsModel } from "./components/patterns/yduqs-questions/yduqs-questions.model";
import { iQuizAnswer } from "./models/yduqs-quiz";
import { iScoreItem } from "./models/yduqs-score";
export namespace Components {
    interface MyStace {
        "autoUpdateContent": boolean;
        "durationBeforeCallback": number;
        "getEditor": () => Promise<Editor>;
        "mode": string;
        "options": any;
        "readOnly": boolean;
        "text": string;
        "theme": string;
        "timeoutSaving": any;
    }
    interface StaceEditor {
        "autoUpdateContent": boolean;
        "durationBeforeCallback": number;
        "getEditor": () => Promise<Editor>;
        "mode": string;
        "options": any;
        "readOnly": boolean;
        "text": string;
        "theme": string;
        "timeoutSaving": any;
    }
    interface YduqsAccordion {
        "outline": boolean;
    }
    interface YduqsAccordionPane {
        "close": () => Promise<void>;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface YduqsAlert {
        "_title": string;
        "btntext"?: string;
        "icon": string;
        "message": string;
        "open": boolean;
        "subtitle"?: string;
        "usematerial"?: boolean;
    }
    interface YduqsAtividadeDiscursiva {
    }
    interface YduqsAudioCard {
        "audiocard_id": string;
        "dark": boolean;
        "equal_height": boolean;
        "group": boolean;
        "outlined": boolean;
        "playAudioStop": () => Promise<void>;
        "playAudioStopSlow": () => Promise<void>;
        "src": string;
        "subtitle_audio_card": string;
        "title_audio_card": string;
    }
    interface YduqsAudioPlayer {
        "audio_id": string;
        "dark": boolean;
        "initialize": (config: YduqsAudioPlayerModel) => Promise<void>;
        "rate": number;
        "settings": YduqsAudioPlayerModel;
        "shortdisplay": boolean;
        "src": string;
    }
    interface YduqsBeforeAfter {
        "after_img": string;
        "after_img_alt": string;
        "after_img_title": string;
        "before_img": string;
        "before_img_alt": string;
        "before_img_title": string;
        "caption": string;
    }
    interface YduqsCaixaFormula {
        "dark": boolean;
        "equal_height": boolean;
        "formula": string;
        "rotate_info": boolean;
        "title_formula": string;
    }
    interface YduqsCard {
        "dark": boolean;
        "equal_height": boolean;
        "outlined": boolean;
        "small": boolean;
    }
    interface YduqsCardBody {
    }
    interface YduqsCardComparativo {
        "dark": boolean;
        "icon": string;
        "outline": boolean;
        "rotate_mobile": boolean;
    }
    interface YduqsCardComparativoBody {
    }
    interface YduqsCardComparativoHeader {
    }
    interface YduqsCardComparativoItem {
    }
    interface YduqsCardDestaque {
        "grade": number;
        "icon": string;
        "outline": boolean;
    }
    interface YduqsCardDestaqueBody {
    }
    interface YduqsCardDestaqueHeader {
    }
    interface YduqsCardFooter {
    }
    interface YduqsCardHeader {
    }
    interface YduqsCardHorizontal {
        "card_icon": string;
        "card_image": string;
        "english": boolean;
        "image_alt": string;
        "image_title": string;
        "isquestion": boolean;
        "spanish": boolean;
    }
    interface YduqsCardIntro {
        "text": string;
    }
    interface YduqsCardModulo {
        "progress": number;
    }
    interface YduqsCardModuloBody {
    }
    interface YduqsCardModuloFooter {
    }
    interface YduqsCardModuloHeader {
    }
    interface YduqsCardSelecionavel {
    }
    interface YduqsCardSelecionavelItem {
        "disabled"?: boolean;
        "isSelected": () => Promise<boolean>;
        "optionid": string;
        "selectItem": () => Promise<void>;
        "selected": boolean;
        "unselectItem": () => Promise<void>;
    }
    interface YduqsCardVideo {
        "active": boolean;
        "border_bottom": boolean;
        "id_video": string;
        "link_video": string;
        "module_video": string;
        "paragraph": string;
        "subtitle_video": string;
        "thumb_video": string;
        "time": string;
        "title_video": string;
        "type_video": string;
    }
    interface YduqsCarousel {
        "english": boolean;
        "next": () => Promise<void>;
        "prev": () => Promise<void>;
        "space": number;
        "spanish": boolean;
    }
    interface YduqsCarouselItem {
    }
    interface YduqsCodeCompiler {
        "code": string;
        "copy": (code: any) => Promise<void>;
        "dark": boolean;
        "exercise_title": string;
        "input_keyboard": string;
        "language_code": string;
    }
    interface YduqsCodeSnipet {
        "code": string;
        "copy": (code: any) => Promise<void>;
        "dark": boolean;
        "input_keyboard": string;
        "language_code": string;
        "size": string;
    }
    interface YduqsCollapse {
        "border": boolean;
        "outline": boolean;
    }
    interface YduqsCollapseContent {
        "aling_collapse": string;
        "close": () => Promise<void>;
        "color_collapse": string;
        "header": string;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
        "size": string;
    }
    interface YduqsCollapseTeoria {
        "border": boolean;
        "outline": boolean;
    }
    interface YduqsCollapseTeoriaContent {
        "close": () => Promise<void>;
        "header": string;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
        "size": string;
        "teoria": boolean;
    }
    interface YduqsConfirm {
        "_title": string;
        "btntext"?: string;
        "icon": string;
        "message": string;
        "open": boolean;
        "subtitle"?: string;
        "usematerial"?: boolean;
    }
    interface YduqsCountdown {
        /**
          * Identificador do Componente
         */
        "_id": string;
        /**
          * Pausa o contador, sem resetar a contagem
          * @returns Promise.resolve
         */
        "pause": () => Promise<void>;
        /**
          * Reinicia a contagem
          * @returns Promise.resolve
         */
        "restart": () => Promise<void>;
        /**
          * Inicia a contagem
          * @returns Promise.resolve
         */
        "start": () => Promise<boolean>;
        /**
          * Para o contador resetando a contagem
          * @returns Promise.resolve
         */
        "stop": () => Promise<void>;
        /**
          * Quantidade de tempo para a contagem em segundos.
         */
        "time": number;
        /**
          * Marcador da contagem de Alerta, em porcentagem;
         */
        "warningMarker": number;
    }
    interface YduqsCover {
        "avatar": Array<any>;
        "background_img": string;
        "background_img_title": string;
        "background_text": string;
        "background_text_mobile": string;
        "colaboradores": () => Promise<void>;
        "colaboradores_nome": Array<any>;
        "collaboration_text": string;
        "contributors": string;
        "cover_preparation": boolean;
        "curadores": () => Promise<void>;
        "english": boolean;
        "lg_title": boolean;
        "link": Array<any>;
        "names_clb": Array<any>;
        "names_prof": Array<any>;
        "professores": Array<any>;
        "spanish": boolean;
        "teacher": string;
        "teacher_avatar": string;
        "teacher_link": string;
        "template_anitta": boolean;
        "template_ibmec": boolean;
        "title_cover": string;
        "title_size": string;
        "xl_title": boolean;
    }
    interface YduqsCoverLab {
        "background_img": string;
        "loading": boolean;
        "subtitle_cover": string;
        "title_cover": string;
        "to_page_init_lab": string;
    }
    interface YduqsCoverStageLab {
        /**
          * Texto de Título da Capa
         */
        "_title": string;
        /**
          * Lista de ações (botões) visíveis na Capa
         */
        "actions": any;
        /**
          * Imagem de Fundo da Capa
         */
        "background": string;
        /**
          * Texto de Descríção
         */
        "description": string;
        /**
          * Que aparece Sobre o Titulo. Se omitido, será mostrado o texto 'Fase %phaseNumber%'
         */
        "overtitle": string;
        /**
          * Numero da Fase
         */
        "phaseNumber": number;
    }
    interface YduqsDestaqueTexto {
        "size": string;
    }
    interface YduqsDropdown {
        "colunas": string;
        "createOptionsDrop": () => Promise<void>;
        "createOptionsSelect": () => Promise<void>;
        "identificador": string;
        "tipo": string;
        "withcheck": boolean;
    }
    interface YduqsFeedbackThumb {
        /**
          * Classe CSS adicional
         */
        "_class": string;
        /**
          * Informa se a imagem é positiva ou negativa
         */
        "feedback": boolean;
        /**
          * URL da imagem
         */
        "image": string;
    }
    interface YduqsFooter {
        "btnimprimir": boolean;
        "english": boolean;
        "hide_motivational_messages": boolean;
        "hide_pagination": boolean;
        "hrefbtnprint": string;
        "namebtnimprimir": string;
        "spanish": boolean;
        "template_anitta": boolean;
        "useimage": boolean;
    }
    interface YduqsGalleryVideo {
        "changeModule": (numMod: any) => Promise<void>;
        "changeVideo": (src: any) => Promise<void>;
        "changeVideoExternal": (video: any) => Promise<void>;
        "english": boolean;
        "moduleId": string;
        "module_number": number;
        "module_number_video": number;
        "paragraph_video": string;
        "spanish": boolean;
        "srcVideo": string;
        "subtitle_gallery": string;
        "title_gallery": string;
        "title_video": string;
        "type_video": string;
    }
    interface YduqsHeaderLab {
        /**
          * Título do Laboratório
         */
        "_title": string;
        /**
          * Esconde o btn de Fullscreen
         */
        "hiddenFullscreen": boolean;
        /**
          * Lista de Botões
         */
        "items": string | any[];
    }
    interface YduqsHelper {
    }
    interface YduqsImage {
        "alt": string;
        "covered": boolean;
        "height": string;
        "img_title": string;
        "src": string;
        "width": string;
    }
    interface YduqsInfo {
        /**
          * Título da mensagem
         */
        "_title": string;
        /**
          * Tempo em milessegundos que a mensagem permanece visível
         */
        "delay"?: number;
        /**
          * Identificador do ícone ou base64 do SVG
         */
        "icon": string;
        /**
          * Texto da mensagem
         */
        "message": string;
        /**
          * Mostra/esconde o componente
         */
        "open": boolean;
        /**
          * Subtítulo da mensagem
         */
        "subtitle"?: string;
        /**
          * Informa se o ícone é Material Design ou Base64
         */
        "usematerial"?: boolean;
    }
    interface YduqsInput {
        "alteraInput": (ev: any) => Promise<void>;
        "apagarValor": () => Promise<void>;
        "icon": any;
        "placeh": string;
        "titulo": string;
    }
    interface YduqsInteractiveMedia {
        /**
          * Url com o endereço do arquivo de configuração
         */
        "config": string;
        /**
          * Icone do cabeçalho
         */
        "headericon": string;
        /**
          * Texto descritivo do cabeçalho
         */
        "headertext": string;
        /**
          * Título do Cabeçalho
         */
        "headertitle": string;
    }
    interface YduqsLabError {
        "errors": any[];
        "message"?: string;
    }
    interface YduqsLabIntro {
        /**
          * Título da página, se slot=header não for informado
         */
        "_title"?: string;
        /**
          * Url do Href dos links do cabeçalho e rodapé
         */
        "btnHref"?: string;
        /**
          * Ícone do link do rodapé. Deve ser uma ícone Material.
         */
        "btnIcon"?: string;
        /**
          * Texto dos links do cabeçalho o rodapé.
         */
        "btnText"?: string;
    }
    interface YduqsLabPhase {
        /**
          * Identificador da Próxima Fase. É utilizado no terminos da Atividade de Desafio
         */
        "next": string | number;
        /**
          * Identificador da Fase
         */
        "phase": string | number;
    }
    interface YduqsLabQuestions {
        /**
          * Identificador do Mapa
         */
        "_id": string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
    }
    interface YduqsListas {
        "tamanho": string;
        "tipo": string;
    }
    interface YduqsLoader {
    }
    interface YduqsLoading {
        "hide": () => Promise<void>;
        "isOpen": () => Promise<boolean>;
        "message": string;
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface YduqsMenu {
        "english": boolean;
        "hide_search": boolean;
        "initialize": (config: YduqsMenuModel) => Promise<void>;
        "openGalleryVideo": (video: any) => Promise<void>;
        "position": number;
        "settings": YduqsMenuModel;
        "spanish": boolean;
    }
    interface YduqsModal {
        "_title": string;
        "hide": () => Promise<void>;
        "isopen": boolean;
        "maxbodyheight": number;
        "show": () => Promise<void>;
        "showModal": () => Promise<void>;
        "size": string;
        "variant": string;
    }
    interface YduqsModuleCover {
        "img_cover": string;
        "midia_time": string;
        "number_module": string;
        "objective": string;
        "read_time": string;
        "title_midia_time": string;
        "title_module": string;
        "title_read_time": string;
    }
    interface YduqsModuleRating {
        "cta": string;
        "english": boolean;
        "icon": string;
        "module": string;
        "spanish": boolean;
        "tamanho": string;
    }
    interface YduqsModuleVideo {
        "active_video": string;
        "initialize": (config: YduqsModulePlaylists) => Promise<void>;
        "module_icon": string;
        "module_number": string;
        "paragraph_video": string;
        "settings": YduqsModulePlaylists;
        "subtitle_gallery": string;
        "title_gallery": string;
        "title_video": string;
    }
    interface YduqsMotivationalMessages {
    }
    interface YduqsNotification {
        "close": () => Promise<void>;
        "dismissible": boolean;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
        "type": string;
    }
    interface YduqsNotifications {
        "position": string;
    }
    interface YduqsOrderedDndChallenge {
        /**
          * Identificador do Mapa
         */
        "_id": string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
        "gameover": () => Promise<void>;
    }
    interface YduqsOrderedDndTrainning {
        /**
          * Identificador do Mapa
         */
        "_id": string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
    }
    interface YduqsPageGenericLab {
        /**
          * Define se o padrao de cores deve seguir um tema claro (light) ou escuro (dark)
         */
        "bg": 'dark' | 'light';
        /**
          * Define se o container é fluido (ocupa toda a tela) ou não (centralizado, seguindo o Grid definido)
         */
        "fluid": boolean;
    }
    interface YduqsPager {
    }
    interface YduqsPlaylistVideo {
        "changeVideoGallery": (video: any) => Promise<void>;
        "english": boolean;
        "initialize": (config: YduqsModulesPlaylists) => Promise<void>;
        "module_number": number;
        "spanish": boolean;
    }
    interface YduqsPodcast {
        "audio": string;
        "changeColor": (novoValor: any) => Promise<void>;
        "dark": boolean;
        "showtitle": (value: any) => Promise<void>;
        "subtitulo": string;
        "withtitle": boolean;
    }
    interface YduqsProgressBar {
        "displayValue": boolean;
        "hide": () => Promise<void>;
        "isValueVisible": () => Promise<boolean>;
        "max": number;
        "min": number;
        "semirounded": boolean;
        "show": () => Promise<void>;
        "value": number;
    }
    interface YduqsQuestions {
        "colunalg": string;
        "english": boolean;
        "initialize": (config: YduqsQuestionsModel) => Promise<void>;
        "math": boolean;
        "math_advanced": boolean;
        "settings": YduqsQuestionsModel;
        "spanish": boolean;
    }
    interface YduqsQuiz {
        /**
          * Lista opções disponíveis para escolha. Esse campo aceita uma string JSON ou um Objeto JSON { id: number; label: string; value: any; }
         */
        "answers": string | iQuizAnswer[];
        /**
          * Identificador do Quiz
         */
        "dataid": number | string;
        /**
          * Descrição da Pergunta. Esse campo suporta HTML
         */
        "description": string;
        /**
          * Tipo de index das opções: Textual (a, b, c, etc) ou numérico (1, 2, 3, etc)
         */
        "indexType": 'number' | 'letter';
        /**
          * Texto que aparece sobre a Pergunta
         */
        "overline": string;
        /**
          * Texto da Pergunta
         */
        "question": string;
    }
    interface YduqsQuote {
        "dark": boolean;
        "size": string;
    }
    interface YduqsQuoteBody {
    }
    interface YduqsQuoteImage {
        "path": string;
    }
    interface YduqsRange {
        "max": number;
        "min": number;
        "name": string;
        "output": (value: number) => void;
        "step": number;
        "value": number;
    }
    interface YduqsRating {
        "cta": string;
        "icon": string;
        "module": string;
        "tamanho": string;
    }
    interface YduqsScore {
        /**
          * Identificador do Quiz
         */
        "dataid": number | string;
        /**
          * Texto de subtítulo
         */
        "datasubtitle": string;
        /**
          * Título do componente
         */
        "datatitle": string;
        /**
          * Lista de itens
         */
        "items": iScoreItem[] | string;
    }
    interface YduqsSearchBar {
    }
    interface YduqsShowPoints {
        /**
          * Identificador do Mapa
         */
        "_id": string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
    }
    interface YduqsTab {
        "disabled": boolean;
        "header": string;
        "open": boolean;
        "outline": string;
        "type": string;
    }
    interface YduqsTabs {
        "currentTab": () => Promise<number>;
        "darkmode": boolean;
        "fixed_titles": boolean;
        "gtm_action": Array<String>;
        "gtm_category": Array<String>;
        "gtm_label": Array<String>;
        "icons": Array<String>;
        "openTab": (tabIndex: number) => Promise<void>;
        "outlined": boolean;
    }
    interface YduqsTag {
        "color": string;
    }
    interface YduqsTags {
    }
    interface YduqsTeoria {
    }
    interface YduqsTextarea {
        "bgfeedbackdark": boolean;
        "colunaslg": number;
        "colunasmd": number;
        "hidden_feedback": boolean;
        "idbtn": string;
        "idtxt": string;
        "ligthtxtarea": boolean;
        "outlinetxtarea": boolean;
        "placeholder": string;
        "withbtn": boolean;
    }
    interface YduqsTimeline {
        "dark": boolean;
        "horizontal": boolean;
    }
    interface YduqsTimelineItem {
        "icon": string;
        "last": boolean;
    }
    interface YduqsTitle {
        "dark": boolean;
        "topic_icon": string;
        "topic_title": string;
    }
    interface YduqsToast {
        "delay"?: number;
        "icon": string;
        "message": string;
        "open": boolean;
        "tit"?: string;
        "usematerial"?: boolean;
    }
    interface YduqsToggle {
        "disable": boolean;
        "open": boolean;
        "teste": String;
    }
    interface YduqsVideoPlayer {
        "bgcolor": string;
        "covered": boolean;
        "height": string;
        "src": string;
        "transparent": boolean;
        "videoId": string;
        "width": string;
    }
    interface YduqsVirtualMap {
        /**
          * Identificador do Mapa
         */
        "_id": string;
        "centralize": () => Promise<void>;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
        /**
          * Número do item que será marcado como ponto atual.
         */
        "selected"?: number;
    }
    interface YduqsZoomChallenge {
        /**
          * Identificador do Mapa
         */
        "_id": string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
        /**
          * Finaliza a Atividade
         */
        "gameover": () => Promise<void>;
    }
    interface YduqsZoomFullScreen {
        "alt": string;
        "max": number;
        "min": number;
        "src": string;
        "step": number;
    }
}
export interface MyStaceCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyStaceElement;
}
export interface StaceEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStaceEditorElement;
}
export interface YduqsAccordionPaneCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsAccordionPaneElement;
}
export interface YduqsAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsAlertElement;
}
export interface YduqsAudioPlayerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsAudioPlayerElement;
}
export interface YduqsCardModuloCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCardModuloElement;
}
export interface YduqsCardSelecionavelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCardSelecionavelElement;
}
export interface YduqsCardSelecionavelItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCardSelecionavelItemElement;
}
export interface YduqsCarouselCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCarouselElement;
}
export interface YduqsCollapseCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCollapseElement;
}
export interface YduqsCollapseContentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCollapseContentElement;
}
export interface YduqsCollapseTeoriaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCollapseTeoriaElement;
}
export interface YduqsCollapseTeoriaContentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCollapseTeoriaContentElement;
}
export interface YduqsConfirmCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsConfirmElement;
}
export interface YduqsCountdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCountdownElement;
}
export interface YduqsCoverLabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCoverLabElement;
}
export interface YduqsCoverStageLabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsCoverStageLabElement;
}
export interface YduqsHeaderLabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsHeaderLabElement;
}
export interface YduqsInfoCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsInfoElement;
}
export interface YduqsLabPhaseCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsLabPhaseElement;
}
export interface YduqsLabQuestionsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsLabQuestionsElement;
}
export interface YduqsLoadingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsLoadingElement;
}
export interface YduqsMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsMenuElement;
}
export interface YduqsModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsModalElement;
}
export interface YduqsNotificationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsNotificationElement;
}
export interface YduqsOrderedDndChallengeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsOrderedDndChallengeElement;
}
export interface YduqsOrderedDndTrainningCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsOrderedDndTrainningElement;
}
export interface YduqsProgressBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsProgressBarElement;
}
export interface YduqsQuizCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsQuizElement;
}
export interface YduqsTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsTabsElement;
}
export interface YduqsToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsToastElement;
}
export interface YduqsToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsToggleElement;
}
export interface YduqsVirtualMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsVirtualMapElement;
}
export interface YduqsZoomChallengeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYduqsZoomChallengeElement;
}
declare global {
    interface HTMLMyStaceElement extends Components.MyStace, HTMLStencilElement {
    }
    var HTMLMyStaceElement: {
        prototype: HTMLMyStaceElement;
        new (): HTMLMyStaceElement;
    };
    interface HTMLStaceEditorElement extends Components.StaceEditor, HTMLStencilElement {
    }
    var HTMLStaceEditorElement: {
        prototype: HTMLStaceEditorElement;
        new (): HTMLStaceEditorElement;
    };
    interface HTMLYduqsAccordionElement extends Components.YduqsAccordion, HTMLStencilElement {
    }
    var HTMLYduqsAccordionElement: {
        prototype: HTMLYduqsAccordionElement;
        new (): HTMLYduqsAccordionElement;
    };
    interface HTMLYduqsAccordionPaneElement extends Components.YduqsAccordionPane, HTMLStencilElement {
    }
    var HTMLYduqsAccordionPaneElement: {
        prototype: HTMLYduqsAccordionPaneElement;
        new (): HTMLYduqsAccordionPaneElement;
    };
    interface HTMLYduqsAlertElement extends Components.YduqsAlert, HTMLStencilElement {
    }
    var HTMLYduqsAlertElement: {
        prototype: HTMLYduqsAlertElement;
        new (): HTMLYduqsAlertElement;
    };
    interface HTMLYduqsAtividadeDiscursivaElement extends Components.YduqsAtividadeDiscursiva, HTMLStencilElement {
    }
    var HTMLYduqsAtividadeDiscursivaElement: {
        prototype: HTMLYduqsAtividadeDiscursivaElement;
        new (): HTMLYduqsAtividadeDiscursivaElement;
    };
    interface HTMLYduqsAudioCardElement extends Components.YduqsAudioCard, HTMLStencilElement {
    }
    var HTMLYduqsAudioCardElement: {
        prototype: HTMLYduqsAudioCardElement;
        new (): HTMLYduqsAudioCardElement;
    };
    interface HTMLYduqsAudioPlayerElement extends Components.YduqsAudioPlayer, HTMLStencilElement {
    }
    var HTMLYduqsAudioPlayerElement: {
        prototype: HTMLYduqsAudioPlayerElement;
        new (): HTMLYduqsAudioPlayerElement;
    };
    interface HTMLYduqsBeforeAfterElement extends Components.YduqsBeforeAfter, HTMLStencilElement {
    }
    var HTMLYduqsBeforeAfterElement: {
        prototype: HTMLYduqsBeforeAfterElement;
        new (): HTMLYduqsBeforeAfterElement;
    };
    interface HTMLYduqsCaixaFormulaElement extends Components.YduqsCaixaFormula, HTMLStencilElement {
    }
    var HTMLYduqsCaixaFormulaElement: {
        prototype: HTMLYduqsCaixaFormulaElement;
        new (): HTMLYduqsCaixaFormulaElement;
    };
    interface HTMLYduqsCardElement extends Components.YduqsCard, HTMLStencilElement {
    }
    var HTMLYduqsCardElement: {
        prototype: HTMLYduqsCardElement;
        new (): HTMLYduqsCardElement;
    };
    interface HTMLYduqsCardBodyElement extends Components.YduqsCardBody, HTMLStencilElement {
    }
    var HTMLYduqsCardBodyElement: {
        prototype: HTMLYduqsCardBodyElement;
        new (): HTMLYduqsCardBodyElement;
    };
    interface HTMLYduqsCardComparativoElement extends Components.YduqsCardComparativo, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoElement: {
        prototype: HTMLYduqsCardComparativoElement;
        new (): HTMLYduqsCardComparativoElement;
    };
    interface HTMLYduqsCardComparativoBodyElement extends Components.YduqsCardComparativoBody, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoBodyElement: {
        prototype: HTMLYduqsCardComparativoBodyElement;
        new (): HTMLYduqsCardComparativoBodyElement;
    };
    interface HTMLYduqsCardComparativoHeaderElement extends Components.YduqsCardComparativoHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoHeaderElement: {
        prototype: HTMLYduqsCardComparativoHeaderElement;
        new (): HTMLYduqsCardComparativoHeaderElement;
    };
    interface HTMLYduqsCardComparativoItemElement extends Components.YduqsCardComparativoItem, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoItemElement: {
        prototype: HTMLYduqsCardComparativoItemElement;
        new (): HTMLYduqsCardComparativoItemElement;
    };
    interface HTMLYduqsCardDestaqueElement extends Components.YduqsCardDestaque, HTMLStencilElement {
    }
    var HTMLYduqsCardDestaqueElement: {
        prototype: HTMLYduqsCardDestaqueElement;
        new (): HTMLYduqsCardDestaqueElement;
    };
    interface HTMLYduqsCardDestaqueBodyElement extends Components.YduqsCardDestaqueBody, HTMLStencilElement {
    }
    var HTMLYduqsCardDestaqueBodyElement: {
        prototype: HTMLYduqsCardDestaqueBodyElement;
        new (): HTMLYduqsCardDestaqueBodyElement;
    };
    interface HTMLYduqsCardDestaqueHeaderElement extends Components.YduqsCardDestaqueHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardDestaqueHeaderElement: {
        prototype: HTMLYduqsCardDestaqueHeaderElement;
        new (): HTMLYduqsCardDestaqueHeaderElement;
    };
    interface HTMLYduqsCardFooterElement extends Components.YduqsCardFooter, HTMLStencilElement {
    }
    var HTMLYduqsCardFooterElement: {
        prototype: HTMLYduqsCardFooterElement;
        new (): HTMLYduqsCardFooterElement;
    };
    interface HTMLYduqsCardHeaderElement extends Components.YduqsCardHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardHeaderElement: {
        prototype: HTMLYduqsCardHeaderElement;
        new (): HTMLYduqsCardHeaderElement;
    };
    interface HTMLYduqsCardHorizontalElement extends Components.YduqsCardHorizontal, HTMLStencilElement {
    }
    var HTMLYduqsCardHorizontalElement: {
        prototype: HTMLYduqsCardHorizontalElement;
        new (): HTMLYduqsCardHorizontalElement;
    };
    interface HTMLYduqsCardIntroElement extends Components.YduqsCardIntro, HTMLStencilElement {
    }
    var HTMLYduqsCardIntroElement: {
        prototype: HTMLYduqsCardIntroElement;
        new (): HTMLYduqsCardIntroElement;
    };
    interface HTMLYduqsCardModuloElement extends Components.YduqsCardModulo, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloElement: {
        prototype: HTMLYduqsCardModuloElement;
        new (): HTMLYduqsCardModuloElement;
    };
    interface HTMLYduqsCardModuloBodyElement extends Components.YduqsCardModuloBody, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloBodyElement: {
        prototype: HTMLYduqsCardModuloBodyElement;
        new (): HTMLYduqsCardModuloBodyElement;
    };
    interface HTMLYduqsCardModuloFooterElement extends Components.YduqsCardModuloFooter, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloFooterElement: {
        prototype: HTMLYduqsCardModuloFooterElement;
        new (): HTMLYduqsCardModuloFooterElement;
    };
    interface HTMLYduqsCardModuloHeaderElement extends Components.YduqsCardModuloHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloHeaderElement: {
        prototype: HTMLYduqsCardModuloHeaderElement;
        new (): HTMLYduqsCardModuloHeaderElement;
    };
    interface HTMLYduqsCardSelecionavelElement extends Components.YduqsCardSelecionavel, HTMLStencilElement {
    }
    var HTMLYduqsCardSelecionavelElement: {
        prototype: HTMLYduqsCardSelecionavelElement;
        new (): HTMLYduqsCardSelecionavelElement;
    };
    interface HTMLYduqsCardSelecionavelItemElement extends Components.YduqsCardSelecionavelItem, HTMLStencilElement {
    }
    var HTMLYduqsCardSelecionavelItemElement: {
        prototype: HTMLYduqsCardSelecionavelItemElement;
        new (): HTMLYduqsCardSelecionavelItemElement;
    };
    interface HTMLYduqsCardVideoElement extends Components.YduqsCardVideo, HTMLStencilElement {
    }
    var HTMLYduqsCardVideoElement: {
        prototype: HTMLYduqsCardVideoElement;
        new (): HTMLYduqsCardVideoElement;
    };
    interface HTMLYduqsCarouselElement extends Components.YduqsCarousel, HTMLStencilElement {
    }
    var HTMLYduqsCarouselElement: {
        prototype: HTMLYduqsCarouselElement;
        new (): HTMLYduqsCarouselElement;
    };
    interface HTMLYduqsCarouselItemElement extends Components.YduqsCarouselItem, HTMLStencilElement {
    }
    var HTMLYduqsCarouselItemElement: {
        prototype: HTMLYduqsCarouselItemElement;
        new (): HTMLYduqsCarouselItemElement;
    };
    interface HTMLYduqsCodeCompilerElement extends Components.YduqsCodeCompiler, HTMLStencilElement {
    }
    var HTMLYduqsCodeCompilerElement: {
        prototype: HTMLYduqsCodeCompilerElement;
        new (): HTMLYduqsCodeCompilerElement;
    };
    interface HTMLYduqsCodeSnipetElement extends Components.YduqsCodeSnipet, HTMLStencilElement {
    }
    var HTMLYduqsCodeSnipetElement: {
        prototype: HTMLYduqsCodeSnipetElement;
        new (): HTMLYduqsCodeSnipetElement;
    };
    interface HTMLYduqsCollapseElement extends Components.YduqsCollapse, HTMLStencilElement {
    }
    var HTMLYduqsCollapseElement: {
        prototype: HTMLYduqsCollapseElement;
        new (): HTMLYduqsCollapseElement;
    };
    interface HTMLYduqsCollapseContentElement extends Components.YduqsCollapseContent, HTMLStencilElement {
    }
    var HTMLYduqsCollapseContentElement: {
        prototype: HTMLYduqsCollapseContentElement;
        new (): HTMLYduqsCollapseContentElement;
    };
    interface HTMLYduqsCollapseTeoriaElement extends Components.YduqsCollapseTeoria, HTMLStencilElement {
    }
    var HTMLYduqsCollapseTeoriaElement: {
        prototype: HTMLYduqsCollapseTeoriaElement;
        new (): HTMLYduqsCollapseTeoriaElement;
    };
    interface HTMLYduqsCollapseTeoriaContentElement extends Components.YduqsCollapseTeoriaContent, HTMLStencilElement {
    }
    var HTMLYduqsCollapseTeoriaContentElement: {
        prototype: HTMLYduqsCollapseTeoriaContentElement;
        new (): HTMLYduqsCollapseTeoriaContentElement;
    };
    interface HTMLYduqsConfirmElement extends Components.YduqsConfirm, HTMLStencilElement {
    }
    var HTMLYduqsConfirmElement: {
        prototype: HTMLYduqsConfirmElement;
        new (): HTMLYduqsConfirmElement;
    };
    interface HTMLYduqsCountdownElement extends Components.YduqsCountdown, HTMLStencilElement {
    }
    var HTMLYduqsCountdownElement: {
        prototype: HTMLYduqsCountdownElement;
        new (): HTMLYduqsCountdownElement;
    };
    interface HTMLYduqsCoverElement extends Components.YduqsCover, HTMLStencilElement {
    }
    var HTMLYduqsCoverElement: {
        prototype: HTMLYduqsCoverElement;
        new (): HTMLYduqsCoverElement;
    };
    interface HTMLYduqsCoverLabElement extends Components.YduqsCoverLab, HTMLStencilElement {
    }
    var HTMLYduqsCoverLabElement: {
        prototype: HTMLYduqsCoverLabElement;
        new (): HTMLYduqsCoverLabElement;
    };
    interface HTMLYduqsCoverStageLabElement extends Components.YduqsCoverStageLab, HTMLStencilElement {
    }
    var HTMLYduqsCoverStageLabElement: {
        prototype: HTMLYduqsCoverStageLabElement;
        new (): HTMLYduqsCoverStageLabElement;
    };
    interface HTMLYduqsDestaqueTextoElement extends Components.YduqsDestaqueTexto, HTMLStencilElement {
    }
    var HTMLYduqsDestaqueTextoElement: {
        prototype: HTMLYduqsDestaqueTextoElement;
        new (): HTMLYduqsDestaqueTextoElement;
    };
    interface HTMLYduqsDropdownElement extends Components.YduqsDropdown, HTMLStencilElement {
    }
    var HTMLYduqsDropdownElement: {
        prototype: HTMLYduqsDropdownElement;
        new (): HTMLYduqsDropdownElement;
    };
    interface HTMLYduqsFeedbackThumbElement extends Components.YduqsFeedbackThumb, HTMLStencilElement {
    }
    var HTMLYduqsFeedbackThumbElement: {
        prototype: HTMLYduqsFeedbackThumbElement;
        new (): HTMLYduqsFeedbackThumbElement;
    };
    interface HTMLYduqsFooterElement extends Components.YduqsFooter, HTMLStencilElement {
    }
    var HTMLYduqsFooterElement: {
        prototype: HTMLYduqsFooterElement;
        new (): HTMLYduqsFooterElement;
    };
    interface HTMLYduqsGalleryVideoElement extends Components.YduqsGalleryVideo, HTMLStencilElement {
    }
    var HTMLYduqsGalleryVideoElement: {
        prototype: HTMLYduqsGalleryVideoElement;
        new (): HTMLYduqsGalleryVideoElement;
    };
    interface HTMLYduqsHeaderLabElement extends Components.YduqsHeaderLab, HTMLStencilElement {
    }
    var HTMLYduqsHeaderLabElement: {
        prototype: HTMLYduqsHeaderLabElement;
        new (): HTMLYduqsHeaderLabElement;
    };
    interface HTMLYduqsHelperElement extends Components.YduqsHelper, HTMLStencilElement {
    }
    var HTMLYduqsHelperElement: {
        prototype: HTMLYduqsHelperElement;
        new (): HTMLYduqsHelperElement;
    };
    interface HTMLYduqsImageElement extends Components.YduqsImage, HTMLStencilElement {
    }
    var HTMLYduqsImageElement: {
        prototype: HTMLYduqsImageElement;
        new (): HTMLYduqsImageElement;
    };
    interface HTMLYduqsInfoElement extends Components.YduqsInfo, HTMLStencilElement {
    }
    var HTMLYduqsInfoElement: {
        prototype: HTMLYduqsInfoElement;
        new (): HTMLYduqsInfoElement;
    };
    interface HTMLYduqsInputElement extends Components.YduqsInput, HTMLStencilElement {
    }
    var HTMLYduqsInputElement: {
        prototype: HTMLYduqsInputElement;
        new (): HTMLYduqsInputElement;
    };
    interface HTMLYduqsInteractiveMediaElement extends Components.YduqsInteractiveMedia, HTMLStencilElement {
    }
    var HTMLYduqsInteractiveMediaElement: {
        prototype: HTMLYduqsInteractiveMediaElement;
        new (): HTMLYduqsInteractiveMediaElement;
    };
    interface HTMLYduqsLabErrorElement extends Components.YduqsLabError, HTMLStencilElement {
    }
    var HTMLYduqsLabErrorElement: {
        prototype: HTMLYduqsLabErrorElement;
        new (): HTMLYduqsLabErrorElement;
    };
    interface HTMLYduqsLabIntroElement extends Components.YduqsLabIntro, HTMLStencilElement {
    }
    var HTMLYduqsLabIntroElement: {
        prototype: HTMLYduqsLabIntroElement;
        new (): HTMLYduqsLabIntroElement;
    };
    interface HTMLYduqsLabPhaseElement extends Components.YduqsLabPhase, HTMLStencilElement {
    }
    var HTMLYduqsLabPhaseElement: {
        prototype: HTMLYduqsLabPhaseElement;
        new (): HTMLYduqsLabPhaseElement;
    };
    interface HTMLYduqsLabQuestionsElement extends Components.YduqsLabQuestions, HTMLStencilElement {
    }
    var HTMLYduqsLabQuestionsElement: {
        prototype: HTMLYduqsLabQuestionsElement;
        new (): HTMLYduqsLabQuestionsElement;
    };
    interface HTMLYduqsListasElement extends Components.YduqsListas, HTMLStencilElement {
    }
    var HTMLYduqsListasElement: {
        prototype: HTMLYduqsListasElement;
        new (): HTMLYduqsListasElement;
    };
    interface HTMLYduqsLoaderElement extends Components.YduqsLoader, HTMLStencilElement {
    }
    var HTMLYduqsLoaderElement: {
        prototype: HTMLYduqsLoaderElement;
        new (): HTMLYduqsLoaderElement;
    };
    interface HTMLYduqsLoadingElement extends Components.YduqsLoading, HTMLStencilElement {
    }
    var HTMLYduqsLoadingElement: {
        prototype: HTMLYduqsLoadingElement;
        new (): HTMLYduqsLoadingElement;
    };
    interface HTMLYduqsMenuElement extends Components.YduqsMenu, HTMLStencilElement {
    }
    var HTMLYduqsMenuElement: {
        prototype: HTMLYduqsMenuElement;
        new (): HTMLYduqsMenuElement;
    };
    interface HTMLYduqsModalElement extends Components.YduqsModal, HTMLStencilElement {
    }
    var HTMLYduqsModalElement: {
        prototype: HTMLYduqsModalElement;
        new (): HTMLYduqsModalElement;
    };
    interface HTMLYduqsModuleCoverElement extends Components.YduqsModuleCover, HTMLStencilElement {
    }
    var HTMLYduqsModuleCoverElement: {
        prototype: HTMLYduqsModuleCoverElement;
        new (): HTMLYduqsModuleCoverElement;
    };
    interface HTMLYduqsModuleRatingElement extends Components.YduqsModuleRating, HTMLStencilElement {
    }
    var HTMLYduqsModuleRatingElement: {
        prototype: HTMLYduqsModuleRatingElement;
        new (): HTMLYduqsModuleRatingElement;
    };
    interface HTMLYduqsModuleVideoElement extends Components.YduqsModuleVideo, HTMLStencilElement {
    }
    var HTMLYduqsModuleVideoElement: {
        prototype: HTMLYduqsModuleVideoElement;
        new (): HTMLYduqsModuleVideoElement;
    };
    interface HTMLYduqsMotivationalMessagesElement extends Components.YduqsMotivationalMessages, HTMLStencilElement {
    }
    var HTMLYduqsMotivationalMessagesElement: {
        prototype: HTMLYduqsMotivationalMessagesElement;
        new (): HTMLYduqsMotivationalMessagesElement;
    };
    interface HTMLYduqsNotificationElement extends Components.YduqsNotification, HTMLStencilElement {
    }
    var HTMLYduqsNotificationElement: {
        prototype: HTMLYduqsNotificationElement;
        new (): HTMLYduqsNotificationElement;
    };
    interface HTMLYduqsNotificationsElement extends Components.YduqsNotifications, HTMLStencilElement {
    }
    var HTMLYduqsNotificationsElement: {
        prototype: HTMLYduqsNotificationsElement;
        new (): HTMLYduqsNotificationsElement;
    };
    interface HTMLYduqsOrderedDndChallengeElement extends Components.YduqsOrderedDndChallenge, HTMLStencilElement {
    }
    var HTMLYduqsOrderedDndChallengeElement: {
        prototype: HTMLYduqsOrderedDndChallengeElement;
        new (): HTMLYduqsOrderedDndChallengeElement;
    };
    interface HTMLYduqsOrderedDndTrainningElement extends Components.YduqsOrderedDndTrainning, HTMLStencilElement {
    }
    var HTMLYduqsOrderedDndTrainningElement: {
        prototype: HTMLYduqsOrderedDndTrainningElement;
        new (): HTMLYduqsOrderedDndTrainningElement;
    };
    interface HTMLYduqsPageGenericLabElement extends Components.YduqsPageGenericLab, HTMLStencilElement {
    }
    var HTMLYduqsPageGenericLabElement: {
        prototype: HTMLYduqsPageGenericLabElement;
        new (): HTMLYduqsPageGenericLabElement;
    };
    interface HTMLYduqsPagerElement extends Components.YduqsPager, HTMLStencilElement {
    }
    var HTMLYduqsPagerElement: {
        prototype: HTMLYduqsPagerElement;
        new (): HTMLYduqsPagerElement;
    };
    interface HTMLYduqsPlaylistVideoElement extends Components.YduqsPlaylistVideo, HTMLStencilElement {
    }
    var HTMLYduqsPlaylistVideoElement: {
        prototype: HTMLYduqsPlaylistVideoElement;
        new (): HTMLYduqsPlaylistVideoElement;
    };
    interface HTMLYduqsPodcastElement extends Components.YduqsPodcast, HTMLStencilElement {
    }
    var HTMLYduqsPodcastElement: {
        prototype: HTMLYduqsPodcastElement;
        new (): HTMLYduqsPodcastElement;
    };
    interface HTMLYduqsProgressBarElement extends Components.YduqsProgressBar, HTMLStencilElement {
    }
    var HTMLYduqsProgressBarElement: {
        prototype: HTMLYduqsProgressBarElement;
        new (): HTMLYduqsProgressBarElement;
    };
    interface HTMLYduqsQuestionsElement extends Components.YduqsQuestions, HTMLStencilElement {
    }
    var HTMLYduqsQuestionsElement: {
        prototype: HTMLYduqsQuestionsElement;
        new (): HTMLYduqsQuestionsElement;
    };
    interface HTMLYduqsQuizElement extends Components.YduqsQuiz, HTMLStencilElement {
    }
    var HTMLYduqsQuizElement: {
        prototype: HTMLYduqsQuizElement;
        new (): HTMLYduqsQuizElement;
    };
    interface HTMLYduqsQuoteElement extends Components.YduqsQuote, HTMLStencilElement {
    }
    var HTMLYduqsQuoteElement: {
        prototype: HTMLYduqsQuoteElement;
        new (): HTMLYduqsQuoteElement;
    };
    interface HTMLYduqsQuoteBodyElement extends Components.YduqsQuoteBody, HTMLStencilElement {
    }
    var HTMLYduqsQuoteBodyElement: {
        prototype: HTMLYduqsQuoteBodyElement;
        new (): HTMLYduqsQuoteBodyElement;
    };
    interface HTMLYduqsQuoteImageElement extends Components.YduqsQuoteImage, HTMLStencilElement {
    }
    var HTMLYduqsQuoteImageElement: {
        prototype: HTMLYduqsQuoteImageElement;
        new (): HTMLYduqsQuoteImageElement;
    };
    interface HTMLYduqsRangeElement extends Components.YduqsRange, HTMLStencilElement {
    }
    var HTMLYduqsRangeElement: {
        prototype: HTMLYduqsRangeElement;
        new (): HTMLYduqsRangeElement;
    };
    interface HTMLYduqsRatingElement extends Components.YduqsRating, HTMLStencilElement {
    }
    var HTMLYduqsRatingElement: {
        prototype: HTMLYduqsRatingElement;
        new (): HTMLYduqsRatingElement;
    };
    interface HTMLYduqsScoreElement extends Components.YduqsScore, HTMLStencilElement {
    }
    var HTMLYduqsScoreElement: {
        prototype: HTMLYduqsScoreElement;
        new (): HTMLYduqsScoreElement;
    };
    interface HTMLYduqsSearchBarElement extends Components.YduqsSearchBar, HTMLStencilElement {
    }
    var HTMLYduqsSearchBarElement: {
        prototype: HTMLYduqsSearchBarElement;
        new (): HTMLYduqsSearchBarElement;
    };
    interface HTMLYduqsShowPointsElement extends Components.YduqsShowPoints, HTMLStencilElement {
    }
    var HTMLYduqsShowPointsElement: {
        prototype: HTMLYduqsShowPointsElement;
        new (): HTMLYduqsShowPointsElement;
    };
    interface HTMLYduqsTabElement extends Components.YduqsTab, HTMLStencilElement {
    }
    var HTMLYduqsTabElement: {
        prototype: HTMLYduqsTabElement;
        new (): HTMLYduqsTabElement;
    };
    interface HTMLYduqsTabsElement extends Components.YduqsTabs, HTMLStencilElement {
    }
    var HTMLYduqsTabsElement: {
        prototype: HTMLYduqsTabsElement;
        new (): HTMLYduqsTabsElement;
    };
    interface HTMLYduqsTagElement extends Components.YduqsTag, HTMLStencilElement {
    }
    var HTMLYduqsTagElement: {
        prototype: HTMLYduqsTagElement;
        new (): HTMLYduqsTagElement;
    };
    interface HTMLYduqsTagsElement extends Components.YduqsTags, HTMLStencilElement {
    }
    var HTMLYduqsTagsElement: {
        prototype: HTMLYduqsTagsElement;
        new (): HTMLYduqsTagsElement;
    };
    interface HTMLYduqsTeoriaElement extends Components.YduqsTeoria, HTMLStencilElement {
    }
    var HTMLYduqsTeoriaElement: {
        prototype: HTMLYduqsTeoriaElement;
        new (): HTMLYduqsTeoriaElement;
    };
    interface HTMLYduqsTextareaElement extends Components.YduqsTextarea, HTMLStencilElement {
    }
    var HTMLYduqsTextareaElement: {
        prototype: HTMLYduqsTextareaElement;
        new (): HTMLYduqsTextareaElement;
    };
    interface HTMLYduqsTimelineElement extends Components.YduqsTimeline, HTMLStencilElement {
    }
    var HTMLYduqsTimelineElement: {
        prototype: HTMLYduqsTimelineElement;
        new (): HTMLYduqsTimelineElement;
    };
    interface HTMLYduqsTimelineItemElement extends Components.YduqsTimelineItem, HTMLStencilElement {
    }
    var HTMLYduqsTimelineItemElement: {
        prototype: HTMLYduqsTimelineItemElement;
        new (): HTMLYduqsTimelineItemElement;
    };
    interface HTMLYduqsTitleElement extends Components.YduqsTitle, HTMLStencilElement {
    }
    var HTMLYduqsTitleElement: {
        prototype: HTMLYduqsTitleElement;
        new (): HTMLYduqsTitleElement;
    };
    interface HTMLYduqsToastElement extends Components.YduqsToast, HTMLStencilElement {
    }
    var HTMLYduqsToastElement: {
        prototype: HTMLYduqsToastElement;
        new (): HTMLYduqsToastElement;
    };
    interface HTMLYduqsToggleElement extends Components.YduqsToggle, HTMLStencilElement {
    }
    var HTMLYduqsToggleElement: {
        prototype: HTMLYduqsToggleElement;
        new (): HTMLYduqsToggleElement;
    };
    interface HTMLYduqsVideoPlayerElement extends Components.YduqsVideoPlayer, HTMLStencilElement {
    }
    var HTMLYduqsVideoPlayerElement: {
        prototype: HTMLYduqsVideoPlayerElement;
        new (): HTMLYduqsVideoPlayerElement;
    };
    interface HTMLYduqsVirtualMapElement extends Components.YduqsVirtualMap, HTMLStencilElement {
    }
    var HTMLYduqsVirtualMapElement: {
        prototype: HTMLYduqsVirtualMapElement;
        new (): HTMLYduqsVirtualMapElement;
    };
    interface HTMLYduqsZoomChallengeElement extends Components.YduqsZoomChallenge, HTMLStencilElement {
    }
    var HTMLYduqsZoomChallengeElement: {
        prototype: HTMLYduqsZoomChallengeElement;
        new (): HTMLYduqsZoomChallengeElement;
    };
    interface HTMLYduqsZoomFullScreenElement extends Components.YduqsZoomFullScreen, HTMLStencilElement {
    }
    var HTMLYduqsZoomFullScreenElement: {
        prototype: HTMLYduqsZoomFullScreenElement;
        new (): HTMLYduqsZoomFullScreenElement;
    };
    interface HTMLElementTagNameMap {
        "my-stace": HTMLMyStaceElement;
        "stace-editor": HTMLStaceEditorElement;
        "yduqs-accordion": HTMLYduqsAccordionElement;
        "yduqs-accordion-pane": HTMLYduqsAccordionPaneElement;
        "yduqs-alert": HTMLYduqsAlertElement;
        "yduqs-atividade-discursiva": HTMLYduqsAtividadeDiscursivaElement;
        "yduqs-audio-card": HTMLYduqsAudioCardElement;
        "yduqs-audio-player": HTMLYduqsAudioPlayerElement;
        "yduqs-before-after": HTMLYduqsBeforeAfterElement;
        "yduqs-caixa-formula": HTMLYduqsCaixaFormulaElement;
        "yduqs-card": HTMLYduqsCardElement;
        "yduqs-card-body": HTMLYduqsCardBodyElement;
        "yduqs-card-comparativo": HTMLYduqsCardComparativoElement;
        "yduqs-card-comparativo-body": HTMLYduqsCardComparativoBodyElement;
        "yduqs-card-comparativo-header": HTMLYduqsCardComparativoHeaderElement;
        "yduqs-card-comparativo-item": HTMLYduqsCardComparativoItemElement;
        "yduqs-card-destaque": HTMLYduqsCardDestaqueElement;
        "yduqs-card-destaque-body": HTMLYduqsCardDestaqueBodyElement;
        "yduqs-card-destaque-header": HTMLYduqsCardDestaqueHeaderElement;
        "yduqs-card-footer": HTMLYduqsCardFooterElement;
        "yduqs-card-header": HTMLYduqsCardHeaderElement;
        "yduqs-card-horizontal": HTMLYduqsCardHorizontalElement;
        "yduqs-card-intro": HTMLYduqsCardIntroElement;
        "yduqs-card-modulo": HTMLYduqsCardModuloElement;
        "yduqs-card-modulo-body": HTMLYduqsCardModuloBodyElement;
        "yduqs-card-modulo-footer": HTMLYduqsCardModuloFooterElement;
        "yduqs-card-modulo-header": HTMLYduqsCardModuloHeaderElement;
        "yduqs-card-selecionavel": HTMLYduqsCardSelecionavelElement;
        "yduqs-card-selecionavel-item": HTMLYduqsCardSelecionavelItemElement;
        "yduqs-card-video": HTMLYduqsCardVideoElement;
        "yduqs-carousel": HTMLYduqsCarouselElement;
        "yduqs-carousel-item": HTMLYduqsCarouselItemElement;
        "yduqs-code-compiler": HTMLYduqsCodeCompilerElement;
        "yduqs-code-snipet": HTMLYduqsCodeSnipetElement;
        "yduqs-collapse": HTMLYduqsCollapseElement;
        "yduqs-collapse-content": HTMLYduqsCollapseContentElement;
        "yduqs-collapse-teoria": HTMLYduqsCollapseTeoriaElement;
        "yduqs-collapse-teoria-content": HTMLYduqsCollapseTeoriaContentElement;
        "yduqs-confirm": HTMLYduqsConfirmElement;
        "yduqs-countdown": HTMLYduqsCountdownElement;
        "yduqs-cover": HTMLYduqsCoverElement;
        "yduqs-cover-lab": HTMLYduqsCoverLabElement;
        "yduqs-cover-stage-lab": HTMLYduqsCoverStageLabElement;
        "yduqs-destaque-texto": HTMLYduqsDestaqueTextoElement;
        "yduqs-dropdown": HTMLYduqsDropdownElement;
        "yduqs-feedback-thumb": HTMLYduqsFeedbackThumbElement;
        "yduqs-footer": HTMLYduqsFooterElement;
        "yduqs-gallery-video": HTMLYduqsGalleryVideoElement;
        "yduqs-header-lab": HTMLYduqsHeaderLabElement;
        "yduqs-helper": HTMLYduqsHelperElement;
        "yduqs-image": HTMLYduqsImageElement;
        "yduqs-info": HTMLYduqsInfoElement;
        "yduqs-input": HTMLYduqsInputElement;
        "yduqs-interactive-media": HTMLYduqsInteractiveMediaElement;
        "yduqs-lab-error": HTMLYduqsLabErrorElement;
        "yduqs-lab-intro": HTMLYduqsLabIntroElement;
        "yduqs-lab-phase": HTMLYduqsLabPhaseElement;
        "yduqs-lab-questions": HTMLYduqsLabQuestionsElement;
        "yduqs-listas": HTMLYduqsListasElement;
        "yduqs-loader": HTMLYduqsLoaderElement;
        "yduqs-loading": HTMLYduqsLoadingElement;
        "yduqs-menu": HTMLYduqsMenuElement;
        "yduqs-modal": HTMLYduqsModalElement;
        "yduqs-module-cover": HTMLYduqsModuleCoverElement;
        "yduqs-module-rating": HTMLYduqsModuleRatingElement;
        "yduqs-module-video": HTMLYduqsModuleVideoElement;
        "yduqs-motivational-messages": HTMLYduqsMotivationalMessagesElement;
        "yduqs-notification": HTMLYduqsNotificationElement;
        "yduqs-notifications": HTMLYduqsNotificationsElement;
        "yduqs-ordered-dnd-challenge": HTMLYduqsOrderedDndChallengeElement;
        "yduqs-ordered-dnd-trainning": HTMLYduqsOrderedDndTrainningElement;
        "yduqs-page-generic-lab": HTMLYduqsPageGenericLabElement;
        "yduqs-pager": HTMLYduqsPagerElement;
        "yduqs-playlist-video": HTMLYduqsPlaylistVideoElement;
        "yduqs-podcast": HTMLYduqsPodcastElement;
        "yduqs-progress-bar": HTMLYduqsProgressBarElement;
        "yduqs-questions": HTMLYduqsQuestionsElement;
        "yduqs-quiz": HTMLYduqsQuizElement;
        "yduqs-quote": HTMLYduqsQuoteElement;
        "yduqs-quote-body": HTMLYduqsQuoteBodyElement;
        "yduqs-quote-image": HTMLYduqsQuoteImageElement;
        "yduqs-range": HTMLYduqsRangeElement;
        "yduqs-rating": HTMLYduqsRatingElement;
        "yduqs-score": HTMLYduqsScoreElement;
        "yduqs-search-bar": HTMLYduqsSearchBarElement;
        "yduqs-show-points": HTMLYduqsShowPointsElement;
        "yduqs-tab": HTMLYduqsTabElement;
        "yduqs-tabs": HTMLYduqsTabsElement;
        "yduqs-tag": HTMLYduqsTagElement;
        "yduqs-tags": HTMLYduqsTagsElement;
        "yduqs-teoria": HTMLYduqsTeoriaElement;
        "yduqs-textarea": HTMLYduqsTextareaElement;
        "yduqs-timeline": HTMLYduqsTimelineElement;
        "yduqs-timeline-item": HTMLYduqsTimelineItemElement;
        "yduqs-title": HTMLYduqsTitleElement;
        "yduqs-toast": HTMLYduqsToastElement;
        "yduqs-toggle": HTMLYduqsToggleElement;
        "yduqs-video-player": HTMLYduqsVideoPlayerElement;
        "yduqs-virtual-map": HTMLYduqsVirtualMapElement;
        "yduqs-zoom-challenge": HTMLYduqsZoomChallengeElement;
        "yduqs-zoom-full-screen": HTMLYduqsZoomFullScreenElement;
    }
}
declare namespace LocalJSX {
    interface MyStace {
        "autoUpdateContent"?: boolean;
        "durationBeforeCallback"?: number;
        "mode"?: string;
        "onChangeText"?: (event: MyStaceCustomEvent<any>) => void;
        "options"?: any;
        "readOnly"?: boolean;
        "text"?: string;
        "theme"?: string;
        "timeoutSaving"?: any;
    }
    interface StaceEditor {
        "autoUpdateContent"?: boolean;
        "durationBeforeCallback"?: number;
        "mode"?: string;
        "onTextChange"?: (event: StaceEditorCustomEvent<any>) => void;
        "options"?: any;
        "readOnly"?: boolean;
        "text"?: string;
        "theme"?: string;
        "timeoutSaving"?: any;
    }
    interface YduqsAccordion {
        "outline"?: boolean;
    }
    interface YduqsAccordionPane {
        "onOnClickCollapse"?: (event: YduqsAccordionPaneCustomEvent<any>) => void;
        "onTogglepane"?: (event: YduqsAccordionPaneCustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface YduqsAlert {
        "_title"?: string;
        "btntext"?: string;
        "icon"?: string;
        "message"?: string;
        "onAlertClick"?: (event: YduqsAlertCustomEvent<boolean>) => void;
        "onAlertClosed"?: (event: YduqsAlertCustomEvent<boolean>) => void;
        "open"?: boolean;
        "subtitle"?: string;
        "usematerial"?: boolean;
    }
    interface YduqsAtividadeDiscursiva {
    }
    interface YduqsAudioCard {
        "audiocard_id"?: string;
        "dark"?: boolean;
        "equal_height"?: boolean;
        "group"?: boolean;
        "outlined"?: boolean;
        "src"?: string;
        "subtitle_audio_card"?: string;
        "title_audio_card"?: string;
    }
    interface YduqsAudioPlayer {
        "audio_id"?: string;
        "dark"?: boolean;
        "onUpdateRate"?: (event: YduqsAudioPlayerCustomEvent<number>) => void;
        "rate"?: number;
        "settings"?: YduqsAudioPlayerModel;
        "shortdisplay"?: boolean;
        "src"?: string;
    }
    interface YduqsBeforeAfter {
        "after_img"?: string;
        "after_img_alt"?: string;
        "after_img_title"?: string;
        "before_img"?: string;
        "before_img_alt"?: string;
        "before_img_title"?: string;
        "caption"?: string;
    }
    interface YduqsCaixaFormula {
        "dark"?: boolean;
        "equal_height"?: boolean;
        "formula"?: string;
        "rotate_info"?: boolean;
        "title_formula"?: string;
    }
    interface YduqsCard {
        "dark"?: boolean;
        "equal_height"?: boolean;
        "outlined"?: boolean;
        "small"?: boolean;
    }
    interface YduqsCardBody {
    }
    interface YduqsCardComparativo {
        "dark"?: boolean;
        "icon"?: string;
        "outline"?: boolean;
        "rotate_mobile"?: boolean;
    }
    interface YduqsCardComparativoBody {
    }
    interface YduqsCardComparativoHeader {
    }
    interface YduqsCardComparativoItem {
    }
    interface YduqsCardDestaque {
        "grade"?: number;
        "icon"?: string;
        "outline"?: boolean;
    }
    interface YduqsCardDestaqueBody {
    }
    interface YduqsCardDestaqueHeader {
    }
    interface YduqsCardFooter {
    }
    interface YduqsCardHeader {
    }
    interface YduqsCardHorizontal {
        "card_icon"?: string;
        "card_image"?: string;
        "english"?: boolean;
        "image_alt"?: string;
        "image_title"?: string;
        "isquestion"?: boolean;
        "spanish"?: boolean;
    }
    interface YduqsCardIntro {
        "text"?: string;
    }
    interface YduqsCardModulo {
        "onChanged"?: (event: YduqsCardModuloCustomEvent<any>) => void;
        "progress"?: number;
    }
    interface YduqsCardModuloBody {
    }
    interface YduqsCardModuloFooter {
    }
    interface YduqsCardModuloHeader {
    }
    interface YduqsCardSelecionavel {
        "onSelected"?: (event: YduqsCardSelecionavelCustomEvent<any>) => void;
    }
    interface YduqsCardSelecionavelItem {
        "disabled"?: boolean;
        "onOnselect"?: (event: YduqsCardSelecionavelItemCustomEvent<any>) => void;
        "optionid"?: string;
        "selected"?: boolean;
    }
    interface YduqsCardVideo {
        "active"?: boolean;
        "border_bottom"?: boolean;
        "id_video"?: string;
        "link_video"?: string;
        "module_video"?: string;
        "paragraph"?: string;
        "subtitle_video"?: string;
        "thumb_video"?: string;
        "time"?: string;
        "title_video"?: string;
        "type_video"?: string;
    }
    interface YduqsCarousel {
        "english"?: boolean;
        "onNextslide"?: (event: YduqsCarouselCustomEvent<any>) => void;
        "onPrevslide"?: (event: YduqsCarouselCustomEvent<any>) => void;
        "onUpdatepage"?: (event: YduqsCarouselCustomEvent<any>) => void;
        "space"?: number;
        "spanish"?: boolean;
    }
    interface YduqsCarouselItem {
    }
    interface YduqsCodeCompiler {
        "code"?: string;
        "dark"?: boolean;
        "exercise_title"?: string;
        "input_keyboard"?: string;
        "language_code"?: string;
    }
    interface YduqsCodeSnipet {
        "code"?: string;
        "dark"?: boolean;
        "input_keyboard"?: string;
        "language_code"?: string;
        "size"?: string;
    }
    interface YduqsCollapse {
        "border"?: boolean;
        "onToggle"?: (event: YduqsCollapseCustomEvent<any>) => void;
        "outline"?: boolean;
    }
    interface YduqsCollapseContent {
        "aling_collapse"?: string;
        "color_collapse"?: string;
        "header"?: string;
        "onTogglepane"?: (event: YduqsCollapseContentCustomEvent<any>) => void;
        "open"?: boolean;
        "size"?: string;
    }
    interface YduqsCollapseTeoria {
        "border"?: boolean;
        "onToggle"?: (event: YduqsCollapseTeoriaCustomEvent<any>) => void;
        "outline"?: boolean;
    }
    interface YduqsCollapseTeoriaContent {
        "header"?: string;
        "onTogglepane"?: (event: YduqsCollapseTeoriaContentCustomEvent<any>) => void;
        "open"?: boolean;
        "size"?: string;
        "teoria"?: boolean;
    }
    interface YduqsConfirm {
        "_title"?: string;
        "btntext"?: string;
        "icon"?: string;
        "message"?: string;
        "onConfirmClick"?: (event: YduqsConfirmCustomEvent<boolean>) => void;
        "onConfirmClosed"?: (event: YduqsConfirmCustomEvent<boolean>) => void;
        "open"?: boolean;
        "subtitle"?: string;
        "usematerial"?: boolean;
    }
    interface YduqsCountdown {
        /**
          * Identificador do Componente
         */
        "_id"?: string;
        /**
          * Evento disparado quando a contagem entra no estado de Perigo
         */
        "onCountdownDanger"?: (event: YduqsCountdownCustomEvent<string>) => void;
        /**
          * Evento disparado quando o contador termina
         */
        "onCountdownFinished"?: (event: YduqsCountdownCustomEvent<string>) => void;
        /**
          * Evento disparado quando a contagem entra no estado de Alerta
         */
        "onCountdownWarning"?: (event: YduqsCountdownCustomEvent<string>) => void;
        /**
          * Quantidade de tempo para a contagem em segundos.
         */
        "time": number;
        /**
          * Marcador da contagem de Alerta, em porcentagem;
         */
        "warningMarker"?: number;
    }
    interface YduqsCover {
        "avatar"?: Array<any>;
        "background_img"?: string;
        "background_img_title"?: string;
        "background_text"?: string;
        "background_text_mobile"?: string;
        "colaboradores_nome"?: Array<any>;
        "collaboration_text"?: string;
        "contributors"?: string;
        "cover_preparation"?: boolean;
        "english"?: boolean;
        "lg_title"?: boolean;
        "link"?: Array<any>;
        "names_clb"?: Array<any>;
        "names_prof"?: Array<any>;
        "professores"?: Array<any>;
        "spanish"?: boolean;
        "teacher"?: string;
        "teacher_avatar"?: string;
        "teacher_link"?: string;
        "template_anitta"?: boolean;
        "template_ibmec"?: boolean;
        "title_cover"?: string;
        "title_size"?: string;
        "xl_title"?: boolean;
    }
    interface YduqsCoverLab {
        "background_img"?: string;
        "loading"?: boolean;
        "onGoToNextPage"?: (event: YduqsCoverLabCustomEvent<string>) => void;
        "subtitle_cover"?: string;
        "title_cover"?: string;
        "to_page_init_lab"?: string;
    }
    interface YduqsCoverStageLab {
        /**
          * Texto de Título da Capa
         */
        "_title"?: string;
        /**
          * Lista de ações (botões) visíveis na Capa
         */
        "actions": any;
        /**
          * Imagem de Fundo da Capa
         */
        "background"?: string;
        /**
          * Texto de Descríção
         */
        "description"?: string;
        /**
          * Evento disparado no click dos botões de Ação
         */
        "onBtnClick"?: (event: YduqsCoverStageLabCustomEvent<any>) => void;
        /**
          * Que aparece Sobre o Titulo. Se omitido, será mostrado o texto 'Fase %phaseNumber%'
         */
        "overtitle"?: string;
        /**
          * Numero da Fase
         */
        "phaseNumber": number;
    }
    interface YduqsDestaqueTexto {
        "size"?: string;
    }
    interface YduqsDropdown {
        "colunas"?: string;
        "identificador"?: string;
        "tipo"?: string;
        "withcheck"?: boolean;
    }
    interface YduqsFeedbackThumb {
        /**
          * Classe CSS adicional
         */
        "_class"?: string;
        /**
          * Informa se a imagem é positiva ou negativa
         */
        "feedback": boolean;
        /**
          * URL da imagem
         */
        "image": string;
    }
    interface YduqsFooter {
        "btnimprimir"?: boolean;
        "english"?: boolean;
        "hide_motivational_messages"?: boolean;
        "hide_pagination"?: boolean;
        "hrefbtnprint"?: string;
        "namebtnimprimir"?: string;
        "spanish"?: boolean;
        "template_anitta"?: boolean;
        "useimage"?: boolean;
    }
    interface YduqsGalleryVideo {
        "english"?: boolean;
        "moduleId"?: string;
        "module_number"?: number;
        "module_number_video"?: number;
        "paragraph_video"?: string;
        "spanish"?: boolean;
        "srcVideo"?: string;
        "subtitle_gallery"?: string;
        "title_gallery"?: string;
        "title_video"?: string;
        "type_video"?: string;
    }
    interface YduqsHeaderLab {
        /**
          * Título do Laboratório
         */
        "_title"?: string;
        /**
          * Esconde o btn de Fullscreen
         */
        "hiddenFullscreen"?: boolean;
        /**
          * Lista de Botões
         */
        "items"?: string | any[];
        "onYduqs-lab-action"?: (event: YduqsHeaderLabCustomEvent<any>) => void;
    }
    interface YduqsHelper {
    }
    interface YduqsImage {
        "alt"?: string;
        "covered"?: boolean;
        "height"?: string;
        "img_title"?: string;
        "src"?: string;
        "width"?: string;
    }
    interface YduqsInfo {
        /**
          * Título da mensagem
         */
        "_title"?: string;
        /**
          * Tempo em milessegundos que a mensagem permanece visível
         */
        "delay"?: number;
        /**
          * Identificador do ícone ou base64 do SVG
         */
        "icon"?: string;
        /**
          * Texto da mensagem
         */
        "message"?: string;
        /**
          * Evento disparado no onClick do icone de fechar ou quando o tempo visível termina
         */
        "onInfoClosed"?: (event: YduqsInfoCustomEvent<boolean>) => void;
        /**
          * Mostra/esconde o componente
         */
        "open"?: boolean;
        /**
          * Subtítulo da mensagem
         */
        "subtitle"?: string;
        /**
          * Informa se o ícone é Material Design ou Base64
         */
        "usematerial"?: boolean;
    }
    interface YduqsInput {
        "icon"?: any;
        "placeh"?: string;
        "titulo"?: string;
    }
    interface YduqsInteractiveMedia {
        /**
          * Url com o endereço do arquivo de configuração
         */
        "config": string;
        /**
          * Icone do cabeçalho
         */
        "headericon"?: string;
        /**
          * Texto descritivo do cabeçalho
         */
        "headertext"?: string;
        /**
          * Título do Cabeçalho
         */
        "headertitle"?: string;
    }
    interface YduqsLabError {
        "errors"?: any[];
        "message"?: string;
    }
    interface YduqsLabIntro {
        /**
          * Título da página, se slot=header não for informado
         */
        "_title"?: string;
        /**
          * Url do Href dos links do cabeçalho e rodapé
         */
        "btnHref"?: string;
        /**
          * Ícone do link do rodapé. Deve ser uma ícone Material.
         */
        "btnIcon"?: string;
        /**
          * Texto dos links do cabeçalho o rodapé.
         */
        "btnText"?: string;
    }
    interface YduqsLabPhase {
        /**
          * Identificador da Próxima Fase. É utilizado no terminos da Atividade de Desafio
         */
        "next": string | number;
        /**
          * Evento disparado sempre que houver navegação no meio de um desafio
         */
        "onGameOverEvent"?: (event: YduqsLabPhaseCustomEvent<any>) => void;
        /**
          * Evento disparado no final dos Desafios
         */
        "onGoToNextPage"?: (event: YduqsLabPhaseCustomEvent<string>) => void;
        /**
          * Identificador da Fase
         */
        "phase": string | number;
    }
    interface YduqsLabQuestions {
        /**
          * Identificador do Mapa
         */
        "_id"?: string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
        /**
          * Evento disparado no Final do Desafio
         */
        "onChallengeEnd"?: (event: YduqsLabQuestionsCustomEvent<any>) => void;
    }
    interface YduqsListas {
        "tamanho"?: string;
        "tipo"?: string;
    }
    interface YduqsLoader {
    }
    interface YduqsLoading {
        "message"?: string;
        "onClose"?: (event: YduqsLoadingCustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface YduqsMenu {
        "english"?: boolean;
        "hide_search"?: boolean;
        "onChangemenudata"?: (event: YduqsMenuCustomEvent<any>) => void;
        "onClickmenuitem"?: (event: YduqsMenuCustomEvent<any>) => void;
        "onOnClickMenuTitle"?: (event: YduqsMenuCustomEvent<any>) => void;
        "position"?: number;
        "settings"?: YduqsMenuModel;
        "spanish"?: boolean;
    }
    interface YduqsModal {
        "_title"?: string;
        "isopen"?: boolean;
        "maxbodyheight"?: number;
        "onModalClosed"?: (event: YduqsModalCustomEvent<boolean>) => void;
        "size"?: string;
        "variant"?: string;
    }
    interface YduqsModuleCover {
        "img_cover"?: string;
        "midia_time"?: string;
        "number_module"?: string;
        "objective"?: string;
        "read_time"?: string;
        "title_midia_time"?: string;
        "title_module"?: string;
        "title_read_time"?: string;
    }
    interface YduqsModuleRating {
        "cta"?: string;
        "english"?: boolean;
        "icon"?: string;
        "module"?: string;
        "spanish"?: boolean;
        "tamanho"?: string;
    }
    interface YduqsModuleVideo {
        "active_video"?: string;
        "module_icon"?: string;
        "module_number"?: string;
        "paragraph_video"?: string;
        "settings"?: YduqsModulePlaylists;
        "subtitle_gallery"?: string;
        "title_gallery"?: string;
        "title_video"?: string;
    }
    interface YduqsMotivationalMessages {
    }
    interface YduqsNotification {
        "dismissible"?: boolean;
        "onClose"?: (event: YduqsNotificationCustomEvent<any>) => void;
        "open"?: boolean;
        "type"?: string;
    }
    interface YduqsNotifications {
        "position"?: string;
    }
    interface YduqsOrderedDndChallenge {
        /**
          * Identificador do Mapa
         */
        "_id"?: string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
        /**
          * Evento disparado no Final do Desafio
         */
        "onChallengeEnd"?: (event: YduqsOrderedDndChallengeCustomEvent<any>) => void;
    }
    interface YduqsOrderedDndTrainning {
        /**
          * Identificador do Mapa
         */
        "_id"?: string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
        /**
          * Evento disparado no Final do Treinamento
         */
        "onTrainningEnd"?: (event: YduqsOrderedDndTrainningCustomEvent<any>) => void;
    }
    interface YduqsPageGenericLab {
        /**
          * Define se o padrao de cores deve seguir um tema claro (light) ou escuro (dark)
         */
        "bg"?: 'dark' | 'light';
        /**
          * Define se o container é fluido (ocupa toda a tela) ou não (centralizado, seguindo o Grid definido)
         */
        "fluid"?: boolean;
    }
    interface YduqsPager {
    }
    interface YduqsPlaylistVideo {
        "english"?: boolean;
        "module_number"?: number;
        "spanish"?: boolean;
    }
    interface YduqsPodcast {
        "audio"?: string;
        "dark"?: boolean;
        "subtitulo"?: string;
        "withtitle"?: boolean;
    }
    interface YduqsProgressBar {
        "displayValue"?: boolean;
        "max"?: number;
        "min"?: number;
        "onChangebar"?: (event: YduqsProgressBarCustomEvent<any>) => void;
        "onHoverbar"?: (event: YduqsProgressBarCustomEvent<any>) => void;
        "semirounded"?: boolean;
        "value"?: number;
    }
    interface YduqsQuestions {
        "colunalg"?: string;
        "english"?: boolean;
        "math"?: boolean;
        "math_advanced"?: boolean;
        "settings"?: YduqsQuestionsModel;
        "spanish"?: boolean;
    }
    interface YduqsQuiz {
        /**
          * Lista opções disponíveis para escolha. Esse campo aceita uma string JSON ou um Objeto JSON { id: number; label: string; value: any; }
         */
        "answers": string | iQuizAnswer[];
        /**
          * Identificador do Quiz
         */
        "dataid": number | string;
        /**
          * Descrição da Pergunta. Esse campo suporta HTML
         */
        "description"?: string;
        /**
          * Tipo de index das opções: Textual (a, b, c, etc) ou numérico (1, 2, 3, etc)
         */
        "indexType"?: 'number' | 'letter';
        /**
          * Evento disparado sempre que uma opção é selecionada
         */
        "onQuizSelect"?: (event: YduqsQuizCustomEvent<iQuizAnswer>) => void;
        /**
          * Texto que aparece sobre a Pergunta
         */
        "overline"?: string;
        /**
          * Texto da Pergunta
         */
        "question": string;
    }
    interface YduqsQuote {
        "dark"?: boolean;
        "size"?: string;
    }
    interface YduqsQuoteBody {
    }
    interface YduqsQuoteImage {
        "path"?: string;
    }
    interface YduqsRange {
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "output"?: (value: number) => void;
        "step"?: number;
        "value"?: number;
    }
    interface YduqsRating {
        "cta"?: string;
        "icon"?: string;
        "module"?: string;
        "tamanho"?: string;
    }
    interface YduqsScore {
        /**
          * Identificador do Quiz
         */
        "dataid": number | string;
        /**
          * Texto de subtítulo
         */
        "datasubtitle"?: string;
        /**
          * Título do componente
         */
        "datatitle"?: string;
        /**
          * Lista de itens
         */
        "items"?: iScoreItem[] | string;
    }
    interface YduqsSearchBar {
    }
    interface YduqsShowPoints {
        /**
          * Identificador do Mapa
         */
        "_id"?: string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
    }
    interface YduqsTab {
        "disabled"?: boolean;
        "header"?: string;
        "open"?: boolean;
        "outline"?: string;
        "type"?: string;
    }
    interface YduqsTabs {
        "darkmode"?: boolean;
        "fixed_titles"?: boolean;
        "gtm_action"?: Array<String>;
        "gtm_category"?: Array<String>;
        "gtm_label"?: Array<String>;
        "icons"?: Array<String>;
        "onChanged"?: (event: YduqsTabsCustomEvent<any>) => void;
        "outlined"?: boolean;
    }
    interface YduqsTag {
        "color"?: string;
    }
    interface YduqsTags {
    }
    interface YduqsTeoria {
    }
    interface YduqsTextarea {
        "bgfeedbackdark"?: boolean;
        "colunaslg"?: number;
        "colunasmd"?: number;
        "hidden_feedback"?: boolean;
        "idbtn"?: string;
        "idtxt"?: string;
        "ligthtxtarea"?: boolean;
        "outlinetxtarea"?: boolean;
        "placeholder"?: string;
        "withbtn"?: boolean;
    }
    interface YduqsTimeline {
        "dark"?: boolean;
        "horizontal"?: boolean;
    }
    interface YduqsTimelineItem {
        "icon"?: string;
        "last"?: boolean;
    }
    interface YduqsTitle {
        "dark"?: boolean;
        "topic_icon"?: string;
        "topic_title"?: string;
    }
    interface YduqsToast {
        "delay"?: number;
        "icon"?: string;
        "message"?: string;
        "onToastClosed"?: (event: YduqsToastCustomEvent<boolean>) => void;
        "open"?: boolean;
        "tit"?: string;
        "usematerial"?: boolean;
    }
    interface YduqsToggle {
        "disable"?: boolean;
        "onMyToggleEmit"?: (event: YduqsToggleCustomEvent<any>) => void;
        "open"?: boolean;
        "teste"?: String;
    }
    interface YduqsVideoPlayer {
        "bgcolor"?: string;
        "covered"?: boolean;
        "height"?: string;
        "src"?: string;
        "transparent"?: boolean;
        "videoId"?: string;
        "width"?: string;
    }
    interface YduqsVirtualMap {
        /**
          * Identificador do Mapa
         */
        "_id"?: string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
        /**
          * Evento disparado no clique de cada ponto
         */
        "onVirtualMapPointClick"?: (event: YduqsVirtualMapCustomEvent<any>) => void;
        /**
          * Número do item que será marcado como ponto atual.
         */
        "selected"?: number;
    }
    interface YduqsZoomChallenge {
        /**
          * Identificador do Mapa
         */
        "_id"?: string;
        /**
          * Endereço do arquivo de configuração
         */
        "config": string;
        /**
          * Evento disparado no Final do Desafio
         */
        "onChallengeEnd"?: (event: YduqsZoomChallengeCustomEvent<any>) => void;
    }
    interface YduqsZoomFullScreen {
        "alt"?: string;
        "max"?: number;
        "min"?: number;
        "src"?: string;
        "step"?: number;
    }
    interface IntrinsicElements {
        "my-stace": MyStace;
        "stace-editor": StaceEditor;
        "yduqs-accordion": YduqsAccordion;
        "yduqs-accordion-pane": YduqsAccordionPane;
        "yduqs-alert": YduqsAlert;
        "yduqs-atividade-discursiva": YduqsAtividadeDiscursiva;
        "yduqs-audio-card": YduqsAudioCard;
        "yduqs-audio-player": YduqsAudioPlayer;
        "yduqs-before-after": YduqsBeforeAfter;
        "yduqs-caixa-formula": YduqsCaixaFormula;
        "yduqs-card": YduqsCard;
        "yduqs-card-body": YduqsCardBody;
        "yduqs-card-comparativo": YduqsCardComparativo;
        "yduqs-card-comparativo-body": YduqsCardComparativoBody;
        "yduqs-card-comparativo-header": YduqsCardComparativoHeader;
        "yduqs-card-comparativo-item": YduqsCardComparativoItem;
        "yduqs-card-destaque": YduqsCardDestaque;
        "yduqs-card-destaque-body": YduqsCardDestaqueBody;
        "yduqs-card-destaque-header": YduqsCardDestaqueHeader;
        "yduqs-card-footer": YduqsCardFooter;
        "yduqs-card-header": YduqsCardHeader;
        "yduqs-card-horizontal": YduqsCardHorizontal;
        "yduqs-card-intro": YduqsCardIntro;
        "yduqs-card-modulo": YduqsCardModulo;
        "yduqs-card-modulo-body": YduqsCardModuloBody;
        "yduqs-card-modulo-footer": YduqsCardModuloFooter;
        "yduqs-card-modulo-header": YduqsCardModuloHeader;
        "yduqs-card-selecionavel": YduqsCardSelecionavel;
        "yduqs-card-selecionavel-item": YduqsCardSelecionavelItem;
        "yduqs-card-video": YduqsCardVideo;
        "yduqs-carousel": YduqsCarousel;
        "yduqs-carousel-item": YduqsCarouselItem;
        "yduqs-code-compiler": YduqsCodeCompiler;
        "yduqs-code-snipet": YduqsCodeSnipet;
        "yduqs-collapse": YduqsCollapse;
        "yduqs-collapse-content": YduqsCollapseContent;
        "yduqs-collapse-teoria": YduqsCollapseTeoria;
        "yduqs-collapse-teoria-content": YduqsCollapseTeoriaContent;
        "yduqs-confirm": YduqsConfirm;
        "yduqs-countdown": YduqsCountdown;
        "yduqs-cover": YduqsCover;
        "yduqs-cover-lab": YduqsCoverLab;
        "yduqs-cover-stage-lab": YduqsCoverStageLab;
        "yduqs-destaque-texto": YduqsDestaqueTexto;
        "yduqs-dropdown": YduqsDropdown;
        "yduqs-feedback-thumb": YduqsFeedbackThumb;
        "yduqs-footer": YduqsFooter;
        "yduqs-gallery-video": YduqsGalleryVideo;
        "yduqs-header-lab": YduqsHeaderLab;
        "yduqs-helper": YduqsHelper;
        "yduqs-image": YduqsImage;
        "yduqs-info": YduqsInfo;
        "yduqs-input": YduqsInput;
        "yduqs-interactive-media": YduqsInteractiveMedia;
        "yduqs-lab-error": YduqsLabError;
        "yduqs-lab-intro": YduqsLabIntro;
        "yduqs-lab-phase": YduqsLabPhase;
        "yduqs-lab-questions": YduqsLabQuestions;
        "yduqs-listas": YduqsListas;
        "yduqs-loader": YduqsLoader;
        "yduqs-loading": YduqsLoading;
        "yduqs-menu": YduqsMenu;
        "yduqs-modal": YduqsModal;
        "yduqs-module-cover": YduqsModuleCover;
        "yduqs-module-rating": YduqsModuleRating;
        "yduqs-module-video": YduqsModuleVideo;
        "yduqs-motivational-messages": YduqsMotivationalMessages;
        "yduqs-notification": YduqsNotification;
        "yduqs-notifications": YduqsNotifications;
        "yduqs-ordered-dnd-challenge": YduqsOrderedDndChallenge;
        "yduqs-ordered-dnd-trainning": YduqsOrderedDndTrainning;
        "yduqs-page-generic-lab": YduqsPageGenericLab;
        "yduqs-pager": YduqsPager;
        "yduqs-playlist-video": YduqsPlaylistVideo;
        "yduqs-podcast": YduqsPodcast;
        "yduqs-progress-bar": YduqsProgressBar;
        "yduqs-questions": YduqsQuestions;
        "yduqs-quiz": YduqsQuiz;
        "yduqs-quote": YduqsQuote;
        "yduqs-quote-body": YduqsQuoteBody;
        "yduqs-quote-image": YduqsQuoteImage;
        "yduqs-range": YduqsRange;
        "yduqs-rating": YduqsRating;
        "yduqs-score": YduqsScore;
        "yduqs-search-bar": YduqsSearchBar;
        "yduqs-show-points": YduqsShowPoints;
        "yduqs-tab": YduqsTab;
        "yduqs-tabs": YduqsTabs;
        "yduqs-tag": YduqsTag;
        "yduqs-tags": YduqsTags;
        "yduqs-teoria": YduqsTeoria;
        "yduqs-textarea": YduqsTextarea;
        "yduqs-timeline": YduqsTimeline;
        "yduqs-timeline-item": YduqsTimelineItem;
        "yduqs-title": YduqsTitle;
        "yduqs-toast": YduqsToast;
        "yduqs-toggle": YduqsToggle;
        "yduqs-video-player": YduqsVideoPlayer;
        "yduqs-virtual-map": YduqsVirtualMap;
        "yduqs-zoom-challenge": YduqsZoomChallenge;
        "yduqs-zoom-full-screen": YduqsZoomFullScreen;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-stace": LocalJSX.MyStace & JSXBase.HTMLAttributes<HTMLMyStaceElement>;
            "stace-editor": LocalJSX.StaceEditor & JSXBase.HTMLAttributes<HTMLStaceEditorElement>;
            "yduqs-accordion": LocalJSX.YduqsAccordion & JSXBase.HTMLAttributes<HTMLYduqsAccordionElement>;
            "yduqs-accordion-pane": LocalJSX.YduqsAccordionPane & JSXBase.HTMLAttributes<HTMLYduqsAccordionPaneElement>;
            "yduqs-alert": LocalJSX.YduqsAlert & JSXBase.HTMLAttributes<HTMLYduqsAlertElement>;
            "yduqs-atividade-discursiva": LocalJSX.YduqsAtividadeDiscursiva & JSXBase.HTMLAttributes<HTMLYduqsAtividadeDiscursivaElement>;
            "yduqs-audio-card": LocalJSX.YduqsAudioCard & JSXBase.HTMLAttributes<HTMLYduqsAudioCardElement>;
            "yduqs-audio-player": LocalJSX.YduqsAudioPlayer & JSXBase.HTMLAttributes<HTMLYduqsAudioPlayerElement>;
            "yduqs-before-after": LocalJSX.YduqsBeforeAfter & JSXBase.HTMLAttributes<HTMLYduqsBeforeAfterElement>;
            "yduqs-caixa-formula": LocalJSX.YduqsCaixaFormula & JSXBase.HTMLAttributes<HTMLYduqsCaixaFormulaElement>;
            "yduqs-card": LocalJSX.YduqsCard & JSXBase.HTMLAttributes<HTMLYduqsCardElement>;
            "yduqs-card-body": LocalJSX.YduqsCardBody & JSXBase.HTMLAttributes<HTMLYduqsCardBodyElement>;
            "yduqs-card-comparativo": LocalJSX.YduqsCardComparativo & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoElement>;
            "yduqs-card-comparativo-body": LocalJSX.YduqsCardComparativoBody & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoBodyElement>;
            "yduqs-card-comparativo-header": LocalJSX.YduqsCardComparativoHeader & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoHeaderElement>;
            "yduqs-card-comparativo-item": LocalJSX.YduqsCardComparativoItem & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoItemElement>;
            "yduqs-card-destaque": LocalJSX.YduqsCardDestaque & JSXBase.HTMLAttributes<HTMLYduqsCardDestaqueElement>;
            "yduqs-card-destaque-body": LocalJSX.YduqsCardDestaqueBody & JSXBase.HTMLAttributes<HTMLYduqsCardDestaqueBodyElement>;
            "yduqs-card-destaque-header": LocalJSX.YduqsCardDestaqueHeader & JSXBase.HTMLAttributes<HTMLYduqsCardDestaqueHeaderElement>;
            "yduqs-card-footer": LocalJSX.YduqsCardFooter & JSXBase.HTMLAttributes<HTMLYduqsCardFooterElement>;
            "yduqs-card-header": LocalJSX.YduqsCardHeader & JSXBase.HTMLAttributes<HTMLYduqsCardHeaderElement>;
            "yduqs-card-horizontal": LocalJSX.YduqsCardHorizontal & JSXBase.HTMLAttributes<HTMLYduqsCardHorizontalElement>;
            "yduqs-card-intro": LocalJSX.YduqsCardIntro & JSXBase.HTMLAttributes<HTMLYduqsCardIntroElement>;
            "yduqs-card-modulo": LocalJSX.YduqsCardModulo & JSXBase.HTMLAttributes<HTMLYduqsCardModuloElement>;
            "yduqs-card-modulo-body": LocalJSX.YduqsCardModuloBody & JSXBase.HTMLAttributes<HTMLYduqsCardModuloBodyElement>;
            "yduqs-card-modulo-footer": LocalJSX.YduqsCardModuloFooter & JSXBase.HTMLAttributes<HTMLYduqsCardModuloFooterElement>;
            "yduqs-card-modulo-header": LocalJSX.YduqsCardModuloHeader & JSXBase.HTMLAttributes<HTMLYduqsCardModuloHeaderElement>;
            "yduqs-card-selecionavel": LocalJSX.YduqsCardSelecionavel & JSXBase.HTMLAttributes<HTMLYduqsCardSelecionavelElement>;
            "yduqs-card-selecionavel-item": LocalJSX.YduqsCardSelecionavelItem & JSXBase.HTMLAttributes<HTMLYduqsCardSelecionavelItemElement>;
            "yduqs-card-video": LocalJSX.YduqsCardVideo & JSXBase.HTMLAttributes<HTMLYduqsCardVideoElement>;
            "yduqs-carousel": LocalJSX.YduqsCarousel & JSXBase.HTMLAttributes<HTMLYduqsCarouselElement>;
            "yduqs-carousel-item": LocalJSX.YduqsCarouselItem & JSXBase.HTMLAttributes<HTMLYduqsCarouselItemElement>;
            "yduqs-code-compiler": LocalJSX.YduqsCodeCompiler & JSXBase.HTMLAttributes<HTMLYduqsCodeCompilerElement>;
            "yduqs-code-snipet": LocalJSX.YduqsCodeSnipet & JSXBase.HTMLAttributes<HTMLYduqsCodeSnipetElement>;
            "yduqs-collapse": LocalJSX.YduqsCollapse & JSXBase.HTMLAttributes<HTMLYduqsCollapseElement>;
            "yduqs-collapse-content": LocalJSX.YduqsCollapseContent & JSXBase.HTMLAttributes<HTMLYduqsCollapseContentElement>;
            "yduqs-collapse-teoria": LocalJSX.YduqsCollapseTeoria & JSXBase.HTMLAttributes<HTMLYduqsCollapseTeoriaElement>;
            "yduqs-collapse-teoria-content": LocalJSX.YduqsCollapseTeoriaContent & JSXBase.HTMLAttributes<HTMLYduqsCollapseTeoriaContentElement>;
            "yduqs-confirm": LocalJSX.YduqsConfirm & JSXBase.HTMLAttributes<HTMLYduqsConfirmElement>;
            "yduqs-countdown": LocalJSX.YduqsCountdown & JSXBase.HTMLAttributes<HTMLYduqsCountdownElement>;
            "yduqs-cover": LocalJSX.YduqsCover & JSXBase.HTMLAttributes<HTMLYduqsCoverElement>;
            "yduqs-cover-lab": LocalJSX.YduqsCoverLab & JSXBase.HTMLAttributes<HTMLYduqsCoverLabElement>;
            "yduqs-cover-stage-lab": LocalJSX.YduqsCoverStageLab & JSXBase.HTMLAttributes<HTMLYduqsCoverStageLabElement>;
            "yduqs-destaque-texto": LocalJSX.YduqsDestaqueTexto & JSXBase.HTMLAttributes<HTMLYduqsDestaqueTextoElement>;
            "yduqs-dropdown": LocalJSX.YduqsDropdown & JSXBase.HTMLAttributes<HTMLYduqsDropdownElement>;
            "yduqs-feedback-thumb": LocalJSX.YduqsFeedbackThumb & JSXBase.HTMLAttributes<HTMLYduqsFeedbackThumbElement>;
            "yduqs-footer": LocalJSX.YduqsFooter & JSXBase.HTMLAttributes<HTMLYduqsFooterElement>;
            "yduqs-gallery-video": LocalJSX.YduqsGalleryVideo & JSXBase.HTMLAttributes<HTMLYduqsGalleryVideoElement>;
            "yduqs-header-lab": LocalJSX.YduqsHeaderLab & JSXBase.HTMLAttributes<HTMLYduqsHeaderLabElement>;
            "yduqs-helper": LocalJSX.YduqsHelper & JSXBase.HTMLAttributes<HTMLYduqsHelperElement>;
            "yduqs-image": LocalJSX.YduqsImage & JSXBase.HTMLAttributes<HTMLYduqsImageElement>;
            "yduqs-info": LocalJSX.YduqsInfo & JSXBase.HTMLAttributes<HTMLYduqsInfoElement>;
            "yduqs-input": LocalJSX.YduqsInput & JSXBase.HTMLAttributes<HTMLYduqsInputElement>;
            "yduqs-interactive-media": LocalJSX.YduqsInteractiveMedia & JSXBase.HTMLAttributes<HTMLYduqsInteractiveMediaElement>;
            "yduqs-lab-error": LocalJSX.YduqsLabError & JSXBase.HTMLAttributes<HTMLYduqsLabErrorElement>;
            "yduqs-lab-intro": LocalJSX.YduqsLabIntro & JSXBase.HTMLAttributes<HTMLYduqsLabIntroElement>;
            "yduqs-lab-phase": LocalJSX.YduqsLabPhase & JSXBase.HTMLAttributes<HTMLYduqsLabPhaseElement>;
            "yduqs-lab-questions": LocalJSX.YduqsLabQuestions & JSXBase.HTMLAttributes<HTMLYduqsLabQuestionsElement>;
            "yduqs-listas": LocalJSX.YduqsListas & JSXBase.HTMLAttributes<HTMLYduqsListasElement>;
            "yduqs-loader": LocalJSX.YduqsLoader & JSXBase.HTMLAttributes<HTMLYduqsLoaderElement>;
            "yduqs-loading": LocalJSX.YduqsLoading & JSXBase.HTMLAttributes<HTMLYduqsLoadingElement>;
            "yduqs-menu": LocalJSX.YduqsMenu & JSXBase.HTMLAttributes<HTMLYduqsMenuElement>;
            "yduqs-modal": LocalJSX.YduqsModal & JSXBase.HTMLAttributes<HTMLYduqsModalElement>;
            "yduqs-module-cover": LocalJSX.YduqsModuleCover & JSXBase.HTMLAttributes<HTMLYduqsModuleCoverElement>;
            "yduqs-module-rating": LocalJSX.YduqsModuleRating & JSXBase.HTMLAttributes<HTMLYduqsModuleRatingElement>;
            "yduqs-module-video": LocalJSX.YduqsModuleVideo & JSXBase.HTMLAttributes<HTMLYduqsModuleVideoElement>;
            "yduqs-motivational-messages": LocalJSX.YduqsMotivationalMessages & JSXBase.HTMLAttributes<HTMLYduqsMotivationalMessagesElement>;
            "yduqs-notification": LocalJSX.YduqsNotification & JSXBase.HTMLAttributes<HTMLYduqsNotificationElement>;
            "yduqs-notifications": LocalJSX.YduqsNotifications & JSXBase.HTMLAttributes<HTMLYduqsNotificationsElement>;
            "yduqs-ordered-dnd-challenge": LocalJSX.YduqsOrderedDndChallenge & JSXBase.HTMLAttributes<HTMLYduqsOrderedDndChallengeElement>;
            "yduqs-ordered-dnd-trainning": LocalJSX.YduqsOrderedDndTrainning & JSXBase.HTMLAttributes<HTMLYduqsOrderedDndTrainningElement>;
            "yduqs-page-generic-lab": LocalJSX.YduqsPageGenericLab & JSXBase.HTMLAttributes<HTMLYduqsPageGenericLabElement>;
            "yduqs-pager": LocalJSX.YduqsPager & JSXBase.HTMLAttributes<HTMLYduqsPagerElement>;
            "yduqs-playlist-video": LocalJSX.YduqsPlaylistVideo & JSXBase.HTMLAttributes<HTMLYduqsPlaylistVideoElement>;
            "yduqs-podcast": LocalJSX.YduqsPodcast & JSXBase.HTMLAttributes<HTMLYduqsPodcastElement>;
            "yduqs-progress-bar": LocalJSX.YduqsProgressBar & JSXBase.HTMLAttributes<HTMLYduqsProgressBarElement>;
            "yduqs-questions": LocalJSX.YduqsQuestions & JSXBase.HTMLAttributes<HTMLYduqsQuestionsElement>;
            "yduqs-quiz": LocalJSX.YduqsQuiz & JSXBase.HTMLAttributes<HTMLYduqsQuizElement>;
            "yduqs-quote": LocalJSX.YduqsQuote & JSXBase.HTMLAttributes<HTMLYduqsQuoteElement>;
            "yduqs-quote-body": LocalJSX.YduqsQuoteBody & JSXBase.HTMLAttributes<HTMLYduqsQuoteBodyElement>;
            "yduqs-quote-image": LocalJSX.YduqsQuoteImage & JSXBase.HTMLAttributes<HTMLYduqsQuoteImageElement>;
            "yduqs-range": LocalJSX.YduqsRange & JSXBase.HTMLAttributes<HTMLYduqsRangeElement>;
            "yduqs-rating": LocalJSX.YduqsRating & JSXBase.HTMLAttributes<HTMLYduqsRatingElement>;
            "yduqs-score": LocalJSX.YduqsScore & JSXBase.HTMLAttributes<HTMLYduqsScoreElement>;
            "yduqs-search-bar": LocalJSX.YduqsSearchBar & JSXBase.HTMLAttributes<HTMLYduqsSearchBarElement>;
            "yduqs-show-points": LocalJSX.YduqsShowPoints & JSXBase.HTMLAttributes<HTMLYduqsShowPointsElement>;
            "yduqs-tab": LocalJSX.YduqsTab & JSXBase.HTMLAttributes<HTMLYduqsTabElement>;
            "yduqs-tabs": LocalJSX.YduqsTabs & JSXBase.HTMLAttributes<HTMLYduqsTabsElement>;
            "yduqs-tag": LocalJSX.YduqsTag & JSXBase.HTMLAttributes<HTMLYduqsTagElement>;
            "yduqs-tags": LocalJSX.YduqsTags & JSXBase.HTMLAttributes<HTMLYduqsTagsElement>;
            "yduqs-teoria": LocalJSX.YduqsTeoria & JSXBase.HTMLAttributes<HTMLYduqsTeoriaElement>;
            "yduqs-textarea": LocalJSX.YduqsTextarea & JSXBase.HTMLAttributes<HTMLYduqsTextareaElement>;
            "yduqs-timeline": LocalJSX.YduqsTimeline & JSXBase.HTMLAttributes<HTMLYduqsTimelineElement>;
            "yduqs-timeline-item": LocalJSX.YduqsTimelineItem & JSXBase.HTMLAttributes<HTMLYduqsTimelineItemElement>;
            "yduqs-title": LocalJSX.YduqsTitle & JSXBase.HTMLAttributes<HTMLYduqsTitleElement>;
            "yduqs-toast": LocalJSX.YduqsToast & JSXBase.HTMLAttributes<HTMLYduqsToastElement>;
            "yduqs-toggle": LocalJSX.YduqsToggle & JSXBase.HTMLAttributes<HTMLYduqsToggleElement>;
            "yduqs-video-player": LocalJSX.YduqsVideoPlayer & JSXBase.HTMLAttributes<HTMLYduqsVideoPlayerElement>;
            "yduqs-virtual-map": LocalJSX.YduqsVirtualMap & JSXBase.HTMLAttributes<HTMLYduqsVirtualMapElement>;
            "yduqs-zoom-challenge": LocalJSX.YduqsZoomChallenge & JSXBase.HTMLAttributes<HTMLYduqsZoomChallengeElement>;
            "yduqs-zoom-full-screen": LocalJSX.YduqsZoomFullScreen & JSXBase.HTMLAttributes<HTMLYduqsZoomFullScreenElement>;
        }
    }
}
