import { EventEmitter } from '../../../stencil-public-runtime';
import { YduqsMenuModel } from './yduqs-menu.model';
export declare class YduqsMenu {
  el: HTMLElement;
  onChangeMenuData: EventEmitter;
  onClickMenuItem: EventEmitter;
  _isMobile: boolean;
  _isOpen: boolean;
  _isOpenGallery: boolean;
  _isActive: boolean;
  _animate: boolean;
  _activeIndex: number;
  _videoModule: number;
  menuDeskContainerEl: HTMLDivElement;
  _menuDeskContainerWidth: string;
  settings: YduqsMenuModel;
  position: number;
  english: boolean;
  spanish: boolean;
  handleWindowResize(): void;
  initialize(config: YduqsMenuModel): Promise<void>;
  private closeMenu;
  watchHandler(): void;
  private openMenu;
  private updateActiveItem;
  private renderActiveMarker;
  private renderNameModule;
  private renderMenuJorney;
  private renderMenuMedia;
  private renderMenuActivity;
  private getMenuRender;
  private animate;
  componentWillLoad(): void;
  componentDidLoad(): void;
  componentDidRender(): void;
  render(): any;
}
