/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { Editor } from "brace";
import { YduqsAudioPlayerModel } from "./components/atoms/yduqs-audio-player/yduqs-audio-player.model";
import { YduqsModulePlaylists } from "./components/patterns/yduqs-gallery-video/yduqs-gallery-video.model";
import { YduqsMenuModel } from "./components/atoms/yduqs-menu/yduqs-menu.model";
import { YduqsModulePlaylists as YduqsModulePlaylists1 } from "./components/patterns/yduqs-module-video/yduqs-module-video.model";
import { YduqsModulesPlaylists } from "./components/patterns/yduqs-playlist-video/yduqs-playlist-video.model";
import { YduqsQuestionsModel } from "./components/patterns/yduqs-questions/yduqs-questions.model";
export namespace Components {
    interface MyStace {
        "autoUpdateContent": boolean;
        "durationBeforeCallback": number;
        "getEditor": () => Promise<Editor>;
        "mode": string;
        "options": any;
        "readOnly": boolean;
        "text": string;
        "theme": string;
        "timeoutSaving": any;
    }
    interface StaceEditor {
        "autoUpdateContent": boolean;
        "durationBeforeCallback": number;
        "getEditor": () => Promise<Editor>;
        "mode": string;
        "options": any;
        "readOnly": boolean;
        "text": string;
        "theme": string;
        "timeoutSaving": any;
    }
    interface YduqsAccordion {
        "outline": boolean;
    }
    interface YduqsAccordionPane {
        "close": () => Promise<void>;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface YduqsAtividadeDiscursiva {
    }
    interface YduqsAudioCard {
        "audiocard_id": string;
        "dark": boolean;
        "equal_height": boolean;
        "group": boolean;
        "outlined": boolean;
        "playAudioStop": () => Promise<void>;
        "playAudioStopSlow": () => Promise<void>;
        "src": string;
        "subtitle_audio_card": string;
        "title_audio_card": string;
    }
    interface YduqsAudioPlayer {
        "audio_id": string;
        "dark": boolean;
        "initialize": (config: YduqsAudioPlayerModel) => Promise<void>;
        "rate": number;
        "settings": YduqsAudioPlayerModel;
        "shortdisplay": boolean;
        "src": string;
    }
    interface YduqsBeforeAfter {
        "after_img": string;
        "after_img_alt": string;
        "after_img_title": string;
        "before_img": string;
        "before_img_alt": string;
        "before_img_title": string;
        "caption": string;
    }
    interface YduqsCaixaFormula {
        "dark": boolean;
        "equal_height": boolean;
        "formula": string;
        "rotate_info": boolean;
        "title_formula": string;
    }
    interface YduqsCard {
        "dark": boolean;
        "equal_height": boolean;
        "outlined": boolean;
    }
    interface YduqsCardBody {
    }
    interface YduqsCardComparativo {
        "dark": boolean;
        "icon": string;
        "outline": boolean;
        "rotate_mobile": boolean;
    }
    interface YduqsCardComparativoBody {
    }
    interface YduqsCardComparativoHeader {
    }
    interface YduqsCardComparativoItem {
    }
    interface YduqsCardDestaque {
        "grade": number;
        "icon": string;
        "outline": boolean;
    }
    interface YduqsCardDestaqueBody {
    }
    interface YduqsCardDestaqueHeader {
    }
    interface YduqsCardFooter {
    }
    interface YduqsCardHeader {
    }
    interface YduqsCardHorizontal {
        "card_icon": string;
        "card_image": string;
        "english": boolean;
        "image_alt": string;
        "image_title": string;
        "isquestion": boolean;
        "spanish": boolean;
    }
    interface YduqsCardIntro {
        "text": string;
    }
    interface YduqsCardModulo {
        "progress": number;
    }
    interface YduqsCardModuloBody {
    }
    interface YduqsCardModuloFooter {
    }
    interface YduqsCardModuloHeader {
    }
    interface YduqsCardSelecionavel {
    }
    interface YduqsCardSelecionavelItem {
        "disabled"?: boolean;
        "isSelected": () => Promise<boolean>;
        "optionid": string;
        "selectItem": () => Promise<void>;
        "selected": boolean;
        "unselectItem": () => Promise<void>;
    }
    interface YduqsCardVideo {
        "active": boolean;
        "border_bottom": boolean;
        "link_video": string;
        "paragraph": string;
        "subtitle_video": string;
        "thumb_video": string;
        "time": string;
        "title_video": string;
    }
    interface YduqsCarousel {
        "english": boolean;
        "next": () => Promise<void>;
        "prev": () => Promise<void>;
        "space": number;
        "spanish": boolean;
    }
    interface YduqsCarouselItem {
    }
    interface YduqsCodeCompiler {
        "code": string;
        "copy": (code: any) => Promise<void>;
        "dark": boolean;
        "exercise_title": string;
        "input_keyboard": string;
        "language_code": string;
    }
    interface YduqsCodeSnipet {
        "code": string;
        "copy": (code: any) => Promise<void>;
        "dark": boolean;
        "input_keyboard": string;
        "language_code": string;
        "size": string;
    }
    interface YduqsCollapse {
        "border": boolean;
        "outline": boolean;
    }
    interface YduqsCollapseContent {
        "close": () => Promise<void>;
        "header": string;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
        "size": string;
    }
    interface YduqsCollapseTeoria {
        "border": boolean;
        "outline": boolean;
    }
    interface YduqsCollapseTeoriaContent {
        "close": () => Promise<void>;
        "header": string;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
        "size": string;
        "teoria": boolean;
    }
    interface YduqsCover {
        "avatar": Array<any>;
        "background_img": string;
        "background_img_title": string;
        "background_text": string;
        "background_text_mobile": string;
        "colaboradores": () => Promise<void>;
        "colaboradores_nome": Array<any>;
        "collaboration_text": string;
        "contributors": string;
        "cover_preparation": boolean;
        "curadores": () => Promise<void>;
        "english": boolean;
        "lg_title": boolean;
        "link": Array<any>;
        "names_clb": Array<any>;
        "names_prof": Array<any>;
        "professores": Array<any>;
        "spanish": boolean;
        "teacher": string;
        "teacher_avatar": string;
        "teacher_link": string;
        "template_anitta": boolean;
        "title_cover": string;
        "title_size": string;
        "xl_title": boolean;
    }
    interface YduqsDestaqueTexto {
        "size": string;
    }
    interface YduqsDropdown {
        "colunas": string;
        "createOptionsDrop": () => Promise<void>;
        "createOptionsSelect": () => Promise<void>;
        "identificador": string;
        "tipo": string;
    }
    interface YduqsFooter {
        "btnimprimir": boolean;
        "english": boolean;
        "hrefbtnprint": string;
        "namebtnimprimir": string;
        "spanish": boolean;
        "template_anitta": boolean;
        "useimage": boolean;
    }
    interface YduqsGalleryVideo {
        "english": boolean;
        "initialize": (config: YduqsModulePlaylists) => Promise<void>;
        "module_number": number;
        "paragraph_video": string;
        "settings": YduqsModulePlaylists;
        "spanish": boolean;
        "subtitle_gallery": string;
        "title_gallery": string;
        "title_video": string;
    }
    interface YduqsImage {
        "alt": string;
        "covered": boolean;
        "height": string;
        "img_title": string;
        "src": string;
        "width": string;
    }
    interface YduqsInput {
        "alteraInput": (ev: any) => Promise<void>;
        "apagarValor": () => Promise<void>;
        "icon": any;
        "placeh": string;
        "titulo": string;
    }
    interface YduqsListas {
        "tamanho": string;
        "tipo": string;
    }
    interface YduqsLoader {
    }
    interface YduqsLoading {
        "hide": () => Promise<void>;
        "isOpen": () => Promise<boolean>;
        "message": string;
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface YduqsMenu {
        "english": boolean;
        "initialize": (config: YduqsMenuModel) => Promise<void>;
        "position": number;
        "settings": YduqsMenuModel;
        "spanish": boolean;
    }
    interface YduqsModal {
        "isopen": boolean;
        "maxbodyheight": number;
        "showModal": () => Promise<void>;
    }
    interface YduqsModuleCover {
        "img_cover": string;
        "midia_time": string;
        "number_module": string;
        "objective": string;
        "read_time": string;
        "title_midia_time": string;
        "title_module": string;
        "title_read_time": string;
    }
    interface YduqsModuleRating {
        "cta": string;
        "english": boolean;
        "icon": string;
        "module": string;
        "spanish": boolean;
        "tamanho": string;
    }
    interface YduqsModuleVideo {
        "active_video": string;
        "initialize": (config: YduqsModulePlaylists) => Promise<void>;
        "module_icon": string;
        "module_number": number;
        "paragraph_video": string;
        "settings": YduqsModulePlaylists;
        "subtitle_gallery": string;
        "title_gallery": string;
        "title_video": string;
    }
    interface YduqsNotification {
        "close": () => Promise<void>;
        "dismissible": boolean;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
        "type": string;
    }
    interface YduqsNotifications {
        "position": string;
    }
    interface YduqsPlaylistVideo {
        "initialize": (config: YduqsModulesPlaylists) => Promise<void>;
        "module_number": number;
        "settings": YduqsModulesPlaylists;
    }
    interface YduqsPodcast {
        "audio": string;
        "changeColor": (novoValor: any) => Promise<void>;
        "dark": boolean;
        "showtitle": (value: any) => Promise<void>;
        "subtitulo": string;
        "withtitle": boolean;
    }
    interface YduqsProgressBar {
        "displayValue": boolean;
        "hide": () => Promise<void>;
        "isValueVisible": () => Promise<boolean>;
        "max": number;
        "min": number;
        "semirounded": boolean;
        "show": () => Promise<void>;
        "value": number;
    }
    interface YduqsQuestions {
        "colunalg": string;
        "english": boolean;
        "initialize": (config: YduqsQuestionsModel) => Promise<void>;
        "math": boolean;
        "math_advanced": boolean;
        "settings": YduqsQuestionsModel;
        "spanish": boolean;
    }
    interface YduqsQuote {
        "dark": boolean;
        "size": string;
    }
    interface YduqsQuoteBody {
    }
    interface YduqsQuoteImage {
        "path": string;
    }
    interface YduqsRating {
        "cta": string;
        "icon": string;
        "module": string;
        "tamanho": string;
    }
    interface YduqsTab {
        "disabled": boolean;
        "header": string;
        "open": boolean;
        "outline": string;
        "type": string;
    }
    interface YduqsTabs {
        "currentTab": () => Promise<number>;
        "darkmode": boolean;
        "fixed_titles": boolean;
        "gtm_action": Array<String>;
        "gtm_category": Array<String>;
        "gtm_label": Array<String>;
        "icons": Array<String>;
        "openTab": (tabIndex: number) => Promise<void>;
        "outlined": boolean;
    }
    interface YduqsTag {
        "color": string;
    }
    interface YduqsTags {
    }
    interface YduqsTeoria {
    }
    interface YduqsTextarea {
        "bgfeedbackdark": boolean;
        "colunaslg": number;
        "colunasmd": number;
        "idbtn": string;
        "idtxt": string;
        "ligthtxtarea": boolean;
        "outlinetxtarea": boolean;
        "placeholder": string;
        "withbtn": boolean;
    }
    interface YduqsTimeline {
        "dark": boolean;
        "horizontal": boolean;
    }
    interface YduqsTimelineItem {
        "icon": string;
        "last": boolean;
    }
    interface YduqsTitle {
        "dark": boolean;
        "topic_icon": string;
        "topic_title": string;
    }
    interface YduqsToggle {
        "disable": boolean;
        "open": boolean;
        "teste": String;
    }
    interface YduqsVideoPlayer {
        "bgcolor": string;
        "covered": boolean;
        "height": string;
        "src": string;
        "videoId": string;
        "width": string;
    }
}
declare global {
    interface HTMLMyStaceElement extends Components.MyStace, HTMLStencilElement {
    }
    var HTMLMyStaceElement: {
        prototype: HTMLMyStaceElement;
        new (): HTMLMyStaceElement;
    };
    interface HTMLStaceEditorElement extends Components.StaceEditor, HTMLStencilElement {
    }
    var HTMLStaceEditorElement: {
        prototype: HTMLStaceEditorElement;
        new (): HTMLStaceEditorElement;
    };
    interface HTMLYduqsAccordionElement extends Components.YduqsAccordion, HTMLStencilElement {
    }
    var HTMLYduqsAccordionElement: {
        prototype: HTMLYduqsAccordionElement;
        new (): HTMLYduqsAccordionElement;
    };
    interface HTMLYduqsAccordionPaneElement extends Components.YduqsAccordionPane, HTMLStencilElement {
    }
    var HTMLYduqsAccordionPaneElement: {
        prototype: HTMLYduqsAccordionPaneElement;
        new (): HTMLYduqsAccordionPaneElement;
    };
    interface HTMLYduqsAtividadeDiscursivaElement extends Components.YduqsAtividadeDiscursiva, HTMLStencilElement {
    }
    var HTMLYduqsAtividadeDiscursivaElement: {
        prototype: HTMLYduqsAtividadeDiscursivaElement;
        new (): HTMLYduqsAtividadeDiscursivaElement;
    };
    interface HTMLYduqsAudioCardElement extends Components.YduqsAudioCard, HTMLStencilElement {
    }
    var HTMLYduqsAudioCardElement: {
        prototype: HTMLYduqsAudioCardElement;
        new (): HTMLYduqsAudioCardElement;
    };
    interface HTMLYduqsAudioPlayerElement extends Components.YduqsAudioPlayer, HTMLStencilElement {
    }
    var HTMLYduqsAudioPlayerElement: {
        prototype: HTMLYduqsAudioPlayerElement;
        new (): HTMLYduqsAudioPlayerElement;
    };
    interface HTMLYduqsBeforeAfterElement extends Components.YduqsBeforeAfter, HTMLStencilElement {
    }
    var HTMLYduqsBeforeAfterElement: {
        prototype: HTMLYduqsBeforeAfterElement;
        new (): HTMLYduqsBeforeAfterElement;
    };
    interface HTMLYduqsCaixaFormulaElement extends Components.YduqsCaixaFormula, HTMLStencilElement {
    }
    var HTMLYduqsCaixaFormulaElement: {
        prototype: HTMLYduqsCaixaFormulaElement;
        new (): HTMLYduqsCaixaFormulaElement;
    };
    interface HTMLYduqsCardElement extends Components.YduqsCard, HTMLStencilElement {
    }
    var HTMLYduqsCardElement: {
        prototype: HTMLYduqsCardElement;
        new (): HTMLYduqsCardElement;
    };
    interface HTMLYduqsCardBodyElement extends Components.YduqsCardBody, HTMLStencilElement {
    }
    var HTMLYduqsCardBodyElement: {
        prototype: HTMLYduqsCardBodyElement;
        new (): HTMLYduqsCardBodyElement;
    };
    interface HTMLYduqsCardComparativoElement extends Components.YduqsCardComparativo, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoElement: {
        prototype: HTMLYduqsCardComparativoElement;
        new (): HTMLYduqsCardComparativoElement;
    };
    interface HTMLYduqsCardComparativoBodyElement extends Components.YduqsCardComparativoBody, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoBodyElement: {
        prototype: HTMLYduqsCardComparativoBodyElement;
        new (): HTMLYduqsCardComparativoBodyElement;
    };
    interface HTMLYduqsCardComparativoHeaderElement extends Components.YduqsCardComparativoHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoHeaderElement: {
        prototype: HTMLYduqsCardComparativoHeaderElement;
        new (): HTMLYduqsCardComparativoHeaderElement;
    };
    interface HTMLYduqsCardComparativoItemElement extends Components.YduqsCardComparativoItem, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoItemElement: {
        prototype: HTMLYduqsCardComparativoItemElement;
        new (): HTMLYduqsCardComparativoItemElement;
    };
    interface HTMLYduqsCardDestaqueElement extends Components.YduqsCardDestaque, HTMLStencilElement {
    }
    var HTMLYduqsCardDestaqueElement: {
        prototype: HTMLYduqsCardDestaqueElement;
        new (): HTMLYduqsCardDestaqueElement;
    };
    interface HTMLYduqsCardDestaqueBodyElement extends Components.YduqsCardDestaqueBody, HTMLStencilElement {
    }
    var HTMLYduqsCardDestaqueBodyElement: {
        prototype: HTMLYduqsCardDestaqueBodyElement;
        new (): HTMLYduqsCardDestaqueBodyElement;
    };
    interface HTMLYduqsCardDestaqueHeaderElement extends Components.YduqsCardDestaqueHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardDestaqueHeaderElement: {
        prototype: HTMLYduqsCardDestaqueHeaderElement;
        new (): HTMLYduqsCardDestaqueHeaderElement;
    };
    interface HTMLYduqsCardFooterElement extends Components.YduqsCardFooter, HTMLStencilElement {
    }
    var HTMLYduqsCardFooterElement: {
        prototype: HTMLYduqsCardFooterElement;
        new (): HTMLYduqsCardFooterElement;
    };
    interface HTMLYduqsCardHeaderElement extends Components.YduqsCardHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardHeaderElement: {
        prototype: HTMLYduqsCardHeaderElement;
        new (): HTMLYduqsCardHeaderElement;
    };
    interface HTMLYduqsCardHorizontalElement extends Components.YduqsCardHorizontal, HTMLStencilElement {
    }
    var HTMLYduqsCardHorizontalElement: {
        prototype: HTMLYduqsCardHorizontalElement;
        new (): HTMLYduqsCardHorizontalElement;
    };
    interface HTMLYduqsCardIntroElement extends Components.YduqsCardIntro, HTMLStencilElement {
    }
    var HTMLYduqsCardIntroElement: {
        prototype: HTMLYduqsCardIntroElement;
        new (): HTMLYduqsCardIntroElement;
    };
    interface HTMLYduqsCardModuloElement extends Components.YduqsCardModulo, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloElement: {
        prototype: HTMLYduqsCardModuloElement;
        new (): HTMLYduqsCardModuloElement;
    };
    interface HTMLYduqsCardModuloBodyElement extends Components.YduqsCardModuloBody, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloBodyElement: {
        prototype: HTMLYduqsCardModuloBodyElement;
        new (): HTMLYduqsCardModuloBodyElement;
    };
    interface HTMLYduqsCardModuloFooterElement extends Components.YduqsCardModuloFooter, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloFooterElement: {
        prototype: HTMLYduqsCardModuloFooterElement;
        new (): HTMLYduqsCardModuloFooterElement;
    };
    interface HTMLYduqsCardModuloHeaderElement extends Components.YduqsCardModuloHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloHeaderElement: {
        prototype: HTMLYduqsCardModuloHeaderElement;
        new (): HTMLYduqsCardModuloHeaderElement;
    };
    interface HTMLYduqsCardSelecionavelElement extends Components.YduqsCardSelecionavel, HTMLStencilElement {
    }
    var HTMLYduqsCardSelecionavelElement: {
        prototype: HTMLYduqsCardSelecionavelElement;
        new (): HTMLYduqsCardSelecionavelElement;
    };
    interface HTMLYduqsCardSelecionavelItemElement extends Components.YduqsCardSelecionavelItem, HTMLStencilElement {
    }
    var HTMLYduqsCardSelecionavelItemElement: {
        prototype: HTMLYduqsCardSelecionavelItemElement;
        new (): HTMLYduqsCardSelecionavelItemElement;
    };
    interface HTMLYduqsCardVideoElement extends Components.YduqsCardVideo, HTMLStencilElement {
    }
    var HTMLYduqsCardVideoElement: {
        prototype: HTMLYduqsCardVideoElement;
        new (): HTMLYduqsCardVideoElement;
    };
    interface HTMLYduqsCarouselElement extends Components.YduqsCarousel, HTMLStencilElement {
    }
    var HTMLYduqsCarouselElement: {
        prototype: HTMLYduqsCarouselElement;
        new (): HTMLYduqsCarouselElement;
    };
    interface HTMLYduqsCarouselItemElement extends Components.YduqsCarouselItem, HTMLStencilElement {
    }
    var HTMLYduqsCarouselItemElement: {
        prototype: HTMLYduqsCarouselItemElement;
        new (): HTMLYduqsCarouselItemElement;
    };
    interface HTMLYduqsCodeCompilerElement extends Components.YduqsCodeCompiler, HTMLStencilElement {
    }
    var HTMLYduqsCodeCompilerElement: {
        prototype: HTMLYduqsCodeCompilerElement;
        new (): HTMLYduqsCodeCompilerElement;
    };
    interface HTMLYduqsCodeSnipetElement extends Components.YduqsCodeSnipet, HTMLStencilElement {
    }
    var HTMLYduqsCodeSnipetElement: {
        prototype: HTMLYduqsCodeSnipetElement;
        new (): HTMLYduqsCodeSnipetElement;
    };
    interface HTMLYduqsCollapseElement extends Components.YduqsCollapse, HTMLStencilElement {
    }
    var HTMLYduqsCollapseElement: {
        prototype: HTMLYduqsCollapseElement;
        new (): HTMLYduqsCollapseElement;
    };
    interface HTMLYduqsCollapseContentElement extends Components.YduqsCollapseContent, HTMLStencilElement {
    }
    var HTMLYduqsCollapseContentElement: {
        prototype: HTMLYduqsCollapseContentElement;
        new (): HTMLYduqsCollapseContentElement;
    };
    interface HTMLYduqsCollapseTeoriaElement extends Components.YduqsCollapseTeoria, HTMLStencilElement {
    }
    var HTMLYduqsCollapseTeoriaElement: {
        prototype: HTMLYduqsCollapseTeoriaElement;
        new (): HTMLYduqsCollapseTeoriaElement;
    };
    interface HTMLYduqsCollapseTeoriaContentElement extends Components.YduqsCollapseTeoriaContent, HTMLStencilElement {
    }
    var HTMLYduqsCollapseTeoriaContentElement: {
        prototype: HTMLYduqsCollapseTeoriaContentElement;
        new (): HTMLYduqsCollapseTeoriaContentElement;
    };
    interface HTMLYduqsCoverElement extends Components.YduqsCover, HTMLStencilElement {
    }
    var HTMLYduqsCoverElement: {
        prototype: HTMLYduqsCoverElement;
        new (): HTMLYduqsCoverElement;
    };
    interface HTMLYduqsDestaqueTextoElement extends Components.YduqsDestaqueTexto, HTMLStencilElement {
    }
    var HTMLYduqsDestaqueTextoElement: {
        prototype: HTMLYduqsDestaqueTextoElement;
        new (): HTMLYduqsDestaqueTextoElement;
    };
    interface HTMLYduqsDropdownElement extends Components.YduqsDropdown, HTMLStencilElement {
    }
    var HTMLYduqsDropdownElement: {
        prototype: HTMLYduqsDropdownElement;
        new (): HTMLYduqsDropdownElement;
    };
    interface HTMLYduqsFooterElement extends Components.YduqsFooter, HTMLStencilElement {
    }
    var HTMLYduqsFooterElement: {
        prototype: HTMLYduqsFooterElement;
        new (): HTMLYduqsFooterElement;
    };
    interface HTMLYduqsGalleryVideoElement extends Components.YduqsGalleryVideo, HTMLStencilElement {
    }
    var HTMLYduqsGalleryVideoElement: {
        prototype: HTMLYduqsGalleryVideoElement;
        new (): HTMLYduqsGalleryVideoElement;
    };
    interface HTMLYduqsImageElement extends Components.YduqsImage, HTMLStencilElement {
    }
    var HTMLYduqsImageElement: {
        prototype: HTMLYduqsImageElement;
        new (): HTMLYduqsImageElement;
    };
    interface HTMLYduqsInputElement extends Components.YduqsInput, HTMLStencilElement {
    }
    var HTMLYduqsInputElement: {
        prototype: HTMLYduqsInputElement;
        new (): HTMLYduqsInputElement;
    };
    interface HTMLYduqsListasElement extends Components.YduqsListas, HTMLStencilElement {
    }
    var HTMLYduqsListasElement: {
        prototype: HTMLYduqsListasElement;
        new (): HTMLYduqsListasElement;
    };
    interface HTMLYduqsLoaderElement extends Components.YduqsLoader, HTMLStencilElement {
    }
    var HTMLYduqsLoaderElement: {
        prototype: HTMLYduqsLoaderElement;
        new (): HTMLYduqsLoaderElement;
    };
    interface HTMLYduqsLoadingElement extends Components.YduqsLoading, HTMLStencilElement {
    }
    var HTMLYduqsLoadingElement: {
        prototype: HTMLYduqsLoadingElement;
        new (): HTMLYduqsLoadingElement;
    };
    interface HTMLYduqsMenuElement extends Components.YduqsMenu, HTMLStencilElement {
    }
    var HTMLYduqsMenuElement: {
        prototype: HTMLYduqsMenuElement;
        new (): HTMLYduqsMenuElement;
    };
    interface HTMLYduqsModalElement extends Components.YduqsModal, HTMLStencilElement {
    }
    var HTMLYduqsModalElement: {
        prototype: HTMLYduqsModalElement;
        new (): HTMLYduqsModalElement;
    };
    interface HTMLYduqsModuleCoverElement extends Components.YduqsModuleCover, HTMLStencilElement {
    }
    var HTMLYduqsModuleCoverElement: {
        prototype: HTMLYduqsModuleCoverElement;
        new (): HTMLYduqsModuleCoverElement;
    };
    interface HTMLYduqsModuleRatingElement extends Components.YduqsModuleRating, HTMLStencilElement {
    }
    var HTMLYduqsModuleRatingElement: {
        prototype: HTMLYduqsModuleRatingElement;
        new (): HTMLYduqsModuleRatingElement;
    };
    interface HTMLYduqsModuleVideoElement extends Components.YduqsModuleVideo, HTMLStencilElement {
    }
    var HTMLYduqsModuleVideoElement: {
        prototype: HTMLYduqsModuleVideoElement;
        new (): HTMLYduqsModuleVideoElement;
    };
    interface HTMLYduqsNotificationElement extends Components.YduqsNotification, HTMLStencilElement {
    }
    var HTMLYduqsNotificationElement: {
        prototype: HTMLYduqsNotificationElement;
        new (): HTMLYduqsNotificationElement;
    };
    interface HTMLYduqsNotificationsElement extends Components.YduqsNotifications, HTMLStencilElement {
    }
    var HTMLYduqsNotificationsElement: {
        prototype: HTMLYduqsNotificationsElement;
        new (): HTMLYduqsNotificationsElement;
    };
    interface HTMLYduqsPlaylistVideoElement extends Components.YduqsPlaylistVideo, HTMLStencilElement {
    }
    var HTMLYduqsPlaylistVideoElement: {
        prototype: HTMLYduqsPlaylistVideoElement;
        new (): HTMLYduqsPlaylistVideoElement;
    };
    interface HTMLYduqsPodcastElement extends Components.YduqsPodcast, HTMLStencilElement {
    }
    var HTMLYduqsPodcastElement: {
        prototype: HTMLYduqsPodcastElement;
        new (): HTMLYduqsPodcastElement;
    };
    interface HTMLYduqsProgressBarElement extends Components.YduqsProgressBar, HTMLStencilElement {
    }
    var HTMLYduqsProgressBarElement: {
        prototype: HTMLYduqsProgressBarElement;
        new (): HTMLYduqsProgressBarElement;
    };
    interface HTMLYduqsQuestionsElement extends Components.YduqsQuestions, HTMLStencilElement {
    }
    var HTMLYduqsQuestionsElement: {
        prototype: HTMLYduqsQuestionsElement;
        new (): HTMLYduqsQuestionsElement;
    };
    interface HTMLYduqsQuoteElement extends Components.YduqsQuote, HTMLStencilElement {
    }
    var HTMLYduqsQuoteElement: {
        prototype: HTMLYduqsQuoteElement;
        new (): HTMLYduqsQuoteElement;
    };
    interface HTMLYduqsQuoteBodyElement extends Components.YduqsQuoteBody, HTMLStencilElement {
    }
    var HTMLYduqsQuoteBodyElement: {
        prototype: HTMLYduqsQuoteBodyElement;
        new (): HTMLYduqsQuoteBodyElement;
    };
    interface HTMLYduqsQuoteImageElement extends Components.YduqsQuoteImage, HTMLStencilElement {
    }
    var HTMLYduqsQuoteImageElement: {
        prototype: HTMLYduqsQuoteImageElement;
        new (): HTMLYduqsQuoteImageElement;
    };
    interface HTMLYduqsRatingElement extends Components.YduqsRating, HTMLStencilElement {
    }
    var HTMLYduqsRatingElement: {
        prototype: HTMLYduqsRatingElement;
        new (): HTMLYduqsRatingElement;
    };
    interface HTMLYduqsTabElement extends Components.YduqsTab, HTMLStencilElement {
    }
    var HTMLYduqsTabElement: {
        prototype: HTMLYduqsTabElement;
        new (): HTMLYduqsTabElement;
    };
    interface HTMLYduqsTabsElement extends Components.YduqsTabs, HTMLStencilElement {
    }
    var HTMLYduqsTabsElement: {
        prototype: HTMLYduqsTabsElement;
        new (): HTMLYduqsTabsElement;
    };
    interface HTMLYduqsTagElement extends Components.YduqsTag, HTMLStencilElement {
    }
    var HTMLYduqsTagElement: {
        prototype: HTMLYduqsTagElement;
        new (): HTMLYduqsTagElement;
    };
    interface HTMLYduqsTagsElement extends Components.YduqsTags, HTMLStencilElement {
    }
    var HTMLYduqsTagsElement: {
        prototype: HTMLYduqsTagsElement;
        new (): HTMLYduqsTagsElement;
    };
    interface HTMLYduqsTeoriaElement extends Components.YduqsTeoria, HTMLStencilElement {
    }
    var HTMLYduqsTeoriaElement: {
        prototype: HTMLYduqsTeoriaElement;
        new (): HTMLYduqsTeoriaElement;
    };
    interface HTMLYduqsTextareaElement extends Components.YduqsTextarea, HTMLStencilElement {
    }
    var HTMLYduqsTextareaElement: {
        prototype: HTMLYduqsTextareaElement;
        new (): HTMLYduqsTextareaElement;
    };
    interface HTMLYduqsTimelineElement extends Components.YduqsTimeline, HTMLStencilElement {
    }
    var HTMLYduqsTimelineElement: {
        prototype: HTMLYduqsTimelineElement;
        new (): HTMLYduqsTimelineElement;
    };
    interface HTMLYduqsTimelineItemElement extends Components.YduqsTimelineItem, HTMLStencilElement {
    }
    var HTMLYduqsTimelineItemElement: {
        prototype: HTMLYduqsTimelineItemElement;
        new (): HTMLYduqsTimelineItemElement;
    };
    interface HTMLYduqsTitleElement extends Components.YduqsTitle, HTMLStencilElement {
    }
    var HTMLYduqsTitleElement: {
        prototype: HTMLYduqsTitleElement;
        new (): HTMLYduqsTitleElement;
    };
    interface HTMLYduqsToggleElement extends Components.YduqsToggle, HTMLStencilElement {
    }
    var HTMLYduqsToggleElement: {
        prototype: HTMLYduqsToggleElement;
        new (): HTMLYduqsToggleElement;
    };
    interface HTMLYduqsVideoPlayerElement extends Components.YduqsVideoPlayer, HTMLStencilElement {
    }
    var HTMLYduqsVideoPlayerElement: {
        prototype: HTMLYduqsVideoPlayerElement;
        new (): HTMLYduqsVideoPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "my-stace": HTMLMyStaceElement;
        "stace-editor": HTMLStaceEditorElement;
        "yduqs-accordion": HTMLYduqsAccordionElement;
        "yduqs-accordion-pane": HTMLYduqsAccordionPaneElement;
        "yduqs-atividade-discursiva": HTMLYduqsAtividadeDiscursivaElement;
        "yduqs-audio-card": HTMLYduqsAudioCardElement;
        "yduqs-audio-player": HTMLYduqsAudioPlayerElement;
        "yduqs-before-after": HTMLYduqsBeforeAfterElement;
        "yduqs-caixa-formula": HTMLYduqsCaixaFormulaElement;
        "yduqs-card": HTMLYduqsCardElement;
        "yduqs-card-body": HTMLYduqsCardBodyElement;
        "yduqs-card-comparativo": HTMLYduqsCardComparativoElement;
        "yduqs-card-comparativo-body": HTMLYduqsCardComparativoBodyElement;
        "yduqs-card-comparativo-header": HTMLYduqsCardComparativoHeaderElement;
        "yduqs-card-comparativo-item": HTMLYduqsCardComparativoItemElement;
        "yduqs-card-destaque": HTMLYduqsCardDestaqueElement;
        "yduqs-card-destaque-body": HTMLYduqsCardDestaqueBodyElement;
        "yduqs-card-destaque-header": HTMLYduqsCardDestaqueHeaderElement;
        "yduqs-card-footer": HTMLYduqsCardFooterElement;
        "yduqs-card-header": HTMLYduqsCardHeaderElement;
        "yduqs-card-horizontal": HTMLYduqsCardHorizontalElement;
        "yduqs-card-intro": HTMLYduqsCardIntroElement;
        "yduqs-card-modulo": HTMLYduqsCardModuloElement;
        "yduqs-card-modulo-body": HTMLYduqsCardModuloBodyElement;
        "yduqs-card-modulo-footer": HTMLYduqsCardModuloFooterElement;
        "yduqs-card-modulo-header": HTMLYduqsCardModuloHeaderElement;
        "yduqs-card-selecionavel": HTMLYduqsCardSelecionavelElement;
        "yduqs-card-selecionavel-item": HTMLYduqsCardSelecionavelItemElement;
        "yduqs-card-video": HTMLYduqsCardVideoElement;
        "yduqs-carousel": HTMLYduqsCarouselElement;
        "yduqs-carousel-item": HTMLYduqsCarouselItemElement;
        "yduqs-code-compiler": HTMLYduqsCodeCompilerElement;
        "yduqs-code-snipet": HTMLYduqsCodeSnipetElement;
        "yduqs-collapse": HTMLYduqsCollapseElement;
        "yduqs-collapse-content": HTMLYduqsCollapseContentElement;
        "yduqs-collapse-teoria": HTMLYduqsCollapseTeoriaElement;
        "yduqs-collapse-teoria-content": HTMLYduqsCollapseTeoriaContentElement;
        "yduqs-cover": HTMLYduqsCoverElement;
        "yduqs-destaque-texto": HTMLYduqsDestaqueTextoElement;
        "yduqs-dropdown": HTMLYduqsDropdownElement;
        "yduqs-footer": HTMLYduqsFooterElement;
        "yduqs-gallery-video": HTMLYduqsGalleryVideoElement;
        "yduqs-image": HTMLYduqsImageElement;
        "yduqs-input": HTMLYduqsInputElement;
        "yduqs-listas": HTMLYduqsListasElement;
        "yduqs-loader": HTMLYduqsLoaderElement;
        "yduqs-loading": HTMLYduqsLoadingElement;
        "yduqs-menu": HTMLYduqsMenuElement;
        "yduqs-modal": HTMLYduqsModalElement;
        "yduqs-module-cover": HTMLYduqsModuleCoverElement;
        "yduqs-module-rating": HTMLYduqsModuleRatingElement;
        "yduqs-module-video": HTMLYduqsModuleVideoElement;
        "yduqs-notification": HTMLYduqsNotificationElement;
        "yduqs-notifications": HTMLYduqsNotificationsElement;
        "yduqs-playlist-video": HTMLYduqsPlaylistVideoElement;
        "yduqs-podcast": HTMLYduqsPodcastElement;
        "yduqs-progress-bar": HTMLYduqsProgressBarElement;
        "yduqs-questions": HTMLYduqsQuestionsElement;
        "yduqs-quote": HTMLYduqsQuoteElement;
        "yduqs-quote-body": HTMLYduqsQuoteBodyElement;
        "yduqs-quote-image": HTMLYduqsQuoteImageElement;
        "yduqs-rating": HTMLYduqsRatingElement;
        "yduqs-tab": HTMLYduqsTabElement;
        "yduqs-tabs": HTMLYduqsTabsElement;
        "yduqs-tag": HTMLYduqsTagElement;
        "yduqs-tags": HTMLYduqsTagsElement;
        "yduqs-teoria": HTMLYduqsTeoriaElement;
        "yduqs-textarea": HTMLYduqsTextareaElement;
        "yduqs-timeline": HTMLYduqsTimelineElement;
        "yduqs-timeline-item": HTMLYduqsTimelineItemElement;
        "yduqs-title": HTMLYduqsTitleElement;
        "yduqs-toggle": HTMLYduqsToggleElement;
        "yduqs-video-player": HTMLYduqsVideoPlayerElement;
    }
}
declare namespace LocalJSX {
    interface MyStace {
        "autoUpdateContent"?: boolean;
        "durationBeforeCallback"?: number;
        "mode"?: string;
        "onChangeText"?: (event: CustomEvent<any>) => void;
        "options"?: any;
        "readOnly"?: boolean;
        "text"?: string;
        "theme"?: string;
        "timeoutSaving"?: any;
    }
    interface StaceEditor {
        "autoUpdateContent"?: boolean;
        "durationBeforeCallback"?: number;
        "mode"?: string;
        "onTextChange"?: (event: CustomEvent<any>) => void;
        "options"?: any;
        "readOnly"?: boolean;
        "text"?: string;
        "theme"?: string;
        "timeoutSaving"?: any;
    }
    interface YduqsAccordion {
        "outline"?: boolean;
    }
    interface YduqsAccordionPane {
        "onTogglepane"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface YduqsAtividadeDiscursiva {
    }
    interface YduqsAudioCard {
        "audiocard_id"?: string;
        "dark"?: boolean;
        "equal_height"?: boolean;
        "group"?: boolean;
        "outlined"?: boolean;
        "src"?: string;
        "subtitle_audio_card"?: string;
        "title_audio_card"?: string;
    }
    interface YduqsAudioPlayer {
        "audio_id"?: string;
        "dark"?: boolean;
        "onUpdateRate"?: (event: CustomEvent<number>) => void;
        "rate"?: number;
        "settings"?: YduqsAudioPlayerModel;
        "shortdisplay"?: boolean;
        "src"?: string;
    }
    interface YduqsBeforeAfter {
        "after_img"?: string;
        "after_img_alt"?: string;
        "after_img_title"?: string;
        "before_img"?: string;
        "before_img_alt"?: string;
        "before_img_title"?: string;
        "caption"?: string;
    }
    interface YduqsCaixaFormula {
        "dark"?: boolean;
        "equal_height"?: boolean;
        "formula"?: string;
        "rotate_info"?: boolean;
        "title_formula"?: string;
    }
    interface YduqsCard {
        "dark"?: boolean;
        "equal_height"?: boolean;
        "outlined"?: boolean;
    }
    interface YduqsCardBody {
    }
    interface YduqsCardComparativo {
        "dark"?: boolean;
        "icon"?: string;
        "outline"?: boolean;
        "rotate_mobile"?: boolean;
    }
    interface YduqsCardComparativoBody {
    }
    interface YduqsCardComparativoHeader {
    }
    interface YduqsCardComparativoItem {
    }
    interface YduqsCardDestaque {
        "grade"?: number;
        "icon"?: string;
        "outline"?: boolean;
    }
    interface YduqsCardDestaqueBody {
    }
    interface YduqsCardDestaqueHeader {
    }
    interface YduqsCardFooter {
    }
    interface YduqsCardHeader {
    }
    interface YduqsCardHorizontal {
        "card_icon"?: string;
        "card_image"?: string;
        "english"?: boolean;
        "image_alt"?: string;
        "image_title"?: string;
        "isquestion"?: boolean;
        "spanish"?: boolean;
    }
    interface YduqsCardIntro {
        "text"?: string;
    }
    interface YduqsCardModulo {
        "onChanged"?: (event: CustomEvent<any>) => void;
        "progress"?: number;
    }
    interface YduqsCardModuloBody {
    }
    interface YduqsCardModuloFooter {
    }
    interface YduqsCardModuloHeader {
    }
    interface YduqsCardSelecionavel {
        "onSelected"?: (event: CustomEvent<any>) => void;
    }
    interface YduqsCardSelecionavelItem {
        "disabled"?: boolean;
        "onOnselect"?: (event: CustomEvent<any>) => void;
        "optionid"?: string;
        "selected"?: boolean;
    }
    interface YduqsCardVideo {
        "active"?: boolean;
        "border_bottom"?: boolean;
        "link_video"?: string;
        "paragraph"?: string;
        "subtitle_video"?: string;
        "thumb_video"?: string;
        "time"?: string;
        "title_video"?: string;
    }
    interface YduqsCarousel {
        "english"?: boolean;
        "onNextslide"?: (event: CustomEvent<any>) => void;
        "onPrevslide"?: (event: CustomEvent<any>) => void;
        "onUpdatepage"?: (event: CustomEvent<any>) => void;
        "space"?: number;
        "spanish"?: boolean;
    }
    interface YduqsCarouselItem {
    }
    interface YduqsCodeCompiler {
        "code"?: string;
        "dark"?: boolean;
        "exercise_title"?: string;
        "input_keyboard"?: string;
        "language_code"?: string;
    }
    interface YduqsCodeSnipet {
        "code"?: string;
        "dark"?: boolean;
        "input_keyboard"?: string;
        "language_code"?: string;
        "size"?: string;
    }
    interface YduqsCollapse {
        "border"?: boolean;
        "onToggle"?: (event: CustomEvent<any>) => void;
        "outline"?: boolean;
    }
    interface YduqsCollapseContent {
        "header"?: string;
        "onTogglepane"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "size"?: string;
    }
    interface YduqsCollapseTeoria {
        "border"?: boolean;
        "onToggle"?: (event: CustomEvent<any>) => void;
        "outline"?: boolean;
    }
    interface YduqsCollapseTeoriaContent {
        "header"?: string;
        "onTogglepane"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "size"?: string;
        "teoria"?: boolean;
    }
    interface YduqsCover {
        "avatar"?: Array<any>;
        "background_img"?: string;
        "background_img_title"?: string;
        "background_text"?: string;
        "background_text_mobile"?: string;
        "colaboradores_nome"?: Array<any>;
        "collaboration_text"?: string;
        "contributors"?: string;
        "cover_preparation"?: boolean;
        "english"?: boolean;
        "lg_title"?: boolean;
        "link"?: Array<any>;
        "names_clb"?: Array<any>;
        "names_prof"?: Array<any>;
        "professores"?: Array<any>;
        "spanish"?: boolean;
        "teacher"?: string;
        "teacher_avatar"?: string;
        "teacher_link"?: string;
        "template_anitta"?: boolean;
        "title_cover"?: string;
        "title_size"?: string;
        "xl_title"?: boolean;
    }
    interface YduqsDestaqueTexto {
        "size"?: string;
    }
    interface YduqsDropdown {
        "colunas"?: string;
        "identificador"?: string;
        "tipo"?: string;
    }
    interface YduqsFooter {
        "btnimprimir"?: boolean;
        "english"?: boolean;
        "hrefbtnprint"?: string;
        "namebtnimprimir"?: string;
        "spanish"?: boolean;
        "template_anitta"?: boolean;
        "useimage"?: boolean;
    }
    interface YduqsGalleryVideo {
        "english"?: boolean;
        "module_number"?: number;
        "paragraph_video"?: string;
        "settings"?: YduqsModulePlaylists;
        "spanish"?: boolean;
        "subtitle_gallery"?: string;
        "title_gallery"?: string;
        "title_video"?: string;
    }
    interface YduqsImage {
        "alt"?: string;
        "covered"?: boolean;
        "height"?: string;
        "img_title"?: string;
        "src"?: string;
        "width"?: string;
    }
    interface YduqsInput {
        "icon"?: any;
        "placeh"?: string;
        "titulo"?: string;
    }
    interface YduqsListas {
        "tamanho"?: string;
        "tipo"?: string;
    }
    interface YduqsLoader {
    }
    interface YduqsLoading {
        "message"?: string;
        "onClose"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface YduqsMenu {
        "english"?: boolean;
        "onChangemenudata"?: (event: CustomEvent<any>) => void;
        "onClickmenuitem"?: (event: CustomEvent<any>) => void;
        "position"?: number;
        "settings"?: YduqsMenuModel;
        "spanish"?: boolean;
    }
    interface YduqsModal {
        "isopen"?: boolean;
        "maxbodyheight"?: number;
        "onModalClosed"?: (event: CustomEvent<boolean>) => void;
    }
    interface YduqsModuleCover {
        "img_cover"?: string;
        "midia_time"?: string;
        "number_module"?: string;
        "objective"?: string;
        "read_time"?: string;
        "title_midia_time"?: string;
        "title_module"?: string;
        "title_read_time"?: string;
    }
    interface YduqsModuleRating {
        "cta"?: string;
        "english"?: boolean;
        "icon"?: string;
        "module"?: string;
        "spanish"?: boolean;
        "tamanho"?: string;
    }
    interface YduqsModuleVideo {
        "active_video"?: string;
        "module_icon"?: string;
        "module_number"?: number;
        "paragraph_video"?: string;
        "settings"?: YduqsModulePlaylists;
        "subtitle_gallery"?: string;
        "title_gallery"?: string;
        "title_video"?: string;
    }
    interface YduqsNotification {
        "dismissible"?: boolean;
        "onClose"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "type"?: string;
    }
    interface YduqsNotifications {
        "position"?: string;
    }
    interface YduqsPlaylistVideo {
        "module_number"?: number;
        "settings"?: YduqsModulesPlaylists;
    }
    interface YduqsPodcast {
        "audio"?: string;
        "dark"?: boolean;
        "subtitulo"?: string;
        "withtitle"?: boolean;
    }
    interface YduqsProgressBar {
        "displayValue"?: boolean;
        "max"?: number;
        "min"?: number;
        "onChangebar"?: (event: CustomEvent<any>) => void;
        "onHoverbar"?: (event: CustomEvent<any>) => void;
        "semirounded"?: boolean;
        "value"?: number;
    }
    interface YduqsQuestions {
        "colunalg"?: string;
        "english"?: boolean;
        "math"?: boolean;
        "math_advanced"?: boolean;
        "settings"?: YduqsQuestionsModel;
        "spanish"?: boolean;
    }
    interface YduqsQuote {
        "dark"?: boolean;
        "size"?: string;
    }
    interface YduqsQuoteBody {
    }
    interface YduqsQuoteImage {
        "path"?: string;
    }
    interface YduqsRating {
        "cta"?: string;
        "icon"?: string;
        "module"?: string;
        "tamanho"?: string;
    }
    interface YduqsTab {
        "disabled"?: boolean;
        "header"?: string;
        "open"?: boolean;
        "outline"?: string;
        "type"?: string;
    }
    interface YduqsTabs {
        "darkmode"?: boolean;
        "fixed_titles"?: boolean;
        "gtm_action"?: Array<String>;
        "gtm_category"?: Array<String>;
        "gtm_label"?: Array<String>;
        "icons"?: Array<String>;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "outlined"?: boolean;
    }
    interface YduqsTag {
        "color"?: string;
    }
    interface YduqsTags {
    }
    interface YduqsTeoria {
    }
    interface YduqsTextarea {
        "bgfeedbackdark"?: boolean;
        "colunaslg"?: number;
        "colunasmd"?: number;
        "idbtn"?: string;
        "idtxt"?: string;
        "ligthtxtarea"?: boolean;
        "outlinetxtarea"?: boolean;
        "placeholder"?: string;
        "withbtn"?: boolean;
    }
    interface YduqsTimeline {
        "dark"?: boolean;
        "horizontal"?: boolean;
    }
    interface YduqsTimelineItem {
        "icon"?: string;
        "last"?: boolean;
    }
    interface YduqsTitle {
        "dark"?: boolean;
        "topic_icon"?: string;
        "topic_title"?: string;
    }
    interface YduqsToggle {
        "disable"?: boolean;
        "onMyToggleEmit"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "teste"?: String;
    }
    interface YduqsVideoPlayer {
        "bgcolor"?: string;
        "covered"?: boolean;
        "height"?: string;
        "src"?: string;
        "videoId"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "my-stace": MyStace;
        "stace-editor": StaceEditor;
        "yduqs-accordion": YduqsAccordion;
        "yduqs-accordion-pane": YduqsAccordionPane;
        "yduqs-atividade-discursiva": YduqsAtividadeDiscursiva;
        "yduqs-audio-card": YduqsAudioCard;
        "yduqs-audio-player": YduqsAudioPlayer;
        "yduqs-before-after": YduqsBeforeAfter;
        "yduqs-caixa-formula": YduqsCaixaFormula;
        "yduqs-card": YduqsCard;
        "yduqs-card-body": YduqsCardBody;
        "yduqs-card-comparativo": YduqsCardComparativo;
        "yduqs-card-comparativo-body": YduqsCardComparativoBody;
        "yduqs-card-comparativo-header": YduqsCardComparativoHeader;
        "yduqs-card-comparativo-item": YduqsCardComparativoItem;
        "yduqs-card-destaque": YduqsCardDestaque;
        "yduqs-card-destaque-body": YduqsCardDestaqueBody;
        "yduqs-card-destaque-header": YduqsCardDestaqueHeader;
        "yduqs-card-footer": YduqsCardFooter;
        "yduqs-card-header": YduqsCardHeader;
        "yduqs-card-horizontal": YduqsCardHorizontal;
        "yduqs-card-intro": YduqsCardIntro;
        "yduqs-card-modulo": YduqsCardModulo;
        "yduqs-card-modulo-body": YduqsCardModuloBody;
        "yduqs-card-modulo-footer": YduqsCardModuloFooter;
        "yduqs-card-modulo-header": YduqsCardModuloHeader;
        "yduqs-card-selecionavel": YduqsCardSelecionavel;
        "yduqs-card-selecionavel-item": YduqsCardSelecionavelItem;
        "yduqs-card-video": YduqsCardVideo;
        "yduqs-carousel": YduqsCarousel;
        "yduqs-carousel-item": YduqsCarouselItem;
        "yduqs-code-compiler": YduqsCodeCompiler;
        "yduqs-code-snipet": YduqsCodeSnipet;
        "yduqs-collapse": YduqsCollapse;
        "yduqs-collapse-content": YduqsCollapseContent;
        "yduqs-collapse-teoria": YduqsCollapseTeoria;
        "yduqs-collapse-teoria-content": YduqsCollapseTeoriaContent;
        "yduqs-cover": YduqsCover;
        "yduqs-destaque-texto": YduqsDestaqueTexto;
        "yduqs-dropdown": YduqsDropdown;
        "yduqs-footer": YduqsFooter;
        "yduqs-gallery-video": YduqsGalleryVideo;
        "yduqs-image": YduqsImage;
        "yduqs-input": YduqsInput;
        "yduqs-listas": YduqsListas;
        "yduqs-loader": YduqsLoader;
        "yduqs-loading": YduqsLoading;
        "yduqs-menu": YduqsMenu;
        "yduqs-modal": YduqsModal;
        "yduqs-module-cover": YduqsModuleCover;
        "yduqs-module-rating": YduqsModuleRating;
        "yduqs-module-video": YduqsModuleVideo;
        "yduqs-notification": YduqsNotification;
        "yduqs-notifications": YduqsNotifications;
        "yduqs-playlist-video": YduqsPlaylistVideo;
        "yduqs-podcast": YduqsPodcast;
        "yduqs-progress-bar": YduqsProgressBar;
        "yduqs-questions": YduqsQuestions;
        "yduqs-quote": YduqsQuote;
        "yduqs-quote-body": YduqsQuoteBody;
        "yduqs-quote-image": YduqsQuoteImage;
        "yduqs-rating": YduqsRating;
        "yduqs-tab": YduqsTab;
        "yduqs-tabs": YduqsTabs;
        "yduqs-tag": YduqsTag;
        "yduqs-tags": YduqsTags;
        "yduqs-teoria": YduqsTeoria;
        "yduqs-textarea": YduqsTextarea;
        "yduqs-timeline": YduqsTimeline;
        "yduqs-timeline-item": YduqsTimelineItem;
        "yduqs-title": YduqsTitle;
        "yduqs-toggle": YduqsToggle;
        "yduqs-video-player": YduqsVideoPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-stace": LocalJSX.MyStace & JSXBase.HTMLAttributes<HTMLMyStaceElement>;
            "stace-editor": LocalJSX.StaceEditor & JSXBase.HTMLAttributes<HTMLStaceEditorElement>;
            "yduqs-accordion": LocalJSX.YduqsAccordion & JSXBase.HTMLAttributes<HTMLYduqsAccordionElement>;
            "yduqs-accordion-pane": LocalJSX.YduqsAccordionPane & JSXBase.HTMLAttributes<HTMLYduqsAccordionPaneElement>;
            "yduqs-atividade-discursiva": LocalJSX.YduqsAtividadeDiscursiva & JSXBase.HTMLAttributes<HTMLYduqsAtividadeDiscursivaElement>;
            "yduqs-audio-card": LocalJSX.YduqsAudioCard & JSXBase.HTMLAttributes<HTMLYduqsAudioCardElement>;
            "yduqs-audio-player": LocalJSX.YduqsAudioPlayer & JSXBase.HTMLAttributes<HTMLYduqsAudioPlayerElement>;
            "yduqs-before-after": LocalJSX.YduqsBeforeAfter & JSXBase.HTMLAttributes<HTMLYduqsBeforeAfterElement>;
            "yduqs-caixa-formula": LocalJSX.YduqsCaixaFormula & JSXBase.HTMLAttributes<HTMLYduqsCaixaFormulaElement>;
            "yduqs-card": LocalJSX.YduqsCard & JSXBase.HTMLAttributes<HTMLYduqsCardElement>;
            "yduqs-card-body": LocalJSX.YduqsCardBody & JSXBase.HTMLAttributes<HTMLYduqsCardBodyElement>;
            "yduqs-card-comparativo": LocalJSX.YduqsCardComparativo & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoElement>;
            "yduqs-card-comparativo-body": LocalJSX.YduqsCardComparativoBody & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoBodyElement>;
            "yduqs-card-comparativo-header": LocalJSX.YduqsCardComparativoHeader & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoHeaderElement>;
            "yduqs-card-comparativo-item": LocalJSX.YduqsCardComparativoItem & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoItemElement>;
            "yduqs-card-destaque": LocalJSX.YduqsCardDestaque & JSXBase.HTMLAttributes<HTMLYduqsCardDestaqueElement>;
            "yduqs-card-destaque-body": LocalJSX.YduqsCardDestaqueBody & JSXBase.HTMLAttributes<HTMLYduqsCardDestaqueBodyElement>;
            "yduqs-card-destaque-header": LocalJSX.YduqsCardDestaqueHeader & JSXBase.HTMLAttributes<HTMLYduqsCardDestaqueHeaderElement>;
            "yduqs-card-footer": LocalJSX.YduqsCardFooter & JSXBase.HTMLAttributes<HTMLYduqsCardFooterElement>;
            "yduqs-card-header": LocalJSX.YduqsCardHeader & JSXBase.HTMLAttributes<HTMLYduqsCardHeaderElement>;
            "yduqs-card-horizontal": LocalJSX.YduqsCardHorizontal & JSXBase.HTMLAttributes<HTMLYduqsCardHorizontalElement>;
            "yduqs-card-intro": LocalJSX.YduqsCardIntro & JSXBase.HTMLAttributes<HTMLYduqsCardIntroElement>;
            "yduqs-card-modulo": LocalJSX.YduqsCardModulo & JSXBase.HTMLAttributes<HTMLYduqsCardModuloElement>;
            "yduqs-card-modulo-body": LocalJSX.YduqsCardModuloBody & JSXBase.HTMLAttributes<HTMLYduqsCardModuloBodyElement>;
            "yduqs-card-modulo-footer": LocalJSX.YduqsCardModuloFooter & JSXBase.HTMLAttributes<HTMLYduqsCardModuloFooterElement>;
            "yduqs-card-modulo-header": LocalJSX.YduqsCardModuloHeader & JSXBase.HTMLAttributes<HTMLYduqsCardModuloHeaderElement>;
            "yduqs-card-selecionavel": LocalJSX.YduqsCardSelecionavel & JSXBase.HTMLAttributes<HTMLYduqsCardSelecionavelElement>;
            "yduqs-card-selecionavel-item": LocalJSX.YduqsCardSelecionavelItem & JSXBase.HTMLAttributes<HTMLYduqsCardSelecionavelItemElement>;
            "yduqs-card-video": LocalJSX.YduqsCardVideo & JSXBase.HTMLAttributes<HTMLYduqsCardVideoElement>;
            "yduqs-carousel": LocalJSX.YduqsCarousel & JSXBase.HTMLAttributes<HTMLYduqsCarouselElement>;
            "yduqs-carousel-item": LocalJSX.YduqsCarouselItem & JSXBase.HTMLAttributes<HTMLYduqsCarouselItemElement>;
            "yduqs-code-compiler": LocalJSX.YduqsCodeCompiler & JSXBase.HTMLAttributes<HTMLYduqsCodeCompilerElement>;
            "yduqs-code-snipet": LocalJSX.YduqsCodeSnipet & JSXBase.HTMLAttributes<HTMLYduqsCodeSnipetElement>;
            "yduqs-collapse": LocalJSX.YduqsCollapse & JSXBase.HTMLAttributes<HTMLYduqsCollapseElement>;
            "yduqs-collapse-content": LocalJSX.YduqsCollapseContent & JSXBase.HTMLAttributes<HTMLYduqsCollapseContentElement>;
            "yduqs-collapse-teoria": LocalJSX.YduqsCollapseTeoria & JSXBase.HTMLAttributes<HTMLYduqsCollapseTeoriaElement>;
            "yduqs-collapse-teoria-content": LocalJSX.YduqsCollapseTeoriaContent & JSXBase.HTMLAttributes<HTMLYduqsCollapseTeoriaContentElement>;
            "yduqs-cover": LocalJSX.YduqsCover & JSXBase.HTMLAttributes<HTMLYduqsCoverElement>;
            "yduqs-destaque-texto": LocalJSX.YduqsDestaqueTexto & JSXBase.HTMLAttributes<HTMLYduqsDestaqueTextoElement>;
            "yduqs-dropdown": LocalJSX.YduqsDropdown & JSXBase.HTMLAttributes<HTMLYduqsDropdownElement>;
            "yduqs-footer": LocalJSX.YduqsFooter & JSXBase.HTMLAttributes<HTMLYduqsFooterElement>;
            "yduqs-gallery-video": LocalJSX.YduqsGalleryVideo & JSXBase.HTMLAttributes<HTMLYduqsGalleryVideoElement>;
            "yduqs-image": LocalJSX.YduqsImage & JSXBase.HTMLAttributes<HTMLYduqsImageElement>;
            "yduqs-input": LocalJSX.YduqsInput & JSXBase.HTMLAttributes<HTMLYduqsInputElement>;
            "yduqs-listas": LocalJSX.YduqsListas & JSXBase.HTMLAttributes<HTMLYduqsListasElement>;
            "yduqs-loader": LocalJSX.YduqsLoader & JSXBase.HTMLAttributes<HTMLYduqsLoaderElement>;
            "yduqs-loading": LocalJSX.YduqsLoading & JSXBase.HTMLAttributes<HTMLYduqsLoadingElement>;
            "yduqs-menu": LocalJSX.YduqsMenu & JSXBase.HTMLAttributes<HTMLYduqsMenuElement>;
            "yduqs-modal": LocalJSX.YduqsModal & JSXBase.HTMLAttributes<HTMLYduqsModalElement>;
            "yduqs-module-cover": LocalJSX.YduqsModuleCover & JSXBase.HTMLAttributes<HTMLYduqsModuleCoverElement>;
            "yduqs-module-rating": LocalJSX.YduqsModuleRating & JSXBase.HTMLAttributes<HTMLYduqsModuleRatingElement>;
            "yduqs-module-video": LocalJSX.YduqsModuleVideo & JSXBase.HTMLAttributes<HTMLYduqsModuleVideoElement>;
            "yduqs-notification": LocalJSX.YduqsNotification & JSXBase.HTMLAttributes<HTMLYduqsNotificationElement>;
            "yduqs-notifications": LocalJSX.YduqsNotifications & JSXBase.HTMLAttributes<HTMLYduqsNotificationsElement>;
            "yduqs-playlist-video": LocalJSX.YduqsPlaylistVideo & JSXBase.HTMLAttributes<HTMLYduqsPlaylistVideoElement>;
            "yduqs-podcast": LocalJSX.YduqsPodcast & JSXBase.HTMLAttributes<HTMLYduqsPodcastElement>;
            "yduqs-progress-bar": LocalJSX.YduqsProgressBar & JSXBase.HTMLAttributes<HTMLYduqsProgressBarElement>;
            "yduqs-questions": LocalJSX.YduqsQuestions & JSXBase.HTMLAttributes<HTMLYduqsQuestionsElement>;
            "yduqs-quote": LocalJSX.YduqsQuote & JSXBase.HTMLAttributes<HTMLYduqsQuoteElement>;
            "yduqs-quote-body": LocalJSX.YduqsQuoteBody & JSXBase.HTMLAttributes<HTMLYduqsQuoteBodyElement>;
            "yduqs-quote-image": LocalJSX.YduqsQuoteImage & JSXBase.HTMLAttributes<HTMLYduqsQuoteImageElement>;
            "yduqs-rating": LocalJSX.YduqsRating & JSXBase.HTMLAttributes<HTMLYduqsRatingElement>;
            "yduqs-tab": LocalJSX.YduqsTab & JSXBase.HTMLAttributes<HTMLYduqsTabElement>;
            "yduqs-tabs": LocalJSX.YduqsTabs & JSXBase.HTMLAttributes<HTMLYduqsTabsElement>;
            "yduqs-tag": LocalJSX.YduqsTag & JSXBase.HTMLAttributes<HTMLYduqsTagElement>;
            "yduqs-tags": LocalJSX.YduqsTags & JSXBase.HTMLAttributes<HTMLYduqsTagsElement>;
            "yduqs-teoria": LocalJSX.YduqsTeoria & JSXBase.HTMLAttributes<HTMLYduqsTeoriaElement>;
            "yduqs-textarea": LocalJSX.YduqsTextarea & JSXBase.HTMLAttributes<HTMLYduqsTextareaElement>;
            "yduqs-timeline": LocalJSX.YduqsTimeline & JSXBase.HTMLAttributes<HTMLYduqsTimelineElement>;
            "yduqs-timeline-item": LocalJSX.YduqsTimelineItem & JSXBase.HTMLAttributes<HTMLYduqsTimelineItemElement>;
            "yduqs-title": LocalJSX.YduqsTitle & JSXBase.HTMLAttributes<HTMLYduqsTitleElement>;
            "yduqs-toggle": LocalJSX.YduqsToggle & JSXBase.HTMLAttributes<HTMLYduqsToggleElement>;
            "yduqs-video-player": LocalJSX.YduqsVideoPlayer & JSXBase.HTMLAttributes<HTMLYduqsVideoPlayerElement>;
        }
    }
}
