/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { YduqsActivityModel } from "./components/yduqs-activity/yduqs-activity.model";
import { YduqsMenuModel } from "./components/yduqs-menu/yduqs-menu.model";
import { YduqsQuestionsModel } from "./components/yduqs-questions/yduqs-questions.model";
export namespace Components {
    interface YduqsAccordion {
        "outline": boolean;
    }
    interface YduqsAccordionPane {
        "close": () => Promise<void>;
        "header": string;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface YduqsActivity {
        "activity_id": string;
        "initialize": (config: YduqsActivityModel) => Promise<void>;
        "settings": YduqsActivityModel;
    }
    interface YduqsAudioPlayer {
        "shortdisplay": boolean;
        "src": string;
    }
    interface YduqsBeforeAfter {
        "after_img": string;
        "after_img_alt": string;
        "after_img_title": string;
        "before_img": string;
        "before_img_alt": string;
        "before_img_title": string;
        "caption": string;
    }
    interface YduqsCard {
        "dark": boolean;
        "outlined": boolean;
    }
    interface YduqsCardBody {
    }
    interface YduqsCardComparativo {
        "dark": boolean;
        "outline": boolean;
    }
    interface YduqsCardComparativoBody {
    }
    interface YduqsCardComparativoHeader {
    }
    interface YduqsCardComparativoItem {
    }
    interface YduqsCardDestaque {
        "grade": number;
        "icon": string;
        "outline": boolean;
    }
    interface YduqsCardDestaqueBody {
    }
    interface YduqsCardDestaqueHeader {
    }
    interface YduqsCardFooter {
    }
    interface YduqsCardHeader {
    }
    interface YduqsCardIntro {
        "text": string;
    }
    interface YduqsCardModulo {
        "progress": number;
    }
    interface YduqsCardModuloBody {
    }
    interface YduqsCardModuloFooter {
    }
    interface YduqsCardModuloHeader {
    }
    interface YduqsCardSelecionavel {
    }
    interface YduqsCardSelecionavelItem {
        "disabled"?: boolean;
        "isSelected": () => Promise<boolean>;
        "optionid": string;
        "selectItem": () => Promise<void>;
        "selected": boolean;
        "unselectItem": () => Promise<void>;
    }
    interface YduqsCarousel {
        "next": () => Promise<void>;
        "prev": () => Promise<void>;
        "space": number;
    }
    interface YduqsCarouselItem {
    }
    interface YduqsCodeSnipet {
        "dark": boolean;
        "disable": boolean;
    }
    interface YduqsCollapse {
        "border": boolean;
    }
    interface YduqsCollapseContent {
        "close": () => Promise<void>;
        "header": string;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
        "size": string;
    }
    interface YduqsCover {
        "theme_background": string;
        "theme_cover_preparation": boolean;
        "theme_teacher": string;
        "theme_teacher_avatar": string;
        "theme_teacher_bg": boolean;
        "theme_title": string;
        "theme_title_bg": boolean;
    }
    interface YduqsDemo {
        "cor": string;
        "texto": string;
    }
    interface YduqsDropdown {
        "colsize": string;
    }
    interface YduqsFooter {
    }
    interface YduqsImage {
        "alt": string;
        "bgcolor": string;
        "covered": boolean;
        "height": string;
        "img_title": string;
        "src": string;
        "width": string;
    }
    interface YduqsInput {
        "alteraInput": (ev: any) => Promise<void>;
        "apagarValor": () => Promise<void>;
        "icon": any;
        "placeh": string;
        "titulo": string;
    }
    interface YduqsLoading {
        "hide": () => Promise<void>;
        "isOpen": () => Promise<boolean>;
        "message": string;
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface YduqsMediaBody {
    }
    interface YduqsMediaImage {
        "alt": string;
        "src": string;
    }
    interface YduqsMediaItem {
    }
    interface YduqsMenu {
        "initialize": (config: YduqsMenuModel) => Promise<void>;
        "settings": YduqsMenuModel;
    }
    interface YduqsModal {
        "isopen": boolean;
        "maxbodyheight": number;
        "showModal": () => Promise<void>;
    }
    interface YduqsModuleCover {
        "img_cover": string;
        "midia_time": string;
        "number_module": string;
        "objective": string;
        "read_time": string;
        "title_midia_time": string;
        "title_module": string;
        "title_read_time": string;
    }
    interface YduqsNotification {
        "close": () => Promise<void>;
        "dismissible": boolean;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
        "type": string;
    }
    interface YduqsNotifications {
        "position": string;
    }
    interface YduqsProgress {
        "rounded": boolean;
        "semirounded": boolean;
    }
    interface YduqsProgressBar {
        "displayValue": boolean;
        "hide": () => Promise<void>;
        "isValueVisible": () => Promise<boolean>;
        "max": number;
        "min": number;
        "semirounded": boolean;
        "show": () => Promise<void>;
        "value": number;
    }
    interface YduqsQuestions {
        "initialize": (config: YduqsQuestionsModel) => Promise<void>;
        "question_id": string;
        "settings": YduqsQuestionsModel;
    }
    interface YduqsQuote {
        "dark": boolean;
        "size": string;
    }
    interface YduqsQuoteBody {
    }
    interface YduqsQuoteImage {
        "path": string;
    }
    interface YduqsRating {
        "avaliar": () => Promise<void>;
        "cta": string;
    }
    interface YduqsSectionCover {
        "section_icon": string;
        "section_image": string;
    }
    interface YduqsTab {
        "disabled": boolean;
        "header": string;
        "open": boolean;
        "type": string;
    }
    interface YduqsTabs {
        "currentTab": () => Promise<number>;
        "isdarkmode": boolean;
        "openTab": (tabIndex: number) => Promise<void>;
    }
    interface YduqsTag {
        "color": string;
    }
    interface YduqsTags {
    }
    interface YduqsTextarea {
        "cta": string;
        "placeholder": string;
        "txt_button": string;
    }
    interface YduqsTimeline {
        "dark": boolean;
        "horizontal": boolean;
    }
    interface YduqsTimelineItem {
        "icon": string;
        "last": boolean;
    }
    interface YduqsTitle {
        "dark": boolean;
        "topic_icon": string;
        "topic_title": string;
    }
    interface YduqsToggle {
        "disable": boolean;
        "open": boolean;
        "teste": String;
    }
    interface YduqsVideoPlayer {
        "bgcolor": string;
        "covered": boolean;
        "height": string;
        "src": string;
        "videoId": string;
        "width": string;
    }
}
declare global {
    interface HTMLYduqsAccordionElement extends Components.YduqsAccordion, HTMLStencilElement {
    }
    var HTMLYduqsAccordionElement: {
        prototype: HTMLYduqsAccordionElement;
        new (): HTMLYduqsAccordionElement;
    };
    interface HTMLYduqsAccordionPaneElement extends Components.YduqsAccordionPane, HTMLStencilElement {
    }
    var HTMLYduqsAccordionPaneElement: {
        prototype: HTMLYduqsAccordionPaneElement;
        new (): HTMLYduqsAccordionPaneElement;
    };
    interface HTMLYduqsActivityElement extends Components.YduqsActivity, HTMLStencilElement {
    }
    var HTMLYduqsActivityElement: {
        prototype: HTMLYduqsActivityElement;
        new (): HTMLYduqsActivityElement;
    };
    interface HTMLYduqsAudioPlayerElement extends Components.YduqsAudioPlayer, HTMLStencilElement {
    }
    var HTMLYduqsAudioPlayerElement: {
        prototype: HTMLYduqsAudioPlayerElement;
        new (): HTMLYduqsAudioPlayerElement;
    };
    interface HTMLYduqsBeforeAfterElement extends Components.YduqsBeforeAfter, HTMLStencilElement {
    }
    var HTMLYduqsBeforeAfterElement: {
        prototype: HTMLYduqsBeforeAfterElement;
        new (): HTMLYduqsBeforeAfterElement;
    };
    interface HTMLYduqsCardElement extends Components.YduqsCard, HTMLStencilElement {
    }
    var HTMLYduqsCardElement: {
        prototype: HTMLYduqsCardElement;
        new (): HTMLYduqsCardElement;
    };
    interface HTMLYduqsCardBodyElement extends Components.YduqsCardBody, HTMLStencilElement {
    }
    var HTMLYduqsCardBodyElement: {
        prototype: HTMLYduqsCardBodyElement;
        new (): HTMLYduqsCardBodyElement;
    };
    interface HTMLYduqsCardComparativoElement extends Components.YduqsCardComparativo, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoElement: {
        prototype: HTMLYduqsCardComparativoElement;
        new (): HTMLYduqsCardComparativoElement;
    };
    interface HTMLYduqsCardComparativoBodyElement extends Components.YduqsCardComparativoBody, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoBodyElement: {
        prototype: HTMLYduqsCardComparativoBodyElement;
        new (): HTMLYduqsCardComparativoBodyElement;
    };
    interface HTMLYduqsCardComparativoHeaderElement extends Components.YduqsCardComparativoHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoHeaderElement: {
        prototype: HTMLYduqsCardComparativoHeaderElement;
        new (): HTMLYduqsCardComparativoHeaderElement;
    };
    interface HTMLYduqsCardComparativoItemElement extends Components.YduqsCardComparativoItem, HTMLStencilElement {
    }
    var HTMLYduqsCardComparativoItemElement: {
        prototype: HTMLYduqsCardComparativoItemElement;
        new (): HTMLYduqsCardComparativoItemElement;
    };
    interface HTMLYduqsCardDestaqueElement extends Components.YduqsCardDestaque, HTMLStencilElement {
    }
    var HTMLYduqsCardDestaqueElement: {
        prototype: HTMLYduqsCardDestaqueElement;
        new (): HTMLYduqsCardDestaqueElement;
    };
    interface HTMLYduqsCardDestaqueBodyElement extends Components.YduqsCardDestaqueBody, HTMLStencilElement {
    }
    var HTMLYduqsCardDestaqueBodyElement: {
        prototype: HTMLYduqsCardDestaqueBodyElement;
        new (): HTMLYduqsCardDestaqueBodyElement;
    };
    interface HTMLYduqsCardDestaqueHeaderElement extends Components.YduqsCardDestaqueHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardDestaqueHeaderElement: {
        prototype: HTMLYduqsCardDestaqueHeaderElement;
        new (): HTMLYduqsCardDestaqueHeaderElement;
    };
    interface HTMLYduqsCardFooterElement extends Components.YduqsCardFooter, HTMLStencilElement {
    }
    var HTMLYduqsCardFooterElement: {
        prototype: HTMLYduqsCardFooterElement;
        new (): HTMLYduqsCardFooterElement;
    };
    interface HTMLYduqsCardHeaderElement extends Components.YduqsCardHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardHeaderElement: {
        prototype: HTMLYduqsCardHeaderElement;
        new (): HTMLYduqsCardHeaderElement;
    };
    interface HTMLYduqsCardIntroElement extends Components.YduqsCardIntro, HTMLStencilElement {
    }
    var HTMLYduqsCardIntroElement: {
        prototype: HTMLYduqsCardIntroElement;
        new (): HTMLYduqsCardIntroElement;
    };
    interface HTMLYduqsCardModuloElement extends Components.YduqsCardModulo, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloElement: {
        prototype: HTMLYduqsCardModuloElement;
        new (): HTMLYduqsCardModuloElement;
    };
    interface HTMLYduqsCardModuloBodyElement extends Components.YduqsCardModuloBody, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloBodyElement: {
        prototype: HTMLYduqsCardModuloBodyElement;
        new (): HTMLYduqsCardModuloBodyElement;
    };
    interface HTMLYduqsCardModuloFooterElement extends Components.YduqsCardModuloFooter, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloFooterElement: {
        prototype: HTMLYduqsCardModuloFooterElement;
        new (): HTMLYduqsCardModuloFooterElement;
    };
    interface HTMLYduqsCardModuloHeaderElement extends Components.YduqsCardModuloHeader, HTMLStencilElement {
    }
    var HTMLYduqsCardModuloHeaderElement: {
        prototype: HTMLYduqsCardModuloHeaderElement;
        new (): HTMLYduqsCardModuloHeaderElement;
    };
    interface HTMLYduqsCardSelecionavelElement extends Components.YduqsCardSelecionavel, HTMLStencilElement {
    }
    var HTMLYduqsCardSelecionavelElement: {
        prototype: HTMLYduqsCardSelecionavelElement;
        new (): HTMLYduqsCardSelecionavelElement;
    };
    interface HTMLYduqsCardSelecionavelItemElement extends Components.YduqsCardSelecionavelItem, HTMLStencilElement {
    }
    var HTMLYduqsCardSelecionavelItemElement: {
        prototype: HTMLYduqsCardSelecionavelItemElement;
        new (): HTMLYduqsCardSelecionavelItemElement;
    };
    interface HTMLYduqsCarouselElement extends Components.YduqsCarousel, HTMLStencilElement {
    }
    var HTMLYduqsCarouselElement: {
        prototype: HTMLYduqsCarouselElement;
        new (): HTMLYduqsCarouselElement;
    };
    interface HTMLYduqsCarouselItemElement extends Components.YduqsCarouselItem, HTMLStencilElement {
    }
    var HTMLYduqsCarouselItemElement: {
        prototype: HTMLYduqsCarouselItemElement;
        new (): HTMLYduqsCarouselItemElement;
    };
    interface HTMLYduqsCodeSnipetElement extends Components.YduqsCodeSnipet, HTMLStencilElement {
    }
    var HTMLYduqsCodeSnipetElement: {
        prototype: HTMLYduqsCodeSnipetElement;
        new (): HTMLYduqsCodeSnipetElement;
    };
    interface HTMLYduqsCollapseElement extends Components.YduqsCollapse, HTMLStencilElement {
    }
    var HTMLYduqsCollapseElement: {
        prototype: HTMLYduqsCollapseElement;
        new (): HTMLYduqsCollapseElement;
    };
    interface HTMLYduqsCollapseContentElement extends Components.YduqsCollapseContent, HTMLStencilElement {
    }
    var HTMLYduqsCollapseContentElement: {
        prototype: HTMLYduqsCollapseContentElement;
        new (): HTMLYduqsCollapseContentElement;
    };
    interface HTMLYduqsCoverElement extends Components.YduqsCover, HTMLStencilElement {
    }
    var HTMLYduqsCoverElement: {
        prototype: HTMLYduqsCoverElement;
        new (): HTMLYduqsCoverElement;
    };
    interface HTMLYduqsDemoElement extends Components.YduqsDemo, HTMLStencilElement {
    }
    var HTMLYduqsDemoElement: {
        prototype: HTMLYduqsDemoElement;
        new (): HTMLYduqsDemoElement;
    };
    interface HTMLYduqsDropdownElement extends Components.YduqsDropdown, HTMLStencilElement {
    }
    var HTMLYduqsDropdownElement: {
        prototype: HTMLYduqsDropdownElement;
        new (): HTMLYduqsDropdownElement;
    };
    interface HTMLYduqsFooterElement extends Components.YduqsFooter, HTMLStencilElement {
    }
    var HTMLYduqsFooterElement: {
        prototype: HTMLYduqsFooterElement;
        new (): HTMLYduqsFooterElement;
    };
    interface HTMLYduqsImageElement extends Components.YduqsImage, HTMLStencilElement {
    }
    var HTMLYduqsImageElement: {
        prototype: HTMLYduqsImageElement;
        new (): HTMLYduqsImageElement;
    };
    interface HTMLYduqsInputElement extends Components.YduqsInput, HTMLStencilElement {
    }
    var HTMLYduqsInputElement: {
        prototype: HTMLYduqsInputElement;
        new (): HTMLYduqsInputElement;
    };
    interface HTMLYduqsLoadingElement extends Components.YduqsLoading, HTMLStencilElement {
    }
    var HTMLYduqsLoadingElement: {
        prototype: HTMLYduqsLoadingElement;
        new (): HTMLYduqsLoadingElement;
    };
    interface HTMLYduqsMediaBodyElement extends Components.YduqsMediaBody, HTMLStencilElement {
    }
    var HTMLYduqsMediaBodyElement: {
        prototype: HTMLYduqsMediaBodyElement;
        new (): HTMLYduqsMediaBodyElement;
    };
    interface HTMLYduqsMediaImageElement extends Components.YduqsMediaImage, HTMLStencilElement {
    }
    var HTMLYduqsMediaImageElement: {
        prototype: HTMLYduqsMediaImageElement;
        new (): HTMLYduqsMediaImageElement;
    };
    interface HTMLYduqsMediaItemElement extends Components.YduqsMediaItem, HTMLStencilElement {
    }
    var HTMLYduqsMediaItemElement: {
        prototype: HTMLYduqsMediaItemElement;
        new (): HTMLYduqsMediaItemElement;
    };
    interface HTMLYduqsMenuElement extends Components.YduqsMenu, HTMLStencilElement {
    }
    var HTMLYduqsMenuElement: {
        prototype: HTMLYduqsMenuElement;
        new (): HTMLYduqsMenuElement;
    };
    interface HTMLYduqsModalElement extends Components.YduqsModal, HTMLStencilElement {
    }
    var HTMLYduqsModalElement: {
        prototype: HTMLYduqsModalElement;
        new (): HTMLYduqsModalElement;
    };
    interface HTMLYduqsModuleCoverElement extends Components.YduqsModuleCover, HTMLStencilElement {
    }
    var HTMLYduqsModuleCoverElement: {
        prototype: HTMLYduqsModuleCoverElement;
        new (): HTMLYduqsModuleCoverElement;
    };
    interface HTMLYduqsNotificationElement extends Components.YduqsNotification, HTMLStencilElement {
    }
    var HTMLYduqsNotificationElement: {
        prototype: HTMLYduqsNotificationElement;
        new (): HTMLYduqsNotificationElement;
    };
    interface HTMLYduqsNotificationsElement extends Components.YduqsNotifications, HTMLStencilElement {
    }
    var HTMLYduqsNotificationsElement: {
        prototype: HTMLYduqsNotificationsElement;
        new (): HTMLYduqsNotificationsElement;
    };
    interface HTMLYduqsProgressElement extends Components.YduqsProgress, HTMLStencilElement {
    }
    var HTMLYduqsProgressElement: {
        prototype: HTMLYduqsProgressElement;
        new (): HTMLYduqsProgressElement;
    };
    interface HTMLYduqsProgressBarElement extends Components.YduqsProgressBar, HTMLStencilElement {
    }
    var HTMLYduqsProgressBarElement: {
        prototype: HTMLYduqsProgressBarElement;
        new (): HTMLYduqsProgressBarElement;
    };
    interface HTMLYduqsQuestionsElement extends Components.YduqsQuestions, HTMLStencilElement {
    }
    var HTMLYduqsQuestionsElement: {
        prototype: HTMLYduqsQuestionsElement;
        new (): HTMLYduqsQuestionsElement;
    };
    interface HTMLYduqsQuoteElement extends Components.YduqsQuote, HTMLStencilElement {
    }
    var HTMLYduqsQuoteElement: {
        prototype: HTMLYduqsQuoteElement;
        new (): HTMLYduqsQuoteElement;
    };
    interface HTMLYduqsQuoteBodyElement extends Components.YduqsQuoteBody, HTMLStencilElement {
    }
    var HTMLYduqsQuoteBodyElement: {
        prototype: HTMLYduqsQuoteBodyElement;
        new (): HTMLYduqsQuoteBodyElement;
    };
    interface HTMLYduqsQuoteImageElement extends Components.YduqsQuoteImage, HTMLStencilElement {
    }
    var HTMLYduqsQuoteImageElement: {
        prototype: HTMLYduqsQuoteImageElement;
        new (): HTMLYduqsQuoteImageElement;
    };
    interface HTMLYduqsRatingElement extends Components.YduqsRating, HTMLStencilElement {
    }
    var HTMLYduqsRatingElement: {
        prototype: HTMLYduqsRatingElement;
        new (): HTMLYduqsRatingElement;
    };
    interface HTMLYduqsSectionCoverElement extends Components.YduqsSectionCover, HTMLStencilElement {
    }
    var HTMLYduqsSectionCoverElement: {
        prototype: HTMLYduqsSectionCoverElement;
        new (): HTMLYduqsSectionCoverElement;
    };
    interface HTMLYduqsTabElement extends Components.YduqsTab, HTMLStencilElement {
    }
    var HTMLYduqsTabElement: {
        prototype: HTMLYduqsTabElement;
        new (): HTMLYduqsTabElement;
    };
    interface HTMLYduqsTabsElement extends Components.YduqsTabs, HTMLStencilElement {
    }
    var HTMLYduqsTabsElement: {
        prototype: HTMLYduqsTabsElement;
        new (): HTMLYduqsTabsElement;
    };
    interface HTMLYduqsTagElement extends Components.YduqsTag, HTMLStencilElement {
    }
    var HTMLYduqsTagElement: {
        prototype: HTMLYduqsTagElement;
        new (): HTMLYduqsTagElement;
    };
    interface HTMLYduqsTagsElement extends Components.YduqsTags, HTMLStencilElement {
    }
    var HTMLYduqsTagsElement: {
        prototype: HTMLYduqsTagsElement;
        new (): HTMLYduqsTagsElement;
    };
    interface HTMLYduqsTextareaElement extends Components.YduqsTextarea, HTMLStencilElement {
    }
    var HTMLYduqsTextareaElement: {
        prototype: HTMLYduqsTextareaElement;
        new (): HTMLYduqsTextareaElement;
    };
    interface HTMLYduqsTimelineElement extends Components.YduqsTimeline, HTMLStencilElement {
    }
    var HTMLYduqsTimelineElement: {
        prototype: HTMLYduqsTimelineElement;
        new (): HTMLYduqsTimelineElement;
    };
    interface HTMLYduqsTimelineItemElement extends Components.YduqsTimelineItem, HTMLStencilElement {
    }
    var HTMLYduqsTimelineItemElement: {
        prototype: HTMLYduqsTimelineItemElement;
        new (): HTMLYduqsTimelineItemElement;
    };
    interface HTMLYduqsTitleElement extends Components.YduqsTitle, HTMLStencilElement {
    }
    var HTMLYduqsTitleElement: {
        prototype: HTMLYduqsTitleElement;
        new (): HTMLYduqsTitleElement;
    };
    interface HTMLYduqsToggleElement extends Components.YduqsToggle, HTMLStencilElement {
    }
    var HTMLYduqsToggleElement: {
        prototype: HTMLYduqsToggleElement;
        new (): HTMLYduqsToggleElement;
    };
    interface HTMLYduqsVideoPlayerElement extends Components.YduqsVideoPlayer, HTMLStencilElement {
    }
    var HTMLYduqsVideoPlayerElement: {
        prototype: HTMLYduqsVideoPlayerElement;
        new (): HTMLYduqsVideoPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "yduqs-accordion": HTMLYduqsAccordionElement;
        "yduqs-accordion-pane": HTMLYduqsAccordionPaneElement;
        "yduqs-activity": HTMLYduqsActivityElement;
        "yduqs-audio-player": HTMLYduqsAudioPlayerElement;
        "yduqs-before-after": HTMLYduqsBeforeAfterElement;
        "yduqs-card": HTMLYduqsCardElement;
        "yduqs-card-body": HTMLYduqsCardBodyElement;
        "yduqs-card-comparativo": HTMLYduqsCardComparativoElement;
        "yduqs-card-comparativo-body": HTMLYduqsCardComparativoBodyElement;
        "yduqs-card-comparativo-header": HTMLYduqsCardComparativoHeaderElement;
        "yduqs-card-comparativo-item": HTMLYduqsCardComparativoItemElement;
        "yduqs-card-destaque": HTMLYduqsCardDestaqueElement;
        "yduqs-card-destaque-body": HTMLYduqsCardDestaqueBodyElement;
        "yduqs-card-destaque-header": HTMLYduqsCardDestaqueHeaderElement;
        "yduqs-card-footer": HTMLYduqsCardFooterElement;
        "yduqs-card-header": HTMLYduqsCardHeaderElement;
        "yduqs-card-intro": HTMLYduqsCardIntroElement;
        "yduqs-card-modulo": HTMLYduqsCardModuloElement;
        "yduqs-card-modulo-body": HTMLYduqsCardModuloBodyElement;
        "yduqs-card-modulo-footer": HTMLYduqsCardModuloFooterElement;
        "yduqs-card-modulo-header": HTMLYduqsCardModuloHeaderElement;
        "yduqs-card-selecionavel": HTMLYduqsCardSelecionavelElement;
        "yduqs-card-selecionavel-item": HTMLYduqsCardSelecionavelItemElement;
        "yduqs-carousel": HTMLYduqsCarouselElement;
        "yduqs-carousel-item": HTMLYduqsCarouselItemElement;
        "yduqs-code-snipet": HTMLYduqsCodeSnipetElement;
        "yduqs-collapse": HTMLYduqsCollapseElement;
        "yduqs-collapse-content": HTMLYduqsCollapseContentElement;
        "yduqs-cover": HTMLYduqsCoverElement;
        "yduqs-demo": HTMLYduqsDemoElement;
        "yduqs-dropdown": HTMLYduqsDropdownElement;
        "yduqs-footer": HTMLYduqsFooterElement;
        "yduqs-image": HTMLYduqsImageElement;
        "yduqs-input": HTMLYduqsInputElement;
        "yduqs-loading": HTMLYduqsLoadingElement;
        "yduqs-media-body": HTMLYduqsMediaBodyElement;
        "yduqs-media-image": HTMLYduqsMediaImageElement;
        "yduqs-media-item": HTMLYduqsMediaItemElement;
        "yduqs-menu": HTMLYduqsMenuElement;
        "yduqs-modal": HTMLYduqsModalElement;
        "yduqs-module-cover": HTMLYduqsModuleCoverElement;
        "yduqs-notification": HTMLYduqsNotificationElement;
        "yduqs-notifications": HTMLYduqsNotificationsElement;
        "yduqs-progress": HTMLYduqsProgressElement;
        "yduqs-progress-bar": HTMLYduqsProgressBarElement;
        "yduqs-questions": HTMLYduqsQuestionsElement;
        "yduqs-quote": HTMLYduqsQuoteElement;
        "yduqs-quote-body": HTMLYduqsQuoteBodyElement;
        "yduqs-quote-image": HTMLYduqsQuoteImageElement;
        "yduqs-rating": HTMLYduqsRatingElement;
        "yduqs-section-cover": HTMLYduqsSectionCoverElement;
        "yduqs-tab": HTMLYduqsTabElement;
        "yduqs-tabs": HTMLYduqsTabsElement;
        "yduqs-tag": HTMLYduqsTagElement;
        "yduqs-tags": HTMLYduqsTagsElement;
        "yduqs-textarea": HTMLYduqsTextareaElement;
        "yduqs-timeline": HTMLYduqsTimelineElement;
        "yduqs-timeline-item": HTMLYduqsTimelineItemElement;
        "yduqs-title": HTMLYduqsTitleElement;
        "yduqs-toggle": HTMLYduqsToggleElement;
        "yduqs-video-player": HTMLYduqsVideoPlayerElement;
    }
}
declare namespace LocalJSX {
    interface YduqsAccordion {
        "onToggle"?: (event: CustomEvent<any>) => void;
        "outline"?: boolean;
    }
    interface YduqsAccordionPane {
        "header"?: string;
        "onTogglepane"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface YduqsActivity {
        "activity_id"?: string;
        "settings"?: YduqsActivityModel;
    }
    interface YduqsAudioPlayer {
        "shortdisplay"?: boolean;
        "src"?: string;
    }
    interface YduqsBeforeAfter {
        "after_img"?: string;
        "after_img_alt"?: string;
        "after_img_title"?: string;
        "before_img"?: string;
        "before_img_alt"?: string;
        "before_img_title"?: string;
        "caption"?: string;
    }
    interface YduqsCard {
        "dark"?: boolean;
        "outlined"?: boolean;
    }
    interface YduqsCardBody {
    }
    interface YduqsCardComparativo {
        "dark"?: boolean;
        "outline"?: boolean;
    }
    interface YduqsCardComparativoBody {
    }
    interface YduqsCardComparativoHeader {
    }
    interface YduqsCardComparativoItem {
    }
    interface YduqsCardDestaque {
        "grade"?: number;
        "icon"?: string;
        "outline"?: boolean;
    }
    interface YduqsCardDestaqueBody {
    }
    interface YduqsCardDestaqueHeader {
    }
    interface YduqsCardFooter {
    }
    interface YduqsCardHeader {
    }
    interface YduqsCardIntro {
        "text"?: string;
    }
    interface YduqsCardModulo {
        "onChanged"?: (event: CustomEvent<any>) => void;
        "progress"?: number;
    }
    interface YduqsCardModuloBody {
    }
    interface YduqsCardModuloFooter {
    }
    interface YduqsCardModuloHeader {
    }
    interface YduqsCardSelecionavel {
        "onSelected"?: (event: CustomEvent<any>) => void;
    }
    interface YduqsCardSelecionavelItem {
        "disabled"?: boolean;
        "onOnselect"?: (event: CustomEvent<any>) => void;
        "optionid"?: string;
        "selected"?: boolean;
    }
    interface YduqsCarousel {
        "onNextslide"?: (event: CustomEvent<any>) => void;
        "onPrevslide"?: (event: CustomEvent<any>) => void;
        "onUpdatepage"?: (event: CustomEvent<any>) => void;
        "space"?: number;
    }
    interface YduqsCarouselItem {
    }
    interface YduqsCodeSnipet {
        "dark"?: boolean;
        "disable"?: boolean;
    }
    interface YduqsCollapse {
        "border"?: boolean;
        "onToggle"?: (event: CustomEvent<any>) => void;
    }
    interface YduqsCollapseContent {
        "header"?: string;
        "onTogglepane"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "size"?: string;
    }
    interface YduqsCover {
        "theme_background"?: string;
        "theme_cover_preparation"?: boolean;
        "theme_teacher"?: string;
        "theme_teacher_avatar"?: string;
        "theme_teacher_bg"?: boolean;
        "theme_title"?: string;
        "theme_title_bg"?: boolean;
    }
    interface YduqsDemo {
        "cor"?: string;
        "texto"?: string;
    }
    interface YduqsDropdown {
        "colsize"?: string;
    }
    interface YduqsFooter {
    }
    interface YduqsImage {
        "alt"?: string;
        "bgcolor"?: string;
        "covered"?: boolean;
        "height"?: string;
        "img_title"?: string;
        "src"?: string;
        "width"?: string;
    }
    interface YduqsInput {
        "icon"?: any;
        "placeh"?: string;
        "titulo"?: string;
    }
    interface YduqsLoading {
        "message"?: string;
        "onClose"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface YduqsMediaBody {
    }
    interface YduqsMediaImage {
        "alt"?: string;
        "src"?: string;
    }
    interface YduqsMediaItem {
    }
    interface YduqsMenu {
        "onChangemenudata"?: (event: CustomEvent<any>) => void;
        "onClickmenuitem"?: (event: CustomEvent<any>) => void;
        "settings"?: YduqsMenuModel;
    }
    interface YduqsModal {
        "isopen"?: boolean;
        "maxbodyheight"?: number;
        "onModalClosed"?: (event: CustomEvent<boolean>) => void;
    }
    interface YduqsModuleCover {
        "img_cover"?: string;
        "midia_time"?: string;
        "number_module"?: string;
        "objective"?: string;
        "read_time"?: string;
        "title_midia_time"?: string;
        "title_module"?: string;
        "title_read_time"?: string;
    }
    interface YduqsNotification {
        "dismissible"?: boolean;
        "onClose"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "type"?: string;
    }
    interface YduqsNotifications {
        "position"?: string;
    }
    interface YduqsProgress {
        "onChanged"?: (event: CustomEvent<any>) => void;
        "rounded"?: boolean;
        "semirounded"?: boolean;
    }
    interface YduqsProgressBar {
        "displayValue"?: boolean;
        "max"?: number;
        "min"?: number;
        "onChangebar"?: (event: CustomEvent<any>) => void;
        "onHoverbar"?: (event: CustomEvent<any>) => void;
        "semirounded"?: boolean;
        "value"?: number;
    }
    interface YduqsQuestions {
        "question_id"?: string;
        "settings"?: YduqsQuestionsModel;
    }
    interface YduqsQuote {
        "dark"?: boolean;
        "size"?: string;
    }
    interface YduqsQuoteBody {
    }
    interface YduqsQuoteImage {
        "path"?: string;
    }
    interface YduqsRating {
        "cta"?: string;
    }
    interface YduqsSectionCover {
        "section_icon"?: string;
        "section_image"?: string;
    }
    interface YduqsTab {
        "disabled"?: boolean;
        "header"?: string;
        "open"?: boolean;
        "type"?: string;
    }
    interface YduqsTabs {
        "isdarkmode"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
    }
    interface YduqsTag {
        "color"?: string;
    }
    interface YduqsTags {
    }
    interface YduqsTextarea {
        "cta"?: string;
        "placeholder"?: string;
        "txt_button"?: string;
    }
    interface YduqsTimeline {
        "dark"?: boolean;
        "horizontal"?: boolean;
    }
    interface YduqsTimelineItem {
        "icon"?: string;
        "last"?: boolean;
    }
    interface YduqsTitle {
        "dark"?: boolean;
        "topic_icon"?: string;
        "topic_title"?: string;
    }
    interface YduqsToggle {
        "disable"?: boolean;
        "onMyToggleEmit"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "teste"?: String;
    }
    interface YduqsVideoPlayer {
        "bgcolor"?: string;
        "covered"?: boolean;
        "height"?: string;
        "src"?: string;
        "videoId"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "yduqs-accordion": YduqsAccordion;
        "yduqs-accordion-pane": YduqsAccordionPane;
        "yduqs-activity": YduqsActivity;
        "yduqs-audio-player": YduqsAudioPlayer;
        "yduqs-before-after": YduqsBeforeAfter;
        "yduqs-card": YduqsCard;
        "yduqs-card-body": YduqsCardBody;
        "yduqs-card-comparativo": YduqsCardComparativo;
        "yduqs-card-comparativo-body": YduqsCardComparativoBody;
        "yduqs-card-comparativo-header": YduqsCardComparativoHeader;
        "yduqs-card-comparativo-item": YduqsCardComparativoItem;
        "yduqs-card-destaque": YduqsCardDestaque;
        "yduqs-card-destaque-body": YduqsCardDestaqueBody;
        "yduqs-card-destaque-header": YduqsCardDestaqueHeader;
        "yduqs-card-footer": YduqsCardFooter;
        "yduqs-card-header": YduqsCardHeader;
        "yduqs-card-intro": YduqsCardIntro;
        "yduqs-card-modulo": YduqsCardModulo;
        "yduqs-card-modulo-body": YduqsCardModuloBody;
        "yduqs-card-modulo-footer": YduqsCardModuloFooter;
        "yduqs-card-modulo-header": YduqsCardModuloHeader;
        "yduqs-card-selecionavel": YduqsCardSelecionavel;
        "yduqs-card-selecionavel-item": YduqsCardSelecionavelItem;
        "yduqs-carousel": YduqsCarousel;
        "yduqs-carousel-item": YduqsCarouselItem;
        "yduqs-code-snipet": YduqsCodeSnipet;
        "yduqs-collapse": YduqsCollapse;
        "yduqs-collapse-content": YduqsCollapseContent;
        "yduqs-cover": YduqsCover;
        "yduqs-demo": YduqsDemo;
        "yduqs-dropdown": YduqsDropdown;
        "yduqs-footer": YduqsFooter;
        "yduqs-image": YduqsImage;
        "yduqs-input": YduqsInput;
        "yduqs-loading": YduqsLoading;
        "yduqs-media-body": YduqsMediaBody;
        "yduqs-media-image": YduqsMediaImage;
        "yduqs-media-item": YduqsMediaItem;
        "yduqs-menu": YduqsMenu;
        "yduqs-modal": YduqsModal;
        "yduqs-module-cover": YduqsModuleCover;
        "yduqs-notification": YduqsNotification;
        "yduqs-notifications": YduqsNotifications;
        "yduqs-progress": YduqsProgress;
        "yduqs-progress-bar": YduqsProgressBar;
        "yduqs-questions": YduqsQuestions;
        "yduqs-quote": YduqsQuote;
        "yduqs-quote-body": YduqsQuoteBody;
        "yduqs-quote-image": YduqsQuoteImage;
        "yduqs-rating": YduqsRating;
        "yduqs-section-cover": YduqsSectionCover;
        "yduqs-tab": YduqsTab;
        "yduqs-tabs": YduqsTabs;
        "yduqs-tag": YduqsTag;
        "yduqs-tags": YduqsTags;
        "yduqs-textarea": YduqsTextarea;
        "yduqs-timeline": YduqsTimeline;
        "yduqs-timeline-item": YduqsTimelineItem;
        "yduqs-title": YduqsTitle;
        "yduqs-toggle": YduqsToggle;
        "yduqs-video-player": YduqsVideoPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "yduqs-accordion": LocalJSX.YduqsAccordion & JSXBase.HTMLAttributes<HTMLYduqsAccordionElement>;
            "yduqs-accordion-pane": LocalJSX.YduqsAccordionPane & JSXBase.HTMLAttributes<HTMLYduqsAccordionPaneElement>;
            "yduqs-activity": LocalJSX.YduqsActivity & JSXBase.HTMLAttributes<HTMLYduqsActivityElement>;
            "yduqs-audio-player": LocalJSX.YduqsAudioPlayer & JSXBase.HTMLAttributes<HTMLYduqsAudioPlayerElement>;
            "yduqs-before-after": LocalJSX.YduqsBeforeAfter & JSXBase.HTMLAttributes<HTMLYduqsBeforeAfterElement>;
            "yduqs-card": LocalJSX.YduqsCard & JSXBase.HTMLAttributes<HTMLYduqsCardElement>;
            "yduqs-card-body": LocalJSX.YduqsCardBody & JSXBase.HTMLAttributes<HTMLYduqsCardBodyElement>;
            "yduqs-card-comparativo": LocalJSX.YduqsCardComparativo & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoElement>;
            "yduqs-card-comparativo-body": LocalJSX.YduqsCardComparativoBody & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoBodyElement>;
            "yduqs-card-comparativo-header": LocalJSX.YduqsCardComparativoHeader & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoHeaderElement>;
            "yduqs-card-comparativo-item": LocalJSX.YduqsCardComparativoItem & JSXBase.HTMLAttributes<HTMLYduqsCardComparativoItemElement>;
            "yduqs-card-destaque": LocalJSX.YduqsCardDestaque & JSXBase.HTMLAttributes<HTMLYduqsCardDestaqueElement>;
            "yduqs-card-destaque-body": LocalJSX.YduqsCardDestaqueBody & JSXBase.HTMLAttributes<HTMLYduqsCardDestaqueBodyElement>;
            "yduqs-card-destaque-header": LocalJSX.YduqsCardDestaqueHeader & JSXBase.HTMLAttributes<HTMLYduqsCardDestaqueHeaderElement>;
            "yduqs-card-footer": LocalJSX.YduqsCardFooter & JSXBase.HTMLAttributes<HTMLYduqsCardFooterElement>;
            "yduqs-card-header": LocalJSX.YduqsCardHeader & JSXBase.HTMLAttributes<HTMLYduqsCardHeaderElement>;
            "yduqs-card-intro": LocalJSX.YduqsCardIntro & JSXBase.HTMLAttributes<HTMLYduqsCardIntroElement>;
            "yduqs-card-modulo": LocalJSX.YduqsCardModulo & JSXBase.HTMLAttributes<HTMLYduqsCardModuloElement>;
            "yduqs-card-modulo-body": LocalJSX.YduqsCardModuloBody & JSXBase.HTMLAttributes<HTMLYduqsCardModuloBodyElement>;
            "yduqs-card-modulo-footer": LocalJSX.YduqsCardModuloFooter & JSXBase.HTMLAttributes<HTMLYduqsCardModuloFooterElement>;
            "yduqs-card-modulo-header": LocalJSX.YduqsCardModuloHeader & JSXBase.HTMLAttributes<HTMLYduqsCardModuloHeaderElement>;
            "yduqs-card-selecionavel": LocalJSX.YduqsCardSelecionavel & JSXBase.HTMLAttributes<HTMLYduqsCardSelecionavelElement>;
            "yduqs-card-selecionavel-item": LocalJSX.YduqsCardSelecionavelItem & JSXBase.HTMLAttributes<HTMLYduqsCardSelecionavelItemElement>;
            "yduqs-carousel": LocalJSX.YduqsCarousel & JSXBase.HTMLAttributes<HTMLYduqsCarouselElement>;
            "yduqs-carousel-item": LocalJSX.YduqsCarouselItem & JSXBase.HTMLAttributes<HTMLYduqsCarouselItemElement>;
            "yduqs-code-snipet": LocalJSX.YduqsCodeSnipet & JSXBase.HTMLAttributes<HTMLYduqsCodeSnipetElement>;
            "yduqs-collapse": LocalJSX.YduqsCollapse & JSXBase.HTMLAttributes<HTMLYduqsCollapseElement>;
            "yduqs-collapse-content": LocalJSX.YduqsCollapseContent & JSXBase.HTMLAttributes<HTMLYduqsCollapseContentElement>;
            "yduqs-cover": LocalJSX.YduqsCover & JSXBase.HTMLAttributes<HTMLYduqsCoverElement>;
            "yduqs-demo": LocalJSX.YduqsDemo & JSXBase.HTMLAttributes<HTMLYduqsDemoElement>;
            "yduqs-dropdown": LocalJSX.YduqsDropdown & JSXBase.HTMLAttributes<HTMLYduqsDropdownElement>;
            "yduqs-footer": LocalJSX.YduqsFooter & JSXBase.HTMLAttributes<HTMLYduqsFooterElement>;
            "yduqs-image": LocalJSX.YduqsImage & JSXBase.HTMLAttributes<HTMLYduqsImageElement>;
            "yduqs-input": LocalJSX.YduqsInput & JSXBase.HTMLAttributes<HTMLYduqsInputElement>;
            "yduqs-loading": LocalJSX.YduqsLoading & JSXBase.HTMLAttributes<HTMLYduqsLoadingElement>;
            "yduqs-media-body": LocalJSX.YduqsMediaBody & JSXBase.HTMLAttributes<HTMLYduqsMediaBodyElement>;
            "yduqs-media-image": LocalJSX.YduqsMediaImage & JSXBase.HTMLAttributes<HTMLYduqsMediaImageElement>;
            "yduqs-media-item": LocalJSX.YduqsMediaItem & JSXBase.HTMLAttributes<HTMLYduqsMediaItemElement>;
            "yduqs-menu": LocalJSX.YduqsMenu & JSXBase.HTMLAttributes<HTMLYduqsMenuElement>;
            "yduqs-modal": LocalJSX.YduqsModal & JSXBase.HTMLAttributes<HTMLYduqsModalElement>;
            "yduqs-module-cover": LocalJSX.YduqsModuleCover & JSXBase.HTMLAttributes<HTMLYduqsModuleCoverElement>;
            "yduqs-notification": LocalJSX.YduqsNotification & JSXBase.HTMLAttributes<HTMLYduqsNotificationElement>;
            "yduqs-notifications": LocalJSX.YduqsNotifications & JSXBase.HTMLAttributes<HTMLYduqsNotificationsElement>;
            "yduqs-progress": LocalJSX.YduqsProgress & JSXBase.HTMLAttributes<HTMLYduqsProgressElement>;
            "yduqs-progress-bar": LocalJSX.YduqsProgressBar & JSXBase.HTMLAttributes<HTMLYduqsProgressBarElement>;
            "yduqs-questions": LocalJSX.YduqsQuestions & JSXBase.HTMLAttributes<HTMLYduqsQuestionsElement>;
            "yduqs-quote": LocalJSX.YduqsQuote & JSXBase.HTMLAttributes<HTMLYduqsQuoteElement>;
            "yduqs-quote-body": LocalJSX.YduqsQuoteBody & JSXBase.HTMLAttributes<HTMLYduqsQuoteBodyElement>;
            "yduqs-quote-image": LocalJSX.YduqsQuoteImage & JSXBase.HTMLAttributes<HTMLYduqsQuoteImageElement>;
            "yduqs-rating": LocalJSX.YduqsRating & JSXBase.HTMLAttributes<HTMLYduqsRatingElement>;
            "yduqs-section-cover": LocalJSX.YduqsSectionCover & JSXBase.HTMLAttributes<HTMLYduqsSectionCoverElement>;
            "yduqs-tab": LocalJSX.YduqsTab & JSXBase.HTMLAttributes<HTMLYduqsTabElement>;
            "yduqs-tabs": LocalJSX.YduqsTabs & JSXBase.HTMLAttributes<HTMLYduqsTabsElement>;
            "yduqs-tag": LocalJSX.YduqsTag & JSXBase.HTMLAttributes<HTMLYduqsTagElement>;
            "yduqs-tags": LocalJSX.YduqsTags & JSXBase.HTMLAttributes<HTMLYduqsTagsElement>;
            "yduqs-textarea": LocalJSX.YduqsTextarea & JSXBase.HTMLAttributes<HTMLYduqsTextareaElement>;
            "yduqs-timeline": LocalJSX.YduqsTimeline & JSXBase.HTMLAttributes<HTMLYduqsTimelineElement>;
            "yduqs-timeline-item": LocalJSX.YduqsTimelineItem & JSXBase.HTMLAttributes<HTMLYduqsTimelineItemElement>;
            "yduqs-title": LocalJSX.YduqsTitle & JSXBase.HTMLAttributes<HTMLYduqsTitleElement>;
            "yduqs-toggle": LocalJSX.YduqsToggle & JSXBase.HTMLAttributes<HTMLYduqsToggleElement>;
            "yduqs-video-player": LocalJSX.YduqsVideoPlayer & JSXBase.HTMLAttributes<HTMLYduqsVideoPlayerElement>;
        }
    }
}
